-- =====================================================================================
-- examen-inicial-01-ddl.sql
-- Modulo "Examen medico inicial" (FT-SO-04 rev. 04) + notificaciones de la campanita.
-- Para ejecutar en la BASE DEL PORTAL en produccion: BIOMETRICO@PDBPRD (NO en ORDS).
--
-- Generado el 3-oct-2026 a partir de (ya aplicados y probados en QA el mismo dia):
--   src/main/resources/db/sql/app_domain/examen-inicial.sql
--   src/main/resources/db/sql/app_domain/notificaciones.sql
--   src/main/resources/db/sql/app_domain/examen-historico.sql
--
-- QUE HACE
--   1. SERV_MED_EXAMEN_BORRADOR : borrador del examen inicial (se guarda solo hoja por hoja)
--                                 y constancia de que un examen se finalizo desde ese modulo.
--                                 El examen terminado NO vive aqui: va al mismo almacen de
--                                 siempre (WS Servcio/Medico + SERV_MED_TAG, tipo Admision).
--   2. Menu EXAMEN_INICIAL        : entrada "Examen Medico Inicial" en el expediente de la
--                                 persona, asignada a los MISMOS roles que ya ven EXAMEN_MEDICO.
--   3. SERV_MED_NOTIFICACION     : notificaciones de la campanita (primer uso: la solicitud de
--                                 examen inicial que mandara OCR). Hoy se crean solo a mano.
--   4. SERV_MED_EXAMEN_HISTORICO : una fila por examen finalizado, desde los DOS modulos, con el
--                                 examen completo en JSON (el WS solo guarda uno por persona y lo
--                                 pisa). Sirve para el candado del inicial, el tipo de examen en
--                                 el dashboard y la lista de no aptos. No aporta cantidades al
--                                 dashboard, solo etiquetas.
--
-- NO HACE: no toca ninguna tabla existente, no cambia datos, no toca ORDS.
--
-- QUIEN LO EJECUTA: el usuario / el DBA, en SQL Developer, conectado como BIOMETRICO.
-- El agente no ejecuta nada contra esta base (regla del 23-sep-2026).
--
-- IDEMPOTENTE: cada CREATE ignora ORA-00955 (ya existe) y los INSERT comprueban antes.
-- Se puede volver a correr sin dano.
--
-- DESPLIEGUE: el WAR con el modulo debe ir en el mismo paso (rama examen-inicial). Sin el
-- WAR las tablas no estorban; sin las tablas el modulo abre pero avisa que no puede guardar
-- y la campanita queda en 0.
--
-- REVERSA: al final del archivo, comentada.
-- =====================================================================================
SET SERVEROUTPUT ON;
-- Los enlaces de notificacion llevan "&": sin esto SQL Developer pide valores de sustitucion.
SET DEFINE OFF;

-- -------------------------------------------------------------------------------------
-- PRE-CHECK (solo lectura): nada de esto debe existir todavia. Si alguna fila sale, parar y revisar.
-- -------------------------------------------------------------------------------------
SELECT object_type, object_name
  FROM user_objects
 WHERE object_name IN ('SERV_MED_EXAMEN_BORRADOR', 'SERV_MED_PK_EXAMEN_BORRADOR', 'SERV_MED_IX_EXAMEN_BORR_NSS',
                       'SERV_MED_NOTIFICACION', 'SERV_MED_PK_NOTIFICACION', 'SERV_MED_IX_NOTIF_PEND',
                       'SERV_MED_EXAMEN_HISTORICO', 'SERV_MED_PK_EXAMEN_HIST', 'SERV_MED_IX_EXAMEN_HIST_NSS');
SELECT ID, CODE, TITLE FROM SERV_MED_MENU WHERE CODE = 'EXAMEN_INICIAL';

-- -------------------------------------------------------------------------------------
-- 1. Borrador del examen inicial
-- -------------------------------------------------------------------------------------
BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE SERV_MED_EXAMEN_BORRADOR (
      ID             NUMBER GENERATED BY DEFAULT AS IDENTITY
                     CONSTRAINT SERV_MED_PK_EXAMEN_BORRADOR PRIMARY KEY,
      NSS            VARCHAR2(50)  NOT NULL,
      TIPO_EXAMEN    VARCHAR2(20)  DEFAULT 'INICIAL'  NOT NULL,   -- INICIAL (unico por ahora)
      ESTATUS        VARCHAR2(20)  DEFAULT 'BORRADOR' NOT NULL,   -- BORRADOR | FINALIZADO
      HOJA_ACTUAL    NUMBER(2)     DEFAULT 1 NOT NULL,            -- donde se quedo el medico
      DATOS          CLOB,                                        -- JSON {clave: valor}
      CREATED_AT     TIMESTAMP(6)  DEFAULT SYSTIMESTAMP NOT NULL,
      CREATED_BY     VARCHAR2(100),
      UPDATED_AT     TIMESTAMP(6)  DEFAULT SYSTIMESTAMP NOT NULL,
      UPDATED_BY     VARCHAR2(100),
      FINALIZADO_AT  TIMESTAMP(6),
      FINALIZADO_BY  VARCHAR2(100),
      CONSTRAINT SERV_MED_CK_EXAMEN_BORR_EST CHECK (ESTATUS IN ('BORRADOR','FINALIZADO'))
    )
  ]';
  DBMS_OUTPUT.PUT_LINE('SERV_MED_EXAMEN_BORRADOR creada');
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; ELSE DBMS_OUTPUT.PUT_LINE('SERV_MED_EXAMEN_BORRADOR ya existia'); END IF; END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX SERV_MED_IX_EXAMEN_BORR_NSS ON SERV_MED_EXAMEN_BORRADOR (NSS, ESTATUS)';
  DBMS_OUTPUT.PUT_LINE('SERV_MED_IX_EXAMEN_BORR_NSS creado');
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; ELSE DBMS_OUTPUT.PUT_LINE('SERV_MED_IX_EXAMEN_BORR_NSS ya existia'); END IF; END;
/

-- -------------------------------------------------------------------------------------
-- 2. Menu EXAMEN_INICIAL, asignado a los roles que ya ven EXAMEN_MEDICO
--    (fragments/nss-modules.html resuelve la pantalla por CODE; el ID es el IDENTITY)
-- -------------------------------------------------------------------------------------
DECLARE
  v_n NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_n FROM SERV_MED_MENU WHERE CODE = 'EXAMEN_INICIAL';
  IF v_n = 0 THEN
    INSERT INTO SERV_MED_MENU (CODE, TITLE, ICON, ORDER_NO, ACTIVE)
    VALUES ('EXAMEN_INICIAL', 'Examen Médico Inicial', 'ri-file-add-line',
            (SELECT NVL(MAX(ORDER_NO), 0) + 1 FROM SERV_MED_MENU WHERE CODE = 'EXAMEN_MEDICO'), 'Y');
    DBMS_OUTPUT.PUT_LINE('Menu EXAMEN_INICIAL insertado');
  ELSE
    DBMS_OUTPUT.PUT_LINE('Menu EXAMEN_INICIAL ya existia');
  END IF;

  INSERT INTO SERV_MED_MENU_ROLE (MENU_ID, ROLE_ID)
  SELECT n.ID, mr.ROLE_ID
    FROM SERV_MED_MENU n, SERV_MED_MENU m
    JOIN SERV_MED_MENU_ROLE mr ON mr.MENU_ID = m.ID
   WHERE n.CODE = 'EXAMEN_INICIAL' AND m.CODE = 'EXAMEN_MEDICO'
     AND NOT EXISTS (SELECT 1 FROM SERV_MED_MENU_ROLE x WHERE x.MENU_ID = n.ID AND x.ROLE_ID = mr.ROLE_ID);
  DBMS_OUTPUT.PUT_LINE('Roles asignados a EXAMEN_INICIAL: ' || SQL%ROWCOUNT);
  COMMIT;
END;
/

-- -------------------------------------------------------------------------------------
-- 3. Notificaciones (campanita)
-- -------------------------------------------------------------------------------------
BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE SERV_MED_NOTIFICACION (
      ID                 NUMBER GENERATED BY DEFAULT AS IDENTITY
                         CONSTRAINT SERV_MED_PK_NOTIFICACION PRIMARY KEY,
      TIPO               VARCHAR2(40)  NOT NULL,          -- EXAMEN_INICIAL_SOLICITUD, ...
      TITULO             VARCHAR2(200) NOT NULL,
      MENSAJE            VARCHAR2(1000),
      NSS                VARCHAR2(50),
      ENLACE             VARCHAR2(400),                   -- ruta relativa al portal (nss?nss=...&abrir=examen-inicial)
      DESTINO_MENU_CODE  VARCHAR2(120),                   -- la ven los roles con ese menu (SERV_MED_MENU.CODE)
      DESTINO_USUARIO    VARCHAR2(100),                   -- o un usuario concreto
      ORIGEN             VARCHAR2(60),                    -- OCR, PORTAL, ...
      REFERENCIA         VARCHAR2(120),                   -- id externo (p.ej. referenciaOcr)
      CREATED_AT         TIMESTAMP(6)  DEFAULT SYSTIMESTAMP NOT NULL,
      CREATED_BY         VARCHAR2(100),
      LEIDA_AT           TIMESTAMP(6),
      LEIDA_POR          VARCHAR2(100)
    )
  ]';
  DBMS_OUTPUT.PUT_LINE('SERV_MED_NOTIFICACION creada');
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; ELSE DBMS_OUTPUT.PUT_LINE('SERV_MED_NOTIFICACION ya existia'); END IF; END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX SERV_MED_IX_NOTIF_PEND ON SERV_MED_NOTIFICACION (LEIDA_AT, CREATED_AT)';
  DBMS_OUTPUT.PUT_LINE('SERV_MED_IX_NOTIF_PEND creado');
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; ELSE DBMS_OUTPUT.PUT_LINE('SERV_MED_IX_NOTIF_PEND ya existia'); END IF; END;
/

-- -------------------------------------------------------------------------------------
-- 4. Historico de examenes finalizados (foto completa por examen, desde los dos modulos)
-- -------------------------------------------------------------------------------------
BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE SERV_MED_EXAMEN_HISTORICO (
      ID             NUMBER GENERATED BY DEFAULT AS IDENTITY
                     CONSTRAINT SERV_MED_PK_EXAMEN_HIST PRIMARY KEY,
      NSS            VARCHAR2(50)  NOT NULL,
      ORIGEN         VARCHAR2(20)  NOT NULL,            -- INICIAL (modulo inicial) | GENERAL (modulo Examen medico)
      TIPO_EXAMEN    VARCHAR2(5),                       -- codigo del legacy: 1 Admision, 2 Periodico, 3 Cambio de rol,
                                                        -- 4 Post incapacidad, 5 Especial; NULL si no se capturo
      DICTAMEN       VARCHAR2(30),                      -- apto | no_apto | apto_condicionado | apto_restringido
      FECHA_EXAMEN   TIMESTAMP(6)  DEFAULT SYSTIMESTAMP NOT NULL,
      USUARIO        VARCHAR2(100),
      DATOS          CLOB,                              -- examen completo aplanado {SECCION.CAMPO: valor}
      CREATED_AT     TIMESTAMP(6)  DEFAULT SYSTIMESTAMP NOT NULL,
      CONSTRAINT SERV_MED_CK_EXAMEN_HIST_ORI CHECK (ORIGEN IN ('INICIAL','GENERAL'))
    )
  ]';
  DBMS_OUTPUT.PUT_LINE('SERV_MED_EXAMEN_HISTORICO creada');
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; ELSE DBMS_OUTPUT.PUT_LINE('SERV_MED_EXAMEN_HISTORICO ya existia'); END IF; END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX SERV_MED_IX_EXAMEN_HIST_NSS ON SERV_MED_EXAMEN_HISTORICO (NSS, FECHA_EXAMEN)';
  DBMS_OUTPUT.PUT_LINE('SERV_MED_IX_EXAMEN_HIST_NSS creado');
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; ELSE DBMS_OUTPUT.PUT_LINE('SERV_MED_IX_EXAMEN_HIST_NSS ya existia'); END IF; END;
/

-- -------------------------------------------------------------------------------------
-- POST-CHECK (solo lectura): 3 tablas, 3 indices, 1 menu con al menos 1 rol.
-- -------------------------------------------------------------------------------------
SELECT object_type, object_name, status
  FROM user_objects
 WHERE object_name IN ('SERV_MED_EXAMEN_BORRADOR', 'SERV_MED_IX_EXAMEN_BORR_NSS', 'SERV_MED_NOTIFICACION', 'SERV_MED_IX_NOTIF_PEND',
                       'SERV_MED_EXAMEN_HISTORICO', 'SERV_MED_IX_EXAMEN_HIST_NSS')
 ORDER BY 1, 2;
SELECT m.CODE, m.TITLE, m.ACTIVE, COUNT(mr.ROLE_ID) AS roles
  FROM SERV_MED_MENU m LEFT JOIN SERV_MED_MENU_ROLE mr ON mr.MENU_ID = m.ID
 WHERE m.CODE IN ('EXAMEN_MEDICO', 'EXAMEN_INICIAL')
 GROUP BY m.CODE, m.TITLE, m.ACTIVE;

-- -------------------------------------------------------------------------------------
-- REVERSA (solo si hay que echar atras el despliegue; descomentar y correr en este orden)
-- -------------------------------------------------------------------------------------
-- DELETE FROM SERV_MED_MENU_ROLE WHERE MENU_ID IN (SELECT ID FROM SERV_MED_MENU WHERE CODE = 'EXAMEN_INICIAL');
-- DELETE FROM SERV_MED_MENU WHERE CODE = 'EXAMEN_INICIAL';
-- COMMIT;
-- DROP TABLE SERV_MED_EXAMEN_HISTORICO PURGE;
-- DROP TABLE SERV_MED_NOTIFICACION PURGE;
-- DROP TABLE SERV_MED_EXAMEN_BORRADOR PURGE;
