-- ============================================================================
-- CARGA DE EXCEL 2026 -- DDL de las tablas destino
--
-- BASE: la del PORTAL (JDBC). En produccion eso es BIOMETRICO.
--       NO es ORDS. Aqui no hay ningun WS ni ninguna tabla del legacy.
--
-- QUE HACE:  crea 3 tablas nuevas, 8 indices explicitos (+3 que Oracle
--            crea solo para las llaves primarias = 11 en total) y
--            2 llaves foraneas ENTRE LAS TABLAS NUEVAS.
-- QUE NO HACE: ni un solo ALTER, DROP, TRUNCATE, GRANT ni UPDATE sobre
--            nada que ya exista. BIOMETRICO tiene 595 tablas (medido el
--            29-sep-2026 en el PRE-CHECK); no toca ninguna, ni las 20
--            del portal.
--
-- APLICADO en BIOMETRICO@PDBPRD el 29-sep-2026. Resultado verificado:
-- 3 tablas VALID, 12 indices (8 explicitos + 3 de PK + 1 del CLOB
-- MENSAJES), 3 PRIMARY KEY, 2 FOREIGN KEY, 18 NOT NULL.
--
-- Es idempotente: si ya existe algo, lo salta (guard -955 / -1408).
-- Se puede correr dos veces sin efecto.
--
-- Nombre: la hoja de 2017 se titula literalmente "BITACORA DE ATENCION",
-- que es como el servicio medico llama a estos archivos.
-- ============================================================================

SET SERVEROUTPUT ON
SET LINESIZE 200

-- ----------------------------------------------------------------------
-- PRE-CHECK  (solo lectura). Correr ESTO primero y leer la salida.
-- Si reporta colisiones, parar y avisar antes de crear nada.
-- ----------------------------------------------------------------------
DECLARE
  v_n NUMBER;
BEGIN
  DBMS_OUTPUT.PUT_LINE('=== PRE-CHECK ===');
  DBMS_OUTPUT.PUT_LINE('Usuario: ' || USER ||
                       '  Base: ' || SYS_CONTEXT('USERENV','DB_NAME') ||
                       '  PDB: '  || SYS_CONTEXT('USERENV','CON_NAME'));

  SELECT COUNT(*) INTO v_n FROM user_tables;
  DBMS_OUTPUT.PUT_LINE('Tablas que ya tiene este esquema: ' || v_n);

  SELECT COUNT(*) INTO v_n FROM user_objects
   WHERE object_name IN ('SERV_MED_BITACORA_LOTE',
                         'SERV_MED_BITACORA_EVENTO',
                         'SERV_MED_BITACORA_ATRIBUTO');
  IF v_n = 0 THEN
    DBMS_OUTPUT.PUT_LINE('Las 3 tablas nuevas NO existen todavia: OK, se van a crear.');
  ELSE
    DBMS_OUTPUT.PUT_LINE('ATENCION: ya existen ' || v_n || ' de los 3 objetos.');
    DBMS_OUTPUT.PUT_LINE('El script los va a saltar, no los va a modificar.');
  END IF;

  -- Que ningun nombre pase de 30 caracteres (limite del esquema legacy)
  SELECT COUNT(*) INTO v_n FROM (
    SELECT 'SERV_MED_BITACORA_LOTE' n FROM dual UNION ALL
    SELECT 'SERV_MED_BITACORA_EVENTO' FROM dual UNION ALL
    SELECT 'SERV_MED_BITACORA_ATRIBUTO' FROM dual UNION ALL
    SELECT 'SERV_MED_UX_BITACORA_ORIGEN' FROM dual UNION ALL
    SELECT 'SERV_MED_IX_BITACORA_FAM_MES' FROM dual UNION ALL
    SELECT 'SERV_MED_IX_BITACORA_PREDIO' FROM dual UNION ALL
    SELECT 'SERV_MED_IX_BITACORA_CUENTA' FROM dual UNION ALL
    SELECT 'SERV_MED_IX_BITACORA_LOTE' FROM dual UNION ALL
    SELECT 'SERV_MED_IX_ATRIB_EVENTO' FROM dual UNION ALL
    SELECT 'SERV_MED_IX_ATRIB_NOM_VAL' FROM dual UNION ALL
    SELECT 'SERV_MED_UX_BITACORA_LOTE_AR' FROM dual
  ) WHERE LENGTH(n) > 30;
  IF v_n > 0 THEN
    DBMS_OUTPUT.PUT_LINE('ERROR: ' || v_n || ' nombres pasan de 30 caracteres.');
  ELSE
    DBMS_OUTPUT.PUT_LINE('Todos los nombres caben en 30 caracteres: OK.');
  END IF;
  DBMS_OUTPUT.PUT_LINE('=== FIN PRE-CHECK ===');
END;
/


-- ======================================================================
-- TABLA 1 de 3:  SERV_MED_BITACORA_LOTE
-- Un renglon por ARCHIVO+HOJA procesado. Es la bitacora de la carga y,
-- sobre todo, el CUADRE: cada Excel trae su propia hoja ACUMULADO con
-- los totales, asi que el cargador compara lo que conto contra lo que el
-- archivo dice de si mismo. Verificado: en ENE 2017 el detalle da 103
-- renglones y el ACUMULADO dice 103.
-- ======================================================================
BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE SERV_MED_BITACORA_LOTE (
      ID                  NUMBER GENERATED BY DEFAULT AS IDENTITY
                          CONSTRAINT SERV_MED_PK_BITACORA_LOTE PRIMARY KEY,
      ARCHIVO             VARCHAR2(400)  NOT NULL,   -- nombre del archivo, tal cual
      RUTA                VARCHAR2(1000),            -- ruta completa de donde se leyo
      CHECKSUM_SHA256     VARCHAR2(64),              -- detecta copias: TOLUCA vs TOLUCA1
      HOJA                VARCHAR2(120),             -- hoja procesada de ese archivo
      FAMILIA             VARCHAR2(40)   NOT NULL,   -- ATENCION, EXAMEN_INGRESO, ...
      PREDIO              VARCHAR2(120),             -- resuelto del nombre/contenido
      ANIO                NUMBER(4),                 -- del CONTENIDO, nunca de la carpeta
      FILAS_LEIDAS        NUMBER DEFAULT 0,
      FILAS_INSERTADAS    NUMBER DEFAULT 0,
      FILAS_DESCARTADAS   NUMBER DEFAULT 0,
      -- Autoverificacion contra la hoja ACUMULADO del propio Excel
      ACUMULADO_ESPERADO  NUMBER,
      CUADRA              VARCHAR2(1),               -- S / N / NULL si no hay ACUMULADO
      ESTADO              VARCHAR2(30) DEFAULT 'PENDIENTE' NOT NULL, -- OK, CON_AVISOS, ERROR
      MENSAJES            CLOB,                      -- por que se descarto cada fila
      STARTED_AT          TIMESTAMP(6),
      FINISHED_AT         TIMESTAMP(6),
      CREATED_AT          TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
      CREATED_BY          VARCHAR2(100) DEFAULT 'CARGA_EXCEL' NOT NULL
    )
  ]';
EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-955) THEN RAISE; END IF; END;
/

COMMENT ON TABLE SERV_MED_BITACORA_LOTE IS
  'Carga de Excel: un renglon por archivo+hoja. CUADRA compara lo contado contra la hoja ACUMULADO del propio Excel.';

-- Un mismo archivo+hoja no se procesa dos veces (idempotencia de la corrida)
BEGIN EXECUTE IMMEDIATE
  'CREATE UNIQUE INDEX SERV_MED_UX_BITACORA_LOTE_AR ON SERV_MED_BITACORA_LOTE (ARCHIVO, HOJA)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-955,-1408) THEN RAISE; END IF; END;
/


-- ======================================================================
-- TABLA 2 de 3:  SERV_MED_BITACORA_EVENTO
-- Un renglon por atencion / examen / incapacidad / accidente / etc.
-- YA TRANSPUESTO: el "marca con 1" del Excel se resuelve aqui a un valor.
--
-- Las columnas fijas son el esqueleto que comparten las 8 familias de
-- eventos. Lo propio de cada familia va en SERV_MED_BITACORA_ATRIBUTO,
-- y por eso NO hace falta una tabla por familia ni ALTER mas adelante.
--
-- Consumibles queda FUERA a proposito: son renglones de inventario
-- (medicamento, lote, caducidad, costo), no eventos por persona. Esa
-- tabla se define aparte cuando se analice esa familia.
-- ======================================================================
BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE SERV_MED_BITACORA_EVENTO (
      ID              NUMBER GENERATED BY DEFAULT AS IDENTITY
                      CONSTRAINT SERV_MED_PK_BITACORA_EVE PRIMARY KEY,
      LOTE_ID         NUMBER        NOT NULL,
      FAMILIA         VARCHAR2(40)  NOT NULL,

      -- Cuando
      FECHA           DATE,
      ANIO            NUMBER(4),      -- derivadas al cargar: evitan EXTRACT en
      MES             NUMBER(2),      -- cada consulta de la grafica

      -- Donde  (dimensiones estables en los 10 anios)
      PREDIO          VARCHAR2(120),
      CUENTA          VARCHAR2(160),
      AREA            VARCHAR2(120),
      PUESTO          VARCHAR2(120),
      AGENCIA         VARCHAR2(120),

      -- Quien
      NOMBRE          VARCHAR2(300),  -- tal cual viene del Excel
      NOMBRE_NORM     VARCHAR2(300),  -- sin acentos, mayusculas, espacios simples
      NSS             VARCHAR2(50),   -- SIEMPRE NULL en la carga: el Excel no lo trae.
                                      -- Reservada por si despues se resuelve por nombre.
      RANGO_EDAD      VARCHAR2(20),   -- "18-25" ya normalizado (el Excel dice "18 - 25")
      GENERO          VARCHAR2(10),   -- FEM / MASC

      -- De donde salio cada cifra: permite rastrear hasta la celda
      ORIGEN_ARCHIVO  VARCHAR2(400) NOT NULL,
      ORIGEN_HOJA     VARCHAR2(120) NOT NULL,
      ORIGEN_FILA     NUMBER        NOT NULL,

      CREATED_AT      TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
      CREATED_BY      VARCHAR2(100) DEFAULT 'CARGA_EXCEL' NOT NULL,

      CONSTRAINT SERV_MED_FK_BITACORA_LOTE
        FOREIGN KEY (LOTE_ID) REFERENCES SERV_MED_BITACORA_LOTE (ID)
    )
  ]';
EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-955) THEN RAISE; END IF; END;
/

COMMENT ON TABLE SERV_MED_BITACORA_EVENTO IS
  'Carga de Excel: un evento por renglon, ya transpuesto. Lo propio de cada familia vive en SERV_MED_BITACORA_ATRIBUTO.';
COMMENT ON COLUMN SERV_MED_BITACORA_EVENTO.NSS IS
  'Siempre NULL: los Excel no traen NSS, solo nombre. Reservada por si se resuelve la identidad despues.';

-- Idempotencia real de la carga: la misma celda no entra dos veces
BEGIN EXECUTE IMMEDIATE
  'CREATE UNIQUE INDEX SERV_MED_UX_BITACORA_ORIGEN ON SERV_MED_BITACORA_EVENTO (ORIGEN_ARCHIVO, ORIGEN_HOJA, ORIGEN_FILA)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-955,-1408) THEN RAISE; END IF; END;
/

-- Patron de acceso de las graficas: familia + periodo
BEGIN EXECUTE IMMEDIATE
  'CREATE INDEX SERV_MED_IX_BITACORA_FAM_MES ON SERV_MED_BITACORA_EVENTO (FAMILIA, ANIO, MES)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-955,-1408) THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE
  'CREATE INDEX SERV_MED_IX_BITACORA_PREDIO ON SERV_MED_BITACORA_EVENTO (PREDIO)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-955,-1408) THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE
  'CREATE INDEX SERV_MED_IX_BITACORA_CUENTA ON SERV_MED_BITACORA_EVENTO (CUENTA)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-955,-1408) THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE
  'CREATE INDEX SERV_MED_IX_BITACORA_LOTE ON SERV_MED_BITACORA_EVENTO (LOTE_ID)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-955,-1408) THEN RAISE; END IF; END;
/


-- ======================================================================
-- TABLA 3 de 3:  SERV_MED_BITACORA_ATRIBUTO
-- Lo que cambia de familia a familia, sin una tabla por familia.
-- Mismo patron EAV que ya usa SERV_MED_TAG (550 mil renglones, probado).
--
-- Ejemplos de NOMBRE por familia:
--   ATENCION                -> CAUSA, RAMO, DIAGNOSTICO, TRATAMIENTO, LESION_ME
--   EXAMEN_*                -> DICTAMEN (15 APTO / 45 CONDICIONADO /
--                              60 RESTRINGIDO=INCLUSION / 30 NO APTO)
--   INCAPACIDAD             -> RAMO (EG/MAT/RT1/RT2), TIPO (IMSS/INTERNA),
--                              DIAS, COSTO, FECHA_INICIO, FECHA_FIN
--   ACCIDENTE               -> TIPO (RT1 laboral / RT2 trayecto /
--                              INCIDENTE / ENF_PROFESIONAL)
--   ANTIDOPING              -> RESULTADO, DESENLACE (MONITOREO/BAJA/NO_CONTRATADO)
--   MATERNIDAD              -> ESTADO, DIAS
--
-- Agregar una familia nueva NO requiere DDL: solo renglones nuevos aqui.
-- ======================================================================
BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE SERV_MED_BITACORA_ATRIBUTO (
      ID            NUMBER GENERATED BY DEFAULT AS IDENTITY
                    CONSTRAINT SERV_MED_PK_BITACORA_ATR PRIMARY KEY,
      EVENTO_ID     NUMBER        NOT NULL,
      NOMBRE        VARCHAR2(60)  NOT NULL,  -- CAUSA, DICTAMEN, RAMO, DIAS, ...
      VALOR         VARCHAR2(300),           -- el valor tal cual venia en el Excel
      VALOR_NUM     NUMBER,                  -- dias, costo
      VALOR_FECHA   DATE,                    -- inicio/fin de incapacidad
      CREATED_AT    TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
      CONSTRAINT SERV_MED_FK_BITACORA_EVENTO
        FOREIGN KEY (EVENTO_ID) REFERENCES SERV_MED_BITACORA_EVENTO (ID)
    )
  ]';
EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-955) THEN RAISE; END IF; END;
/

COMMENT ON TABLE SERV_MED_BITACORA_ATRIBUTO IS
  'Carga de Excel: atributos propios de cada familia (EAV). Agregar una familia no requiere DDL.';
COMMENT ON COLUMN SERV_MED_BITACORA_ATRIBUTO.VALOR IS
  'Valor CRUDO del Excel. Si una equivalencia de negocio cambia, se recalcula sin releer archivos.';

BEGIN EXECUTE IMMEDIATE
  'CREATE INDEX SERV_MED_IX_ATRIB_EVENTO ON SERV_MED_BITACORA_ATRIBUTO (EVENTO_ID)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-955,-1408) THEN RAISE; END IF; END;
/
-- El patron de las graficas: "cuantos por CAUSA", "cuantos por DICTAMEN"
BEGIN EXECUTE IMMEDIATE
  'CREATE INDEX SERV_MED_IX_ATRIB_NOM_VAL ON SERV_MED_BITACORA_ATRIBUTO (NOMBRE, VALOR)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-955,-1408) THEN RAISE; END IF; END;
/


-- ----------------------------------------------------------------------
-- VERIFICACION  (solo lectura)
-- ----------------------------------------------------------------------
SELECT table_name, status FROM user_tables
 WHERE table_name LIKE 'SERV_MED_BITACORA%' ORDER BY table_name;

SELECT index_name, table_name, uniqueness FROM user_indexes
 WHERE table_name LIKE 'SERV_MED_BITACORA%' ORDER BY table_name, index_name;

SELECT constraint_name, table_name, constraint_type FROM user_constraints
 WHERE table_name LIKE 'SERV_MED_BITACORA%' ORDER BY table_name, constraint_type;

-- Esperado (confirmado al aplicarlo el 29-sep-2026):
--   3 tablas VALID
--  12 indices: 8 explicitos + 3 de las llaves primarias + 1 que Oracle
--              crea solo para la columna CLOB MENSAJES (SYS_IL...$$).
--              6 salen UNIQUE: 2 UX explicitos + 3 PK + el del LOB.
--   5 constraints tipo P/R: 3 PRIMARY KEY + 2 FOREIGN KEY
--  18 constraints tipo C: son los NOT NULL (4 en ATRIBUTO, 8 en EVENTO,
--              6 en LOTE), no hay ningun CHECK de negocio.
--
-- Lo importante de revisar aqui son los dos UNIQUE explicitos: si
-- SERV_MED_UX_BITACORA_ORIGEN no aparece, la carga puede meter la misma
-- celda dos veces sin avisar.
