<?php
require_once('../../app/app.php');
$view = new app();
$others = new another();
$nss = (isset($_POST['nss']) ? $_POST['nss'] : null);
$tipoExamenInputO = (isset($_POST['tipoExamenInputO']) ? $_POST['tipoExamenInputO'] : null);
$cardIsq = (isset($_POST['cardIsq']) ? $_POST['cardIsq'] : null);
$cardIsqOBS = (isset($_POST['cardIsqOBS']) ? $_POST['cardIsqOBS'] : null);
$hiper = (isset($_POST['hiper']) ? $_POST['hiper'] : null);
$hiperOBS = (isset($_POST['hiperOBS']) ? $_POST['hiperOBS'] : null);
$hipotension = (isset($_POST['hipotension']) ? $_POST['hipotension'] : null);
$hipotensionObs = (isset($_POST['hipotensionObs']) ? $_POST['hipotensionObs'] : null);
$insuCard = (isset($_POST['insuCard']) ? $_POST['insuCard'] : null);
$insuCardObs = (isset($_POST['insuCardObs']) ? $_POST['insuCardObs'] : null);
$insuVasPer = (isset($_POST['insuVasPer']) ? $_POST['insuVasPer'] : null);
$insuVasPerObs = (isset($_POST['insuVasPerObs']) ? $_POST['insuVasPerObs'] : null);
$dm = (isset($_POST['dm']) ? $_POST['dm'] : null);
$dmOBS = (isset($_POST['dmOBS']) ? $_POST['dmOBS'] : null);
$hipertirod = (isset($_POST['hipertirod']) ? $_POST['hipertirod'] : null);
$hipertirodOBS = (isset($_POST['hipertirodOBS']) ? $_POST['hipertirodOBS'] : null);
$hipotiro = (isset($_POST['hipotiro']) ? $_POST['hipotiro'] : null);
$hipotiroObs = (isset($_POST['hipotiroObs']) ? $_POST['hipotiroObs'] : null);
$neurosis = (isset($_POST['neurosis']) ? $_POST['neurosis'] : null);
$neurosisOBS = (isset($_POST['neurosisOBS']) ? $_POST['neurosisOBS'] : null);
$psicosis = (isset($_POST['psicosis']) ? $_POST['psicosis'] : null);
$psicosisOBS = (isset($_POST['psicosisOBS']) ? $_POST['psicosisOBS'] : null);
$intentoSuicidio = (isset($_POST['intentoSuicidio']) ? $_POST['intentoSuicidio'] : null);
$intentoSuicidioObs = (isset($_POST['intentoSuicidioObs']) ? $_POST['intentoSuicidioObs'] : null);
$esquizo = (isset($_POST['esquizo']) ? $_POST['esquizo'] : null);
$esquizoObs = (isset($_POST['esquizoObs']) ? $_POST['esquizoObs'] : null);
$irc = (isset($_POST['irc']) ? $_POST['irc'] : null);
$ircOBS = (isset($_POST['ircOBS']) ? $_POST['ircOBS'] : null);
$litiasis = (isset($_POST['litiasis']) ? $_POST['litiasis'] : null);
$litiasisOBS = (isset($_POST['litiasisOBS']) ? $_POST['litiasisOBS'] : null);
$bronqui = (isset($_POST['bronqui']) ? $_POST['bronqui'] : null);
$bronquiOBS = (isset($_POST['bronquiOBS']) ? $_POST['bronquiOBS'] : null);
$tuber = (isset($_POST['tuber']) ? $_POST['tuber'] : null);
$tuberOBS = (isset($_POST['tuberOBS']) ? $_POST['tuberOBS'] : null);
$asma = (isset($_POST['asma']) ? $_POST['asma'] : null);
$asmaObs = (isset($_POST['asmaObs']) ? $_POST['asmaObs'] : null);
$insuResp = (isset($_POST['insuResp']) ? $_POST['insuResp'] : null);
$insuRespObs = (isset($_POST['insuRespObs']) ? $_POST['insuRespObs'] : null);
$avc = (isset($_POST['avc']) ? $_POST['avc'] : null);
$emilepcheck = (isset($_POST['emilepcheck']) ? $_POST['emilepcheck'] : null);
$epilepCom = (isset($_POST['epilepCom']) ? $_POST['epilepCom'] : null);
$paralisisFac = (isset($_POST['paralisisFac']) ? $_POST['paralisisFac'] : null);
$paralisisFacObs = (isset($_POST['paralisisFacObs']) ? $_POST['paralisisFacObs'] : null);
$parkinson = (isset($_POST['parkinson']) ? $_POST['parkinson'] : null);
$parkinsonObs = (isset($_POST['parkinsonObs']) ? $_POST['parkinsonObs'] : null);
$alzheimer = (isset($_POST['alzheimer']) ? $_POST['alzheimer'] : null);
$alzheimerObs = (isset($_POST['alzheimerObs']) ? $_POST['alzheimerObs'] : null);
$migraña = (isset($_POST['migraña']) ? $_POST['migraña'] : null);
$migrañaObs = (isset($_POST['migrañaObs']) ? $_POST['migrañaObs'] : null);
$transtornoCreci = (isset($_POST['transtornoCreci']) ? $_POST['transtornoCreci'] : null);
$transtornoCreciOBS = (isset($_POST['transtornoCreciOBS']) ? $_POST['transtornoCreciOBS'] : null);
$alcoholismo = (isset($_POST['alcoholismo']) ? $_POST['alcoholismo'] : null);
$alcoholismoOBS = (isset($_POST['alcoholismoOBS']) ? $_POST['alcoholismoOBS'] : null);
$tabaquismo = (isset($_POST['tabaquismo']) ? $_POST['tabaquismo'] : null);
$tabaquismoOBS = (isset($_POST['tabaquismoOBS']) ? $_POST['tabaquismoOBS'] : null);
$drogas = (isset($_POST['drogas']) ? $_POST['drogas'] : null);
$drogasObs = (isset($_POST['drogasObs']) ? $_POST['drogasObs'] : null);
$cancer = (isset($_POST['cancer']) ? $_POST['cancer'] : null);
$cancerOBS = (isset($_POST['cancerOBS']) ? $_POST['cancerOBS'] : null);
$alergias = (isset($_POST['alergias']) ? $_POST['alergias'] : null);
$alergiasOBS = (isset($_POST['alergiasOBS']) ? $_POST['alergiasOBS'] : null);
$malforma = (isset($_POST['malforma']) ? $_POST['malforma'] : null);
$malformaObs = (isset($_POST['malformaObs']) ? $_POST['malformaObs'] : null);
$otras = (isset($_POST['otras']) ? $_POST['otras'] : null);
$otrasOBS = (isset($_POST['otrasOBS']) ? $_POST['otrasOBS'] : null);
/* APNP */
$habitaInp = (isset($_POST['habitaInp']) ? $_POST['habitaInp'] : null);
$NoDorm = (isset($_POST['NoDorm']) ? $_POST['NoDorm'] : null);
$NoHabita = (isset($_POST['NoHabita']) ? $_POST['NoHabita'] : null);
$pisoInp = (isset($_POST['pisoInp']) ? $_POST['pisoInp'] : null);
$techoInp = (isset($_POST['techoInp']) ? $_POST['techoInp'] : null);
$AguaPotable = (isset($_POST['AguaPotable']) ? $_POST['AguaPotable'] : null);
$LuzInput = (isset($_POST['LuzInput']) ? $_POST['LuzInput'] : null);
$Drenajein = (isset($_POST['Drenajein']) ? $_POST['Drenajein'] : null);
$CCAIn = (isset($_POST['CCAIn']) ? $_POST['CCAIn'] : null);
$AAconIn = (isset($_POST['AAconIn']) ? $_POST['AAconIn'] : null);
$ReligionIn = (isset($_POST['ReligionIn']) ? $_POST['ReligionIn'] : null);
$HPIn = (isset($_POST['HPIn']) ? $_POST['HPIn'] : null);
$BañoIn = (isset($_POST['BañoIn']) ? $_POST['BañoIn'] : null);
$CrInp = (isset($_POST['CrInp']) ? $_POST['CrInp'] : null);
$ABInp = (isset($_POST['ABInp']) ? $_POST['ABInp'] : null);
$AlimInp = (isset($_POST['AlimInp']) ? $_POST['AlimInp'] : null);
$NCDInp = (isset($_POST['NCDInp']) ? $_POST['NCDInp'] : null);
$BalIn = (isset($_POST['BalIn']) ? $_POST['BalIn'] : null);
$SufIn = (isset($_POST['SufIn']) ? $_POST['SufIn'] : null);
$DepIn = (isset($_POST['DepIn']) ? $_POST['DepIn'] : null);
$FCInp1 = (isset($_POST['FCInp1']) ? $_POST['FCInp1'] : null);
$HOPInp = (isset($_POST['HOPInp']) ? $_POST['HOPInp'] : null);
$FCInp2 = (isset($_POST['FCInp2']) ? $_POST['FCInp2'] : null);
/* inmunizaciones */
$bcgs = (isset($_POST['bcgs']) ? $_POST['bcgs'] : null);
$sabin = (isset($_POST['sabin']) ? $_POST['sabin'] : null);
$dptin = (isset($_POST['dptin']) ? $_POST['dptin'] : null);
$hepatitis = (isset($_POST['hepatitis']) ? $_POST['hepatitis'] : null);
$srinp = (isset($_POST['srinp']) ? $_POST['srinp'] : null);
$influenza = (isset($_POST['influenza']) ? $_POST['influenza'] : null);
$tdinp = (isset($_POST['tdinp']) ? $_POST['tdinp'] : null);
/* AGO */
$MenarcaInp = (isset($_POST['MenarcaInp']) ? $_POST['MenarcaInp'] : null);
$RitmoInp = (isset($_POST['RitmoInp']) ? $_POST['RitmoInp'] : null);
$IvsaInp = (isset($_POST['IvsaInp']) ? $_POST['IvsaInp'] : null);
$FumInp = (isset($_POST['FumInp']) ? $_POST['FumInp'] : null);
$GInp = (isset($_POST['GInp']) ? $_POST['GInp'] : null);
$AInp = (isset($_POST['AInp']) ? $_POST['AInp'] : null);
$PInp = (isset($_POST['PInp']) ? $_POST['PInp'] : null);
$CInp = (isset($_POST['CInp']) ? $_POST['CInp'] : null);
$MdPFInp = (isset($_POST['MdPFInp']) ? $_POST['MdPFInp'] : null);
$PapanInp = (isset($_POST['PapanInp']) ? $_POST['PapanInp'] : null);
$InReInp = (isset($_POST['InReInp']) ? $_POST['InReInp'] : null);
$FupInp = (isset($_POST['FupInp']) ? $_POST['FupInp'] : null);
/* APP */
$ENFcONGiNP = (isset($_POST['ENFcONGiNP']) ? $_POST['ENFcONGiNP'] : null);
$genitals = (isset($_POST['genitals']) ? $_POST['genitals'] : null);
$enfPropInf = (isset($_POST['enfPropInf']) ? $_POST['enfPropInf'] : null);
$dermopatics = (isset($_POST['dermopatics']) ? $_POST['dermopatics'] : null);
$sisTAudt = (isset($_POST['sisTAudt']) ? $_POST['sisTAudt'] : null);
$respirInp = (isset($_POST['respirInp']) ? $_POST['respirInp'] : null);
$SisOlfas = (isset($_POST['SisOlfas']) ? $_POST['SisOlfas'] : null);
$TraumasInp = (isset($_POST['TraumasInp']) ? $_POST['TraumasInp'] : null);
$covidInp = (isset($_POST['covidInp']) ? $_POST['covidInp'] : null);
$fechaInm = (isset($_POST['fechaInm']) ? $_POST['fechaInm'] : null);
$ofta = (isset($_POST['ofta']) ? $_POST['ofta'] : null);
$oftaOBS = (isset($_POST['oftaOBS']) ? $_POST['oftaOBS'] : null);
$astigma = (isset($_POST['astigma']) ? $_POST['astigma'] : null);
$astigmaOBS = (isset($_POST['astigmaOBS']) ? $_POST['astigmaOBS'] : null);
$prebisia = (isset($_POST['prebisia']) ? $_POST['prebisia'] : null);
$prebisiaOBS = (isset($_POST['prebisiaOBS']) ? $_POST['prebisiaOBS'] : null);
$estra = (isset($_POST['estra']) ? $_POST['estra'] : null);
$estraOBS = (isset($_POST['estraOBS']) ? $_POST['estraOBS'] : null);
$dalto = (isset($_POST['dalto']) ? $_POST['dalto'] : null);
$daltoOBS = (isset($_POST['daltoOBS']) ? $_POST['daltoOBS'] : null);
$desp = (isset($_POST['desp']) ? $_POST['desp'] : null);
$despOBS = (isset($_POST['despOBS']) ? $_POST['despOBS'] : null);
$miope = (isset($_POST['miope']) ? $_POST['miope'] : null);
$miopeOBS = (isset($_POST['miopeOBS']) ? $_POST['miopeOBS'] : null);
$herns = (isset($_POST['herns']) ? $_POST['herns'] : null);
$hernsOBS = (isset($_POST['hernsOBS']) ? $_POST['hernsOBS'] : null);
$cirrosiss = (isset($_POST['cirrosiss']) ? $_POST['cirrosiss'] : null);
$cirrosissOBS = (isset($_POST['cirrosissOBS']) ? $_POST['cirrosissOBS'] : null);
$colis = (isset($_POST['colis']) ? $_POST['colis'] : null);
$colisOBS = (isset($_POST['colisOBS']) ? $_POST['colisOBS'] : null);
$gast = (isset($_POST['gast']) ? $_POST['gast'] : null);
$gastOBS = (isset($_POST['gastOBS']) ? $_POST['gastOBS'] : null);
$hemos = (isset($_POST['hemos']) ? $_POST['hemos'] : null);
$hemosOBS = (isset($_POST['hemosOBS']) ? $_POST['hemosOBS'] : null);
$ciru = (isset($_POST['ciru']) ? $_POST['ciru'] : null);
$ciruOBS = (isset($_POST['ciruOBS']) ? $_POST['ciruOBS'] : null);
$inconti = (isset($_POST['inconti']) ? $_POST['inconti'] : null);
$incontiOBS = (isset($_POST['incontiOBS']) ? $_POST['incontiOBS'] : null);
$insufi = (isset($_POST['insufi']) ? $_POST['insufi'] : null);
$insufiOBS = (isset($_POST['insufiOBS']) ? $_POST['insufiOBS'] : null);
$litia = (isset($_POST['litia']) ? $_POST['litia'] : null);
$litiaOBS = (isset($_POST['litiaOBS']) ? $_POST['litiaOBS'] : null);
$aneuri = (isset($_POST['aneuri']) ? $_POST['aneuri'] : null);
$aneuriOBS = (isset($_POST['aneuriOBS']) ? $_POST['aneuriOBS'] : null);
$enfdegneu = (isset($_POST['enfdegneu']) ? $_POST['enfdegneu'] : null);
$enfdegneuOBS = (isset($_POST['enfdegneuOBS']) ? $_POST['enfdegneuOBS'] : null);
$acccervascu = (isset($_POST['acccervascu']) ? $_POST['acccervascu'] : null);
$acccervascuOBS = (isset($_POST['acccervascuOBS']) ? $_POST['acccervascuOBS'] : null);
$epilep = (isset($_POST['epilep']) ? $_POST['epilep'] : null);
$epilepOBS = (isset($_POST['epilepOBS']) ? $_POST['epilepOBS'] : null);
$parfacil = (isset($_POST['parfacil']) ? $_POST['parfacil'] : null);
$parfacilOBS = (isset($_POST['parfacilOBS']) ? $_POST['parfacilOBS'] : null);
$escoliosi = (isset($_POST['escoliosi']) ? $_POST['escoliosi'] : null);
$escoliosiOBS = (isset($_POST['escoliosiOBS']) ? $_POST['escoliosiOBS'] : null);
$xifosis = (isset($_POST['xifosis']) ? $_POST['xifosis'] : null);
$xifosisOBS = (isset($_POST['xifosisOBS']) ? $_POST['xifosisOBS'] : null);
$lordosis = (isset($_POST['lordosis']) ? $_POST['lordosis'] : null);
$lordosisOBS = (isset($_POST['lordosisOBS']) ? $_POST['lordosisOBS'] : null);
$lumbagia = (isset($_POST['lumbagia']) ? $_POST['lumbagia'] : null);
$lumbagiaOBS = (isset($_POST['lumbagiaOBS']) ? $_POST['lumbagiaOBS'] : null);
$basculamiento = (isset($_POST['basculamiento']) ? $_POST['basculamiento'] : null);
$basculamientoOBS = (isset($_POST['basculamientoOBS']) ? $_POST['basculamientoOBS'] : null);
$altdiscal = (isset($_POST['altdiscal']) ? $_POST['altdiscal'] : null);
$altdiscalOBS = (isset($_POST['altdiscalOBS']) ? $_POST['altdiscalOBS'] : null);
$aneurism2 = (isset($_POST['aneurism2']) ? $_POST['aneurism2'] : null);
$aneurism2OBS = (isset($_POST['aneurism2OBS']) ? $_POST['aneurism2OBS'] : null);
$himertensss = (isset($_POST['himertensss']) ? $_POST['himertensss'] : null);
$himertensssOBS = (isset($_POST['himertensssOBS']) ? $_POST['himertensssOBS'] : null);
$hipotensi = (isset($_POST['hipotensi']) ? $_POST['hipotensi'] : null);
$hipotensiOBS = (isset($_POST['hipotensiOBS']) ? $_POST['hipotensiOBS'] : null);
$infs = (isset($_POST['infs']) ? $_POST['infs'] : null);
$infsOBS = (isset($_POST['infsOBS']) ? $_POST['infsOBS'] : null);
$insfcards = (isset($_POST['insfcards']) ? $_POST['insfcards'] : null);
$insfcardsOBS = (isset($_POST['insfcardsOBS']) ? $_POST['insfcardsOBS'] : null);
$tabaqqq = (isset($_POST['tabaqqq']) ? $_POST['tabaqqq'] : null);
$tabaqqqOBS = (isset($_POST['tabaqqqOBS']) ? $_POST['tabaqqqOBS'] : null);
$alcohool = (isset($_POST['alcohool']) ? $_POST['alcohool'] : null);
$alcohoolOBS = (isset($_POST['alcohoolOBS']) ? $_POST['alcohoolOBS'] : null);
$grugss = (isset($_POST['grugss']) ? $_POST['grugss'] : null);
$grugssOBS = (isset($_POST['grugssOBS']) ? $_POST['grugssOBS'] : null);
$altcargs = (isset($_POST['altcargs']) ? $_POST['altcargs'] : null);
$altcargsOBS = (isset($_POST['altcargsOBS']) ? $_POST['altcargsOBS'] : null);
$perfoss = (isset($_POST['perfoss']) ? $_POST['perfoss'] : null);
$perfossOBS = (isset($_POST['perfossOBS']) ? $_POST['perfossOBS'] : null);
$tattoo = (isset($_POST['tattoo']) ? $_POST['tattoo'] : null);
$tattooOBS = (isset($_POST['tattooOBS']) ? $_POST['tattooOBS'] : null);
$alergiasInOBS = (isset($_POST['alergiasInOBS']) ? $_POST['alergiasInOBS'] : null);
$alergiasInp = (isset($_POST['alergiasInp']) ? $_POST['alergiasInp'] : null);
$diabolica = (isset($_POST['diabolica']) ? $_POST['diabolica'] : null);
$diabolicaOBS = (isset($_POST['diabolicaOBS']) ? $_POST['diabolicaOBS'] : null);
$hipertirones = (isset($_POST['hipertirones']) ? $_POST['hipertirones'] : null);
$hipertironesOBS = (isset($_POST['hipertironesOBS']) ? $_POST['hipertironesOBS'] : null);
$superhipo = (isset($_POST['superhipo']) ? $_POST['superhipo'] : null);
$superhipoOBS = (isset($_POST['superhipoOBS']) ? $_POST['superhipoOBS'] : null);
/* PA */
$padecimientoActual = (isset($_POST['padecimientoActual']) ? $_POST['padecimientoActual'] : null);
/* InterAS */
$interAS = (isset($_POST['interAS']) ? $_POST['interAS'] : null);
/* EXFIS */
$PESOEXFISINP = (isset($_POST['PESOEXFISINP']) ? $_POST['PESOEXFISINP'] : null);
$TALLAEXFISINP = (isset($_POST['TALLAEXFISINP']) ? $_POST['TALLAEXFISINP'] : null);
$IMCEXFISINP = (isset($_POST['IMCEXFISINP']) ? $_POST['IMCEXFISINP'] : null);
$FCEXFISINP = (isset($_POST['FCEXFISINP']) ? $_POST['FCEXFISINP'] : null);
$FREXFISINP = (isset($_POST['FREXFISINP']) ? $_POST['FREXFISINP'] : null);
$TAEXFISINP = (isset($_POST['TAEXFISINP']) ? $_POST['TAEXFISINP'] : null);
$TEMPEXFISINP = (isset($_POST['TEMPEXFISINP']) ? $_POST['TEMPEXFISINP'] : null);
$STPO2INP = (isset($_POST['STPO2INP']) ? $_POST['STPO2INP'] : null);
$ECTOMORFICOEXFISINP = (isset($_POST['ECTOMORFICOEXFISINP']) ? $_POST['ECTOMORFICOEXFISINP'] : null);
$MESOMORFOEXFISINP = (isset($_POST['MESOMORFOEXFISINP']) ? $_POST['MESOMORFOEXFISINP'] : null);
$ENDOMORFICAEXFISINP = (isset($_POST['ENDOMORFICAEXFISINP']) ? $_POST['ENDOMORFICAEXFISINP'] : null);
$SATISFACCIONEXFISINP = (isset($_POST['SATISFACCIONEXFISINP']) ? $_POST['SATISFACCIONEXFISINP'] : null);
$COMP_TRABAJOEXFISINP = (isset($_POST['COMP_TRABAJOEXFISINP']) ? $_POST['COMP_TRABAJOEXFISINP'] : null);
$COMP_ORGANIZACIONEXFISINP = (isset($_POST['COMP_ORGANIZACIONEXFISINP']) ? $_POST['COMP_ORGANIZACIONEXFISINP'] : null);
$TIEMPOEXFISINP = (isset($_POST['TIEMPOEXFISINP']) ? $_POST['TIEMPOEXFISINP'] : null);
$ESPACIOEXFISINP = (isset($_POST['ESPACIOEXFISINP']) ? $_POST['ESPACIOEXFISINP'] : null);
$PERSONAEXFISINP = (isset($_POST['PERSONAEXFISINP']) ? $_POST['PERSONAEXFISINP'] : null);
$SERENIDADEXFISINP = (isset($_POST['SERENIDADEXFISINP']) ? $_POST['SERENIDADEXFISINP'] : null);
$INTERESEXFISINP = (isset($_POST['INTERESEXFISINP']) ? $_POST['INTERESEXFISINP'] : null);
$ANTAGONICOEXFISINP = (isset($_POST['ANTAGONICOEXFISINP']) ? $_POST['ANTAGONICOEXFISINP'] : null);
$ENTUSIASTAEXFISINP = (isset($_POST['ENTUSIASTAEXFISINP']) ? $_POST['ENTUSIASTAEXFISINP'] : null);
$ENOJOEXFISINP = (isset($_POST['ENOJOEXFISINP']) ? $_POST['ENOJOEXFISINP'] : null);
$HIPOCRITAEXFISINP = (isset($_POST['HIPOCRITAEXFISINP']) ? $_POST['HIPOCRITAEXFISINP'] : null);
$ICTERICAEXFISINP = (isset($_POST['ICTERICAEXFISINP']) ? $_POST['ICTERICAEXFISINP'] : null);
$ANEMICAEXFISINP = (isset($_POST['ANEMICAEXFISINP']) ? $_POST['ANEMICAEXFISINP'] : null);
$TIROIDEAEXFISINP = (isset($_POST['TIROIDEAEXFISINP']) ? $_POST['TIROIDEAEXFISINP'] : null);
$NOLMAL_FASCIESEXFISINP = (isset($_POST['NOLMAL_FASCIESEXFISINP']) ? $_POST['NOLMAL_FASCIESEXFISINP'] : null);
$PARKINSONEXFISINP = (isset($_POST['PARKINSONEXFISINP']) ? $_POST['PARKINSONEXFISINP'] : null);
$HEMIPLEJICOEXFISINP = (isset($_POST['HEMIPLEJICOEXFISINP']) ? $_POST['HEMIPLEJICOEXFISINP'] : null);
$ATAXICAEXFISINP = (isset($_POST['ATAXICAEXFISINP']) ? $_POST['ATAXICAEXFISINP'] : null);
$HEMIPARESIAEXFISINP = (isset($_POST['HEMIPARESIAEXFISINP']) ? $_POST['HEMIPARESIAEXFISINP'] : null);
$NORMAL_MARCHAEXFISINP = (isset($_POST['NORMAL_MARCHAEXFISINP']) ? $_POST['NORMAL_MARCHAEXFISINP'] : null);
$LENGUAJEEXFISINP = (isset($_POST['LENGUAJEEXFISINP']) ? $_POST['LENGUAJEEXFISINP'] : null);
$CONVER_FLUIDAEXFISINP = (isset($_POST['CONVER_FLUIDAEXFISINP']) ? $_POST['CONVER_FLUIDAEXFISINP'] : null);
$COHERENCIA_PALABLASEXFISINP = (isset($_POST['COHERENCIA_PALABLASEXFISINP']) ? $_POST['COHERENCIA_PALABLASEXFISINP'] : null);
$VOZCLARAYFUERTEINP = (isset($_POST['VOZCLARAYFUERTEINP']) ? $_POST['VOZCLARAYFUERTEINP'] : null);
$OJOSEXFISINP = (isset($_POST['OJOSEXFISINP']) ? $_POST['OJOSEXFISINP'] : null);
$PUPILASEXFISINP = (isset($_POST['PUPILASEXFISINP']) ? $_POST['PUPILASEXFISINP'] : null);
$CONJUNTIVASEXFISINP = (isset($_POST['CONJUNTIVASEXFISINP']) ? $_POST['CONJUNTIVASEXFISINP'] : null);
$REFLEJOSEXFISINP = (isset($_POST['REFLEJOSEXFISINP']) ? $_POST['REFLEJOSEXFISINP'] : null);
$FONDO_OJOEXFISINP = (isset($_POST['FONDO_OJOEXFISINP']) ? $_POST['FONDO_OJOEXFISINP'] : null);
$ODEXFISINP = (isset($_POST['ODEXFISINP']) ? $_POST['ODEXFISINP'] : null);
$OIZEXFISINP = (isset($_POST['OIZEXFISINP']) ? $_POST['OIZEXFISINP'] : null);
$LENTEOJODERECHOEXP = (isset($_POST['LENTEOJODERECHOEXP']) ? $_POST['LENTEOJODERECHOEXP'] : null);
$LENTEOJOIZQUIERDOEXP = (isset($_POST['LENTEOJOIZQUIERDOEXP']) ? $_POST['LENTEOJOIZQUIERDOEXP'] : null);
$ROMBERGEXFIS = (isset($_POST['ROMBERGEXFIS']) ? $_POST['ROMBERGEXFIS'] : null);
$COLORESEXFISINP = (isset($_POST['COLORESEXFISINP']) ? $_POST['COLORESEXFISINP'] : null);
$CAVIDAD_NASALEXFISINP = (isset($_POST['CAVIDAD_NASALEXFISINP']) ? $_POST['CAVIDAD_NASALEXFISINP'] : null);
$MUCOSAEXFISINP = (isset($_POST['MUCOSAEXFISINP']) ? $_POST['MUCOSAEXFISINP'] : null);
$TABIQUE_NASALEXFISINP = (isset($_POST['TABIQUE_NASALEXFISINP']) ? $_POST['TABIQUE_NASALEXFISINP'] : null);
$OLFATOEXFISINP = (isset($_POST['OLFATOEXFISINP']) ? $_POST['OLFATOEXFISINP'] : null);
$CERVICALEXFISINP = (isset($_POST['CERVICALEXFISINP']) ? $_POST['CERVICALEXFISINP'] : null);
$DORSALEXFISINP = (isset($_POST['DORSALEXFISINP']) ? $_POST['DORSALEXFISINP'] : null);
$LUMBAREXFISINP = (isset($_POST['LUMBAREXFISINP']) ? $_POST['LUMBAREXFISINP'] : null);
$LESIONESEXFISINP = (isset($_POST['LESIONESEXFISINP']) ? $_POST['LESIONESEXFISINP'] : null);
$ENCIASEXFISINP = (isset($_POST['ENCIASEXFISINP']) ? $_POST['ENCIASEXFISINP'] : null);
$OROIFARINGEEXFISINP = (isset($_POST['OROIFARINGEEXFISINP']) ? $_POST['OROIFARINGEEXFISINP'] : null);
$CAEEXFISINP = (isset($_POST['CAEEXFISINP']) ? $_POST['CAEEXFISINP'] : null);
$MEM_TIMEXCAEEXFISINP = (isset($_POST['MEM_TIMEXCAEEXFISINP']) ? $_POST['MEM_TIMEXCAEEXFISINP'] : null);
$AGUD_AUDITEXCAEEXFISINP = (isset($_POST['AGUD_AUDITEXCAEEXFISINP']) ? $_POST['AGUD_AUDITEXCAEEXFISINP'] : null);
$ODEXCAEEXFISINP = (isset($_POST['ODEXCAEEXFISINP']) ? $_POST['ODEXCAEEXFISINP'] : null);
$OIEXCAEEXFISINP = (isset($_POST['OIEXCAEEXFISINP']) ? $_POST['OIEXCAEEXFISINP'] : null);
$RUIDOS_CARDIACOSEXFISINP = (isset($_POST['RUIDOS_CARDIACOSEXFISINP']) ? $_POST['RUIDOS_CARDIACOSEXFISINP'] : null);
$REG_PRECORDIALEXFISINP = (isset($_POST['REG_PRECORDIALEXFISINP']) ? $_POST['REG_PRECORDIALEXFISINP'] : null);
$CAMPOS_PULMEXFISINP = (isset($_POST['CAMPOS_PULMEXFISINP']) ? $_POST['CAMPOS_PULMEXFISINP'] : null);
$DEFORMACIONESEXFISINP = (isset($_POST['DEFORMACIONESEXFISINP']) ? $_POST['DEFORMACIONESEXFISINP'] : null);
$DOLOREXFISINP = (isset($_POST['DOLOREXFISINP']) ? $_POST['DOLOREXFISINP'] : null);
$MOVIMIENTOSEXFISINP = (isset($_POST['MOVIMIENTOSEXFISINP']) ? $_POST['MOVIMIENTOSEXFISINP'] : null);
$MARCHAEXFISINP = (isset($_POST['MARCHAEXFISINP']) ? $_POST['MARCHAEXFISINP'] : null);
$LASSEGUEEXFISINP = (isset($_POST['LASSEGUEEXFISINP']) ? $_POST['LASSEGUEEXFISINP'] : null);
$PUNTA_TALONEXFISINP = (isset($_POST['PUNTA_TALONEXFISINP']) ? $_POST['PUNTA_TALONEXFISINP'] : null);
$FORMAEXFISINP = (isset($_POST['FORMAEXFISINP']) ? $_POST['FORMAEXFISINP'] : null);
$VISCEROMEGALIASEXFISINP = (isset($_POST['VISCEROMEGALIASEXFISINP']) ? $_POST['VISCEROMEGALIASEXFISINP'] : null);
$HERNIASEXFISINP = (isset($_POST['HERNIASEXFISINP']) ? $_POST['HERNIASEXFISINP'] : null);
$DOLOREXFISINP = (isset($_POST['DOLOREXFISINP']) ? $_POST['DOLOREXFISINP'] : null);
$PERISTALSISEXFISINP = (isset($_POST['PERISTALSISEXFISINP']) ? $_POST['PERISTALSISEXFISINP'] : null);
$MASCULINOEXFISINP = (isset($_POST['MASCULINOEXFISINP']) ? $_POST['MASCULINOEXFISINP'] : null);
$FEMENINOEXFISINP = (isset($_POST['FEMENINOEXFISINP']) ? $_POST['FEMENINOEXFISINP'] : null);
$PUNTOS_URETRALESEXFISINP = (isset($_POST['PUNTOS_URETRALESEXFISINP']) ? $_POST['PUNTOS_URETRALESEXFISINP'] : null);
$FOSAS_RENALESEXFISINP = (isset($_POST['FOSAS_RENALESEXFISINP']) ? $_POST['FOSAS_RENALESEXFISINP'] : null);
$SUPERIOREXFISINP = (isset($_POST['SUPERIOREXFISINP']) ? $_POST['SUPERIOREXFISINP'] : null);
$INFERIOREXFISINP = (isset($_POST['INFERIOREXFISINP']) ? $_POST['INFERIOREXFISINP'] : null);
$IVPEXFISINP = (isset($_POST['IVPEXFISINP']) ? $_POST['IVPEXFISINP'] : null);
$EDEMAEXFISINP = (isset($_POST['EDEMAEXFISINP']) ? $_POST['EDEMAEXFISINP'] : null);
$LUNARESEXFISINP = (isset($_POST['LUNARESEXFISINP']) ? $_POST['LUNARESEXFISINP'] : null);
$PIGMENTACIONEXFISINP = (isset($_POST['PIGMENTACIONEXFISINP']) ? $_POST['PIGMENTACIONEXFISINP'] : null);
$CICATRICES_QUIRUREXFISINP = (isset($_POST['CICATRICES_QUIRUREXFISINP']) ? $_POST['CICATRICES_QUIRUREXFISINP'] : null);

$DIENTE_11 = (isset($_POST['DIENTE_11']) ? $_POST['DIENTE_11'] : null);
$DIENTE_12 = (isset($_POST['DIENTE_12']) ? $_POST['DIENTE_12'] : null);
$DIENTE_13 = (isset($_POST['DIENTE_13']) ? $_POST['DIENTE_13'] : null);
$DIENTE_14 = (isset($_POST['DIENTE_14']) ? $_POST['DIENTE_14'] : null);
$DIENTE_15 = (isset($_POST['DIENTE_15']) ? $_POST['DIENTE_15'] : null);
$DIENTE_16 = (isset($_POST['DIENTE_16']) ? $_POST['DIENTE_16'] : null);
$DIENTE_17 = (isset($_POST['DIENTE_17']) ? $_POST['DIENTE_17'] : null);
$DIENTE_18 = (isset($_POST['DIENTE_18']) ? $_POST['DIENTE_18'] : null);
$DIENTE_41 = (isset($_POST['DIENTE_41']) ? $_POST['DIENTE_41'] : null);
$DIENTE_42 = (isset($_POST['DIENTE_42']) ? $_POST['DIENTE_42'] : null);
$DIENTE_43 = (isset($_POST['DIENTE_43']) ? $_POST['DIENTE_43'] : null);
$DIENTE_44 = (isset($_POST['DIENTE_44']) ? $_POST['DIENTE_44'] : null);
$DIENTE_45 = (isset($_POST['DIENTE_45']) ? $_POST['DIENTE_45'] : null);
$DIENTE_46 = (isset($_POST['DIENTE_46']) ? $_POST['DIENTE_46'] : null);
$DIENTE_47 = (isset($_POST['DIENTE_47']) ? $_POST['DIENTE_47'] : null);
$DIENTE_48 = (isset($_POST['DIENTE_48']) ? $_POST['DIENTE_48'] : null);
$DIENTE_2 = (isset($_POST['DIENTE_2']) ? $_POST['DIENTE_2'] : null);
$DIENTE_22 = (isset($_POST['DIENTE_22']) ? $_POST['DIENTE_22'] : null);
$DIENTE_23 = (isset($_POST['DIENTE_23']) ? $_POST['DIENTE_23'] : null);
$DIENTE_24 = (isset($_POST['DIENTE_24']) ? $_POST['DIENTE_24'] : null);
$DIENTE_25 = (isset($_POST['DIENTE_25']) ? $_POST['DIENTE_25'] : null);
$DIENTE_26 = (isset($_POST['DIENTE_26']) ? $_POST['DIENTE_26'] : null);
$DIENTE_27 = (isset($_POST['DIENTE_27']) ? $_POST['DIENTE_27'] : null);
$DIENTE_28 = (isset($_POST['DIENTE_28']) ? $_POST['DIENTE_28'] : null);
$DIENTE_31 = (isset($_POST['DIENTE_31']) ? $_POST['DIENTE_31'] : null);
$DIENTE_32 = (isset($_POST['DIENTE_32']) ? $_POST['DIENTE_32'] : null);
$DIENTE_33 = (isset($_POST['DIENTE_33']) ? $_POST['DIENTE_33'] : null);
$DIENTE_34 = (isset($_POST['DIENTE_34']) ? $_POST['DIENTE_34'] : null);
$DIENTE_35 = (isset($_POST['DIENTE_35']) ? $_POST['DIENTE_35'] : null);
$DIENTE_36 = (isset($_POST['DIENTE_36']) ? $_POST['DIENTE_36'] : null);
$DIENTE_37 = (isset($_POST['DIENTE_37']) ? $_POST['DIENTE_37'] : null);
$DIENTE_38 = (isset($_POST['DIENTE_38']) ? $_POST['DIENTE_38'] : null);


$RESULTADOSESYRES = (isset($_POST['RESULTADOSESYRES']) ? $_POST['RESULTADOSESYRES'] : null);
$OBSERVACIONESDIAGINP = (isset($_POST['OBSERVACIONESDIAGINP']) ? $_POST['OBSERVACIONESDIAGINP'] : null);
$OBSERVACIONESPLATERINP = (isset($_POST['OBSERVACIONESPLATERINP']) ? $_POST['OBSERVACIONESPLATERINP'] : null);

$DEFORMACIONES_OBSINP = (isset($_POST['DEFORMACIONES_OBSINP']) ? $_POST['DEFORMACIONES_OBSINP'] : null);
$TIROIDES_OBSINP = (isset($_POST['TIROIDES_OBSINP']) ? $_POST['TIROIDES_OBSINP'] : null);
$TRAQUEA_OBSINP = (isset($_POST['TRAQUEA_OBSINP']) ? $_POST['TRAQUEA_OBSINP'] : null);

$resExamIn = (isset($_POST['resExamIn']) ? $_POST['resExamIn'] : null);
$FIRMA = (isset($_POST['FIRMA']) ? $_POST['FIRMA'] : null);

$edad_inicio_laborar = (isset($_POST['edad_inicio_laborar']) ? $_POST['edad_inicio_laborar'] : null);
$cantidad_trabajos = (isset($_POST['cantidad_trabajos']) ? $_POST['cantidad_trabajos'] : null);
$pension = (isset($_POST['pension']) ? $_POST['pension'] : null);

$nombre1 = (isset($_POST['nombre1']) ? $_POST['nombre1'] : null);
$giro1 = (isset($_POST['giro1']) ? $_POST['giro1'] : null);
$puesto1 = (isset($_POST['puesto1']) ? $_POST['puesto1'] : null);
$turno1 = (isset($_POST['turno1']) ? $_POST['turno1'] : null);
$antiguedad1 = (isset($_POST['antiguedad1']) ? $_POST['antiguedad1'] : null);
$salida1 = (isset($_POST['salida1']) ? $_POST['salida1'] : null);
$descripcion1 = (isset($_POST['descripcion1']) ? $_POST['descripcion1'] : null);
$riesgos1 = (isset($_POST['riesgos1']) ? $_POST['riesgos1'] : null);
$epp1 = (isset($_POST['epp1']) ? $_POST['epp1'] : null);
$observaciones1 = (isset($_POST['observaciones1']) ? $_POST['observaciones1'] : null);
$nombre2 = (isset($_POST['nombre2']) ? $_POST['nombre2'] : null);
$giro2 = (isset($_POST['giro2']) ? $_POST['giro2'] : null);
$puesto2 = (isset($_POST['puesto2']) ? $_POST['puesto2'] : null);
$turno2 = (isset($_POST['turno2']) ? $_POST['turno2'] : null);
$antiguedad2 = (isset($_POST['antiguedad2']) ? $_POST['antiguedad2'] : null);
$salida2 = (isset($_POST['salida2']) ? $_POST['salida2'] : null);
$descripcion2 = (isset($_POST['descripcion2']) ? $_POST['descripcion2'] : null);
$riesgos2 = (isset($_POST['riesgos2']) ? $_POST['riesgos2'] : null);
$epp2 = (isset($_POST['epp2']) ? $_POST['epp2'] : null);
$observaciones2 = (isset($_POST['observaciones2']) ? $_POST['observaciones2'] : null);
$nombre3 = (isset($_POST['nombre3']) ? $_POST['nombre3'] : null);
$giro3 = (isset($_POST['giro3']) ? $_POST['giro3'] : null);
$puesto3 = (isset($_POST['puesto3']) ? $_POST['puesto3'] : null);
$turno3 = (isset($_POST['turno3']) ? $_POST['turno3'] : null);
$antiguedad3 = (isset($_POST['antiguedad3']) ? $_POST['antiguedad3'] : null);
$salida3 = (isset($_POST['salida3']) ? $_POST['salida3'] : null);
$descripcion3 = (isset($_POST['descripcion3']) ? $_POST['descripcion3'] : null);
$riesgos3 = (isset($_POST['riesgos3']) ? $_POST['riesgos3'] : null);
$epp3 = (isset($_POST['epp3']) ? $_POST['epp3'] : null);
$observaciones3 = (isset($_POST['observaciones3']) ? $_POST['observaciones3'] : null);
$nombre4 = (isset($_POST['nombre4']) ? $_POST['nombre4'] : null);
$giro4 = (isset($_POST['giro4']) ? $_POST['giro4'] : null);
$puesto4 = (isset($_POST['puesto4']) ? $_POST['puesto4'] : null);
$turno4 = (isset($_POST['turno4']) ? $_POST['turno4'] : null);
$antiguedad4 = (isset($_POST['antiguedad4']) ? $_POST['antiguedad4'] : null);
$salida4 = (isset($_POST['salida4']) ? $_POST['salida4'] : null);
$descripcion4 = (isset($_POST['descripcion4']) ? $_POST['descripcion4'] : null);
$riesgos4 = (isset($_POST['riesgos4']) ? $_POST['riesgos4'] : null);
$epp4 = (isset($_POST['epp4']) ? $_POST['epp4'] : null);
$observaciones4 = (isset($_POST['observaciones4']) ? $_POST['observaciones4'] : null);
$OBSGENERALINPEX = (isset($_POST['OBSGENERALINPEX']) ? $_POST['OBSGENERALINPEX'] : null);

$ODCAEINPEXP = (isset($_POST['ODCAEINPEXP']) ? $_POST['ODCAEINPEXP'] : null);
$ODMEMTIMINPEXP = (isset($_POST['ODMEMTIMINPEXP']) ? $_POST['ODMEMTIMINPEXP'] : null);
$ODAGAUDIINPEXP = (isset($_POST['ODAGAUDIINPEXP']) ? $_POST['ODAGAUDIINPEXP'] : null);
$OICAEINPEXP = (isset($_POST['OICAEINPEXP']) ? $_POST['OICAEINPEXP'] : null);
$OIMEMTIMINPEXP = (isset($_POST['OIMEMTIMINPEXP']) ? $_POST['OIMEMTIMINPEXP'] : null);
$OIAGAUDIINPEXP = (isset($_POST['OIAGAUDIINPEXP']) ? $_POST['OIAGAUDIINPEXP'] : null);

$view->sendHeredoFamDats($nss, 'CAMBIO', $data = [
    "cardIsq" => $cardIsq,
    "cardIsqOBS" => $cardIsqOBS,
    "hiper" => $hiper,
    "hiperOBS" => $hiperOBS,
    "hipotension" => $hipotension,
    "hipotensionObs" => $hipotensionObs,
    "insuCard" => $insuCard,
    "insuCardObs" => $insuCardObs,
    "insuVasPer" => $insuVasPer,
    "insuVasPerObs" => $insuVasPerObs,
    "dm" => $dm,
    "dmOBS" => $dmOBS,
    "hipertirod" => $hipertirod,
    "hipertirodOBS" => $hipertirodOBS,
    "hipotiro" => $hipotiro,
    "hipotiroObs" => $hipotiroObs,
    "neurosis" => $neurosis,
    "neurosisOBS" => $neurosisOBS,
    "psicosis" => $psicosis,
    "psicosisOBS" => $psicosisOBS,
    "intentoSuicidio" => $intentoSuicidio,
    "intentoSuicidioObs" => $intentoSuicidioObs,
    "esquizo" => $esquizo,
    "esquizoObs" => $esquizoObs,
    "irc" => $irc,
    "ircOBS" => $ircOBS,
    "litiasis" => $litiasis,
    "litiasisOBS" => $litiasisOBS,
    "bronqui" => $bronqui,
    "bronquiOBS" => $bronquiOBS,
    "tuber" => $tuber,
    "tuberOBS" => $tuberOBS,
    "asma" => $asma,
    "asmaObs" => $asmaObs,
    "insuResp" => $insuResp,
    "insuRespObs" => $insuRespObs,
    "avc" => $avc,
    "emilepcheck" => $emilepcheck,
    "epilepCom" => $epilepCom,
    "paralisisFac" => $paralisisFac,
    "paralisisFacObs" => $paralisisFacObs,
    "parkinson" => $parkinson,
    "parkinsonObs" => $parkinsonObs,
    "alzheimer" => $alzheimer,
    "alzheimerObs" => $alzheimerObs,
    "migraña" => $migraña,
    "migrañaObs" => $migrañaObs,
    "transtornoCreci" => $transtornoCreci,
    "transtornoCreciOBS" => $transtornoCreciOBS,
    "alcoholismo" => $alcoholismo,
    "alcoholismoOBS" => $alcoholismoOBS,
    "tabaquismo" => $tabaquismo,
    "tabaquismoOBS" => $tabaquismoOBS,
    "drogas" => $drogas,
    "drogasObs" => $drogasObs,
    "cancer" => $cancer,
    "cancerOBS" => $cancerOBS,
    "alergias" => $alergias,
    "alergiasOBS" => $alergiasOBS,
    "malforma" => $malforma,
    "malformaObs" => $malformaObs,
    "otras" => $otras,
    "otrasOBS" => $otrasOBS,
    "habitaInp" => $habitaInp,
    "NoDorm" => $NoDorm,
    "NoHabita" => $NoHabita,
    "pisoInp" => $pisoInp,
    "techoInp" => $techoInp,
    "AguaPotable" => $AguaPotable,
    "LuzInput" => $LuzInput,
    "Drenajein" => $Drenajein,
    "CCAIn" => $CCAIn,
    "AAconIn" => $AAconIn,
    "ReligionIn" => $ReligionIn,
    "HPIn" => $HPIn,
    "BañoIn" => $BañoIn,
    "CrInp" => $CrInp,
    "ABInp" => $ABInp,
    "AlimInp" => $AlimInp,
    "NCDInp" => $NCDInp,
    "BalIn" => $BalIn,
    "SufIn" => $SufIn,
    "DepIn" => $DepIn,
    "FCInp1" => $FCInp1,
    "HOPInp" => $HOPInp,
    "FCInp2" => $FCInp2,
    "bcgs" => $bcgs,
    "sabin" => $sabin,
    "dptin" => $dptin,
    "hepatitis" => $hepatitis,
    "srinp" => $srinp,
    "influenza" => $influenza,
    "tdinp" => $tdinp,
    "MenarcaInp" => $MenarcaInp,
    "RitmoInp" => $RitmoInp,
    "IvsaInp" => $IvsaInp,
    "FumInp" => $FumInp,
    "GInp" => $GInp,
    "AInp" => $AInp,
    "PInp" => $PInp,
    "CInp" => $CInp,
    "MdPFInp" => $MdPFInp,
    "PapanInp" => $PapanInp,
    "InReInp" => $InReInp,
    "FupInp" => $FupInp,
    "ENFcONGiNP" => $ENFcONGiNP,
    "genitals" => $genitals,
    "enfPropInf" => $enfPropInf,
    "dermopatics" => $dermopatics,
    "sisTAudt" => $sisTAudt,
    "respirInp" => $respirInp,
    "SisOlfas" => $SisOlfas,
    "TraumasInp" => $TraumasInp,
    "covidInp" => $covidInp,
    "fechaInm" => $fechaInm,
    "ofta" => $ofta,
    "oftaOBS" => $oftaOBS,
    "astigma" => $astigma,
    "astigmaOBS" => $astigmaOBS,
    "prebisia" => $prebisia,
    "prebisiaOBS" => $prebisiaOBS,
    "estra" => $estra,
    "estraOBS" => $estraOBS,
    "dalto" => $dalto,
    "daltoOBS" => $daltoOBS,
    "desp" => $desp,
    "despOBS" => $despOBS,
    "miope" => $miope,
    "miopeOBS" => $miopeOBS,
    "herns" => $herns,
    "hernsOBS" => $hernsOBS,
    "cirrosiss" => $cirrosiss,
    "cirrosissOBS" => $cirrosissOBS,
    "colis" => $colis,
    "colisOBS" => $colisOBS,
    "gast" => $gast,
    "gastOBS" => $gastOBS,
    "hemos" => $hemos,
    "hemosOBS" => $hemosOBS,
    "ciru" => $ciru,
    "ciruOBS" => $ciruOBS,
    "inconti" => $inconti,
    "incontiOBS" => $incontiOBS,
    "insufi" => $insufi,
    "insufiOBS" => $insufiOBS,
    "litia" => $litia,
    "litiaOBS" => $litiaOBS,
    "aneuri" => $aneuri,
    "aneuriOBS" => $aneuriOBS,
    "enfdegneu" => $enfdegneu,
    "enfdegneuOBS" => $enfdegneuOBS,
    "acccervascu" => $acccervascu,
    "acccervascuOBS" => $acccervascuOBS,
    "epilep" => $epilep,
    "epilepOBS" => $epilepOBS,
    "parfacil" => $parfacil,
    "parfacilOBS" => $parfacilOBS,
    "escoliosi" => $escoliosi,
    "escoliosiOBS" => $escoliosiOBS,
    "xifosis" => $xifosis,
    "xifosisOBS" => $xifosisOBS,
    "lordosis" => $lordosis,
    "lordosisOBS" => $lordosisOBS,
    "lumbagia" => $lumbagia,
    "lumbagiaOBS" => $lumbagiaOBS,
    "basculamiento" => $basculamiento,
    "basculamientoOBS" => $basculamientoOBS,
    "altdiscal" => $altdiscal,
    "altdiscalOBS" => $altdiscalOBS,
    "aneurism2" => $aneurism2,
    "aneurism2OBS" => $aneurism2OBS,
    "himertensss" => $himertensss,
    "himertensssOBS" => $himertensssOBS,
    "hipotensi" => $hipotensi,
    "hipotensiOBS" => $hipotensiOBS,
    "infs" => $infs,
    "infsOBS" => $infsOBS,
    "insfcards" => $insfcards,
    "insfcardsOBS" => $insfcardsOBS,
    "tabaqqq" => $tabaqqq,
    "tabaqqqOBS" => $tabaqqqOBS,
    "alcohool" => $alcohool,
    "alcohoolOBS" => $alcohoolOBS,
    "grugss" => $grugss,
    "grugssOBS" => $grugssOBS,
    "altcargs" => $altcargs,
    "altcargsOBS" => $altcargsOBS,
    "perfoss" => $perfoss,
    "perfossOBS" => $perfossOBS,
    "tattoo" => $tattoo,
    "tattooOBS" => $tattooOBS,
    "alergiasInOBS" => $alergiasInOBS,
    "alergiasInp" => $alergiasInp,
    "diabolica" => $diabolica,
    "diabolicaOBS" => $diabolicaOBS,
    "hipertirones" => $hipertirones,
    "hipertironesOBS" => $hipertironesOBS,
    "superhipo" => $superhipo,
    "superhipoOBS" => $superhipoOBS,
    "padecimientoActual" => $padecimientoActual,
    "interAS" => $interAS,
    "PESOEXFISINP" => $PESOEXFISINP,
    "TALLAEXFISINP" => $TALLAEXFISINP,
    "IMCEXFISINP" => $IMCEXFISINP,
    "FCEXFISINP" => $FCEXFISINP,
    "FREXFISINP" => $FREXFISINP,
    "TAEXFISINP" => $TAEXFISINP,
    "TEMPEXFISINP" => $TEMPEXFISINP,
    "ECTOMORFICOEXFISINP" => $ECTOMORFICOEXFISINP,
    "MESOMORFOEXFISINP" => $MESOMORFOEXFISINP,
    "ENDOMORFICAEXFISINP" => $ENDOMORFICAEXFISINP,
    "SATISFACCIONEXFISINP" => $SATISFACCIONEXFISINP,
    "COMP_TRABAJOEXFISINP" => $COMP_TRABAJOEXFISINP,
    "COMP_ORGANIZACIONEXFISINP" => $COMP_ORGANIZACIONEXFISINP,
    "TIEMPOEXFISINP" => $TIEMPOEXFISINP,
    "ESPACIOEXFISINP" => $ESPACIOEXFISINP,
    "PERSONAEXFISINP" => $PERSONAEXFISINP,
    "SERENIDADEXFISINP" => $SERENIDADEXFISINP,
    "INTERESEXFISINP" => $INTERESEXFISINP,
    "ANTAGONICOEXFISINP" => $ANTAGONICOEXFISINP,
    "ENTUSIASTAEXFISINP" => $ENTUSIASTAEXFISINP,
    "ENOJOEXFISINP" => $ENOJOEXFISINP,
    "HIPOCRITAEXFISINP" => $HIPOCRITAEXFISINP,
    "ICTERICAEXFISINP" => $ICTERICAEXFISINP,
    "ANEMICAEXFISINP" => $ANEMICAEXFISINP,
    "TIROIDEAEXFISINP" => $TIROIDEAEXFISINP,
    "NOLMAL_FASCIESEXFISINP" => $NOLMAL_FASCIESEXFISINP,
    "PARKINSONEXFISINP" => $PARKINSONEXFISINP,
    "HEMIPLEJICOEXFISINP" => $HEMIPLEJICOEXFISINP,
    "ATAXICAEXFISINP" => $ATAXICAEXFISINP,
    "HEMIPARESIAEXFISINP" => $HEMIPARESIAEXFISINP,
    "NORMAL_MARCHAEXFISINP" => $NORMAL_MARCHAEXFISINP,
    "LENGUAJEEXFISINP" => $LENGUAJEEXFISINP,
    "CONVER_FLUIDAEXFISINP" => $CONVER_FLUIDAEXFISINP,
    "COHERENCIA_PALABLASEXFISINP" => $COHERENCIA_PALABLASEXFISINP,
    "OJOSEXFISINP" => $OJOSEXFISINP,
    "PUPILASEXFISINP" => $PUPILASEXFISINP,
    "CONJUNTIVASEXFISINP" => $CONJUNTIVASEXFISINP,
    "REFLEJOSEXFISINP" => $REFLEJOSEXFISINP,
    "FONDO_OJOEXFISINP" => $FONDO_OJOEXFISINP,
    "ODEXFISINP" => $ODEXFISINP,
    "OIZEXFISINP" => $OIZEXFISINP,
    "COLORESEXFISINP" => $COLORESEXFISINP,
    "CAVIDAD_NASALEXFISINP" => $CAVIDAD_NASALEXFISINP,
    "MUCOSAEXFISINP" => $MUCOSAEXFISINP,
    "TABIQUE_NASALEXFISINP" => $TABIQUE_NASALEXFISINP,
    "OLFATOEXFISINP" => $OLFATOEXFISINP,
    "CERVICALEXFISINP" => $CERVICALEXFISINP,
    "DORSALEXFISINP" => $DORSALEXFISINP,
    "LUMBAREXFISINP" => $LUMBAREXFISINP,
    "LESIONESEXFISINP" => $LESIONESEXFISINP,
    "ENCIASEXFISINP" => $ENCIASEXFISINP,
    "OROIFARINGEEXFISINP" => $OROIFARINGEEXFISINP,
    "CAEEXFISINP" => $CAEEXFISINP,
    "MEM_TIMEXCAEEXFISINP" => $MEM_TIMEXCAEEXFISINP,
    "AGUD_AUDITEXCAEEXFISINP" => $AGUD_AUDITEXCAEEXFISINP,
    "ODEXCAEEXFISINP" => $ODEXCAEEXFISINP,
    "OIEXCAEEXFISINP" => $OIEXCAEEXFISINP,
    "RUIDOS_CARDIACOSEXFISINP" => $RUIDOS_CARDIACOSEXFISINP,
    "REG_PRECORDIALEXFISINP" => $REG_PRECORDIALEXFISINP,
    "CAMPOS_PULMEXFISINP" => $CAMPOS_PULMEXFISINP,
    "DEFORMACIONESEXFISINP" => $DEFORMACIONESEXFISINP,
    "DOLOREXFISINP" => $DOLOREXFISINP,
    "MOVIMIENTOSEXFISINP" => $MOVIMIENTOSEXFISINP,
    "MARCHAEXFISINP" => $MARCHAEXFISINP,
    "LASSEGUEEXFISINP" => $LASSEGUEEXFISINP,
    "PUNTA_TALONEXFISINP" => $PUNTA_TALONEXFISINP,
    "FORMAEXFISINP" => $FORMAEXFISINP,
    "VISCEROMEGALIASEXFISINP" => $VISCEROMEGALIASEXFISINP,
    "HERNIASEXFISINP" => $HERNIASEXFISINP,
    "DOLOREXFISINP" => $DOLOREXFISINP,
    "PERISTALSISEXFISINP" => $PERISTALSISEXFISINP,
    "MASCULINOEXFISINP" => $MASCULINOEXFISINP,
    "FEMENINOEXFISINP" => $FEMENINOEXFISINP,
    "PUNTOS_URETRALESEXFISINP" => $PUNTOS_URETRALESEXFISINP,
    "FOSAS_RENALESEXFISINP" => $FOSAS_RENALESEXFISINP,
    "SUPERIOREXFISINP" => $SUPERIOREXFISINP,
    "INFERIOREXFISINP" => $INFERIOREXFISINP,
    "IVPEXFISINP" => $IVPEXFISINP,
    "EDEMAEXFISINP" => $EDEMAEXFISINP,
    "LUNARESEXFISINP" => $LUNARESEXFISINP,
    "PIGMENTACIONEXFISINP" => $PIGMENTACIONEXFISINP,
    "CICATRICES_QUIRUREXFISINP" => $CICATRICES_QUIRUREXFISINP,
    "DIENTE_11" => $DIENTE_11,
    "DIENTE_12" => $DIENTE_12,
    "DIENTE_13" => $DIENTE_13,
    "DIENTE_14" => $DIENTE_14,
    "DIENTE_15" => $DIENTE_15,
    "DIENTE_16" => $DIENTE_16,
    "DIENTE_17" => $DIENTE_17,
    "DIENTE_18" => $DIENTE_18,
    "DIENTE_41" => $DIENTE_41,
    "DIENTE_42" => $DIENTE_42,
    "DIENTE_43" => $DIENTE_43,
    "DIENTE_44" => $DIENTE_44,
    "DIENTE_45" => $DIENTE_45,
    "DIENTE_46" => $DIENTE_46,
    "DIENTE_47" => $DIENTE_47,
    "DIENTE_48" => $DIENTE_48,
    "DIENTE_2" => $DIENTE_2,
    "DIENTE_22" => $DIENTE_22,
    "DIENTE_23" => $DIENTE_23,
    "DIENTE_24" => $DIENTE_24,
    "DIENTE_25" => $DIENTE_25,
    "DIENTE_26" => $DIENTE_26,
    "DIENTE_27" => $DIENTE_27,
    "DIENTE_28" => $DIENTE_28,
    "DIENTE_31" => $DIENTE_31,
    "DIENTE_32" => $DIENTE_32,
    "DIENTE_33" => $DIENTE_33,
    "DIENTE_34" => $DIENTE_34,
    "DIENTE_35" => $DIENTE_35,
    "DIENTE_36" => $DIENTE_36,
    "DIENTE_37" => $DIENTE_37,
    "DIENTE_38" => $DIENTE_38,
    "RESULTADOSESYRES" => $RESULTADOSESYRES,
    "OBSERVACIONESDIAGINP" => $OBSERVACIONESDIAGINP,
    "OBSERVACIONESPLATERINP" => $OBSERVACIONESPLATERINP,
    "DEFORMACIONES_OBSINP" => $DEFORMACIONES_OBSINP,
    "TIROIDES_OBSINP" => $TIROIDES_OBSINP,
    "TRAQUEA_OBSINP" => $TRAQUEA_OBSINP,
    "resExamIn" => $resExamIn,
    "FIRMA" => $FIRMA
]);
$others->insertDatsExpFis($data = [
    "nss" => $nss,
    "content" => $tipoExamenInputO,
    "name" => "tipoExamenInputO",
]);
$others->insertDatsExpFis($data = [
    "nss" => $nss,
    "content" => $Drenajein,
    "name" => "Drenaje",
]);
$others->insertDatsExpFis($data = [
    "nss" => $nss,
    "content" => $CCAIn,
    "name" => "CCA"
]);
$others->insertDatsExpFis($data = [
    "nss" => $nss,
    "content" => $VOZCLARAYFUERTEINP,
    "name" => "VOZCLARAYFUERTE"
]);
$others->insertDatsExpFis($data = [
    "nss" => $nss,
    "content" => $STPO2INP,
    "name" => "STPO2"
]);

$others->insertDatsExpFis($data = [
    "nss" => $nss,
    "content" => $edad_inicio_laborar,
    "name" => "edad_inicio_laborar"
]);
$others->insertDatsExpFis($data = [
    "nss" => $nss,
    "content" => $cantidad_trabajos,
    "name" => "cantidad_trabajos"
]);
$others->insertDatsExpFis($data = [
    "nss" => $nss,
    "content" => $pension,
    "name" => "pension"
]);

$others->insertDatsExpFis($data = [
    "nss" => $nss,
    "content" => $nombre1,
    "name" => "nombre1"
]);
$others->insertDatsExpFis($data = [
    "nss" => $nss,
    "content" => $giro1,
    "name" => "giro1"
]);
$others->insertDatsExpFis($data = [
    "nss" => $nss,
    "content" => $puesto1,
    "name" => "puesto1"
]);
$others->insertDatsExpFis($data = [
    "nss" => $nss,
    "content" => $turno1,
    "name" => "turno1"
]);
$others->insertDatsExpFis($data = [
    "nss" => $nss,
    "content" => $antiguedad1,
    "name" => "antiguedad1"
]);
$others->insertDatsExpFis($data = [
    "nss" => $nss,
    "content" => $salida1,
    "name" => "salida1"
]);
$others->insertDatsExpFis($data = [
    "nss" => $nss,
    "content" => $descripcion1,
    "name" => "descripcion1"
]);
$others->insertDatsExpFis($data = [
    "nss" => $nss,
    "content" => $riesgos1,
    "name" => "riesgos1"
]);
$others->insertDatsExpFis($data = [
    "nss" => $nss,
    "content" => $epp1,
    "name" => "epp1"
]);
$others->insertDatsExpFis($data = [
    "nss" => $nss,
    "content" => $observaciones1,
    "name" => "observaciones1"
]);

$others->insertDatsExpFis($data = [
    "nss" => $nss,
    "content" => $nombre2,
    "name" => "nombre2"
]);
$others->insertDatsExpFis($data = [
    "nss" => $nss,
    "content" => $giro2,
    "name" => "giro2"
]);
$others->insertDatsExpFis($data = [
    "nss" => $nss,
    "content" => $puesto2,
    "name" => "puesto2"
]);
$others->insertDatsExpFis($data = [
    "nss" => $nss,
    "content" => $turno2,
    "name" => "turno2"
]);
$others->insertDatsExpFis($data = [
    "nss" => $nss,
    "content" => $antiguedad2,
    "name" => "antiguedad2"
]);
$others->insertDatsExpFis($data = [
    "nss" => $nss,
    "content" => $salida2,
    "name" => "salida2"
]);
$others->insertDatsExpFis($data = [
    "nss" => $nss,
    "content" => $descripcion2,
    "name" => "descripcion2"
]);
$others->insertDatsExpFis($data = [
    "nss" => $nss,
    "content" => $riesgos2,
    "name" => "riesgos2"
]);
$others->insertDatsExpFis($data = [
    "nss" => $nss,
    "content" => $epp2,
    "name" => "epp2"
]);
$others->insertDatsExpFis($data = [
    "nss" => $nss,
    "content" => $observaciones2,
    "name" => "observaciones2"
]);

$others->insertDatsExpFis($data = [
    "nss" => $nss,
    "content" => $nombre3,
    "name" => "nombre3"
]);
$others->insertDatsExpFis($data = [
    "nss" => $nss,
    "content" => $giro3,
    "name" => "giro3"
]);
$others->insertDatsExpFis($data = [
    "nss" => $nss,
    "content" => $puesto3,
    "name" => "puesto3"
]);
$others->insertDatsExpFis($data = [
    "nss" => $nss,
    "content" => $turno3,
    "name" => "turno3"
]);
$others->insertDatsExpFis($data = [
    "nss" => $nss,
    "content" => $antiguedad3,
    "name" => "antiguedad3"
]);
$others->insertDatsExpFis($data = [
    "nss" => $nss,
    "content" => $salida3,
    "name" => "salida3"
]);
$others->insertDatsExpFis($data = [
    "nss" => $nss,
    "content" => $descripcion3,
    "name" => "descripcion3"
]);
$others->insertDatsExpFis($data = [
    "nss" => $nss,
    "content" => $riesgos3,
    "name" => "riesgos3"
]);
$others->insertDatsExpFis($data = [
    "nss" => $nss,
    "content" => $epp3,
    "name" => "epp3"
]);
$others->insertDatsExpFis($data = [
    "nss" => $nss,
    "content" => $observaciones3,
    "name" => "observaciones3"
]);

$others->insertDatsExpFis($data = [
    "nss" => $nss,
    "content" => $nombre4,
    "name" => "nombre4"
]);
$others->insertDatsExpFis($data = [
    "nss" => $nss,
    "content" => $giro4,
    "name" => "giro4"
]);
$others->insertDatsExpFis($data = [
    "nss" => $nss,
    "content" => $puesto4,
    "name" => "puesto4"
]);
$others->insertDatsExpFis($data = [
    "nss" => $nss,
    "content" => $turno4,
    "name" => "turno4"
]);
$others->insertDatsExpFis($data = [
    "nss" => $nss,
    "content" => $antiguedad4,
    "name" => "antiguedad4"
]);
$others->insertDatsExpFis($data = [
    "nss" => $nss,
    "content" => $salida4,
    "name" => "salida4"
]);
$others->insertDatsExpFis($data = [
    "nss" => $nss,
    "content" => $descripcion4,
    "name" => "descripcion4"
]);
$others->insertDatsExpFis($data = [
    "nss" => $nss,
    "content" => $riesgos4,
    "name" => "riesgos4"
]);
$others->insertDatsExpFis($data = [
    "nss" => $nss,
    "content" => $epp4,
    "name" => "epp4"
]);
$others->insertDatsExpFis($data = [
    "nss" => $nss,
    "content" => $observaciones4,
    "name" => "observaciones4"
]);
$others->insertDatsExpFis($data = [
    "nss" => $nss,
    "content" => $OBSGENERALINPEX,
    "name" => "OBSGENERALINPEX"
]);
$others->insertDatsExpFis($data = [
    "nss" => $nss,
    "content" => $ODEXCAEEXFISINP,
    "name" => "ODEXCAEEXFISINP"
]);
$others->insertDatsExpFis($data = [
    "nss" => $nss,
    "content" => $ODCAEINPEXP,
    "name" => "ODCAEINPEXP"
]);
$others->insertDatsExpFis($data = [
    "nss" => $nss,
    "content" => $ODMEMTIMINPEXP,
    "name" => "ODMEMTIMINPEXP"
]);
$others->insertDatsExpFis($data = [
    "nss" => $nss,
    "content" => $ODAGAUDIINPEXP,
    "name" => "ODAGAUDIINPEXP"
]);
$others->insertDatsExpFis($data = [
    "nss" => $nss,
    "content" => $OICAEINPEXP,
    "name" => "OICAEINPEXP"
]);
$others->insertDatsExpFis($data = [
    "nss" => $nss,
    "content" => $OIMEMTIMINPEXP,
    "name" => "OIMEMTIMINPEXP"
]);
$others->insertDatsExpFis($data = [
    "nss" => $nss,
    "content" => $OIAGAUDIINPEXP,
    "name" => "OIAGAUDIINPEXP"
]);
$others->insertDatsExpFis($data = [
    "nss" => $nss,
    "content" => $TRAQUEA_OBSINP,
    "name" => "TRAQUEA_OBSINP"
]);
$others->insertDatsExpFis($data = [
    "nss" => $nss,
    "content" => $DIENTE_2,
    "name" => "DIENTE_2"
]);
$others->insertDatsExpFis($data = [
    "nss" => $nss,
    "content" => $ciruOBS,
    "name" => "ciruOBS"
]);
$others->insertDatsExpFis($data = [
    "nss" => $nss,
    "content" => $LENTEOJODERECHOEXP,
    "name" => "LENTEOJODERECHOEXP"
]);
$others->insertDatsExpFis($data = [
    "nss" => $nss,
    "content" => $LENTEOJOIZQUIERDOEXP,
    "name" => "LENTEOJOIZQUIERDOEXP"
]);
$others->insertDatsExpFis($data = [
    "nss" => $nss,
    "content" => $ROMBERGEXFIS,
    "name" => "ROMBERGEXFIS"
]);
