# Profile-specific overrides
spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/PROYECTO_BASE_PDB
spring.datasource.username=usr_boilerplate
spring.datasource.password=AppPassword_2026#
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
