# Profile-specific overrides
# Profile-specific overrides
spring.datasource.url=jdbc:oracle:thin:@200.94.116.132:1521/orclpdb
spring.datasource.username=ONEWMS_QA
spring.datasource.password=Ol3rOn3.c4Wm5.3
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
