-- =============================================================================
-- APP_FS_FILE — Metadatos de archivos (binario en filesystem, NO en BD)
-- =============================================================================
-- Proyecto   : Portal Salud — portalsalud-personal
-- Contrato   : docs/architecture/architecture-contract.json > fileManagementContract
--              storageModel = "metadata-in-db-and-binary-in-filesystem"
-- Autor      : Agente IA (Claude) + revisión Tech Lead
-- Fecha      : 2026-07-13
-- Versión    : V1
--
-- PROPÓSITO
-- ─────────
-- Tabla de metadatos del modelo de almacenamiento acordado: el BINARIO vive en
-- el filesystem (portal.files.root, sharding yyyy/MM/dd/<2 del sha256>, nombre
-- UUID) y AQUÍ solo se guardan sus metadatos + la ruta (STORAGE_PATH relativa).
--
-- Reemplaza, para los archivos NUEVOS, el uso de MED_FILE.CONTENT_BLOB (que
-- guardaba el binario en la BD). MED_FILE queda SOLO como capa de aterrizaje de
-- la migración histórica del legacy (files.url base64). Ver files-salud.sql NOTA-5.
--
-- PATRONES DE ACCESO (igual que el legacy files):
--   · Adjuntos de una consulta:  WHERE FILE_TYPE = <consulta_relacionada>
--   · Por NSS + tipo funcional:  WHERE NSS = ? AND FILE_TYPE = 'examen_medico'|...
-- =============================================================================

SET SERVEROUTPUT ON;

-- =============================================================================
-- BLOQUE 1: TABLA APP_FS_FILE
-- =============================================================================
BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE APP_FS_FILE (
      -- Clave primaria
      ID              NUMBER
                      GENERATED BY DEFAULT AS IDENTITY
                      CONSTRAINT PK_APP_FS_FILE PRIMARY KEY,

      -- Identidad de negocio
      BUSINESS_KEY    VARCHAR2(64)  NOT NULL,     -- UUID estable por archivo
      NSS             VARCHAR2(50),               -- dueño (empleado/candidato)
      FILE_TYPE       VARCHAR2(120),              -- relación consulta o tipo funcional

      -- Metadatos del archivo
      ORIGINAL_NAME   VARCHAR2(400) NOT NULL,     -- nombre original (solo referencia)
      EXTENSION       VARCHAR2(20),
      MIME_TYPE       VARCHAR2(200) DEFAULT 'application/pdf',
      SIZE_BYTES      NUMBER        NOT NULL,
      CHECKSUM_SHA256 VARCHAR2(64)  NOT NULL,     -- integridad del binario

      -- Ubicación física (el binario NO está en la BD)
      STORAGE_PATH    VARCHAR2(400) NOT NULL,     -- ruta RELATIVA a portal.files.root
      STORAGE_PROVIDER VARCHAR2(40) DEFAULT 'FILESYSTEM' NOT NULL,

      -- Estado / versión
      STATUS          VARCHAR2(20)  DEFAULT 'ACTIVE' NOT NULL,  -- ACTIVE|DELETED
      VERSION         NUMBER        DEFAULT 1 NOT NULL,
      DATE_UPLOAD     TIMESTAMP(6)  DEFAULT SYSTIMESTAMP NOT NULL,

      -- Auditoría estándar
      CREATED_AT      TIMESTAMP(6)  DEFAULT SYSTIMESTAMP NOT NULL,
      CREATED_BY      VARCHAR2(100) DEFAULT 'SISTEMA' NOT NULL,
      UPDATED_AT      TIMESTAMP(6),
      UPDATED_BY      VARCHAR2(100)
    )
  ]';
  DBMS_OUTPUT.PUT_LINE('[OK] Tabla APP_FS_FILE creada.');
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE = -955 THEN DBMS_OUTPUT.PUT_LINE('[SKIP] APP_FS_FILE ya existe.');
  ELSE RAISE; END IF;
END;
/

COMMENT ON TABLE  APP_FS_FILE                 IS 'Metadatos de archivos; binario en filesystem (portal.files.root). Contrato metadata-in-db-and-binary-in-filesystem.';
COMMENT ON COLUMN APP_FS_FILE.STORAGE_PATH    IS 'Ruta RELATIVA a la raiz por entorno: yyyy/MM/dd/<2 del sha256>/<uuid>.<ext>';
COMMENT ON COLUMN APP_FS_FILE.CHECKSUM_SHA256 IS 'SHA-256 del contenido; integridad y futura deduplicacion.';
COMMENT ON COLUMN APP_FS_FILE.FILE_TYPE       IS 'consulta_relacionada | examen_medico | nota_medica | laboratorio | nota_incapacidad';
COMMENT ON COLUMN APP_FS_FILE.STATUS          IS 'ACTIVE|DELETED (hoy el borrado es fisico; columna reservada para soft-delete).';
/

-- =============================================================================
-- BLOQUE 2: ÍNDICES (según patrones de acceso reales)
-- =============================================================================
BEGIN EXECUTE IMMEDIATE 'CREATE INDEX IDX_APP_FS_FILE_TYPE     ON APP_FS_FILE (FILE_TYPE)';
  DBMS_OUTPUT.PUT_LINE('[OK] IDX_APP_FS_FILE_TYPE');
EXCEPTION WHEN OTHERS THEN IF SQLCODE=-955 THEN NULL; ELSE RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE INDEX IDX_APP_FS_FILE_NSS_TYPE ON APP_FS_FILE (NSS, FILE_TYPE)';
  DBMS_OUTPUT.PUT_LINE('[OK] IDX_APP_FS_FILE_NSS_TYPE');
EXCEPTION WHEN OTHERS THEN IF SQLCODE=-955 THEN NULL; ELSE RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX UX_APP_FS_FILE_BKEY ON APP_FS_FILE (BUSINESS_KEY)';
  DBMS_OUTPUT.PUT_LINE('[OK] UX_APP_FS_FILE_BKEY');
EXCEPTION WHEN OTHERS THEN IF SQLCODE=-955 THEN NULL; ELSE RAISE; END IF; END;
/

-- =============================================================================
-- FIN DEL SCRIPT
-- =============================================================================
