-- =============================================================================
-- Importador Excel (Analisis > Importar Excel) - tablas TEMPORALES de staging.
-- Aplicar en la BD del portal (la misma de APP_FS_FILE / APP_AUD_EVENT), NO en ORDS.
--
-- Por que "temporal": hoy no existen los layouts ni las tablas destino del reporte
-- gerencial. El importador lee el archivo, lo valida y deja TODO aqui (una fila por
-- renglon de cada hoja, valores en JSON) mas el archivo original en APP_FS_FILE.
-- Cuando lleguen los layouts, el mapeo hoja -> tabla final se hace desde estas
-- tablas sin volver a pedir el archivo.
--
-- Versionado: si se vuelve a cargar un archivo con el MISMO nombre, el lote
-- anterior no se borra: pasa a estado SUSTITUIDO y el nuevo lleva VERSION + 1.
-- El binario anterior tambien se conserva (APP_FS_FILE.VERSION).
-- =============================================================================
SET SERVEROUTPUT ON;

BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE APP_IMPORT_LOTE (
      ID               NUMBER GENERATED BY DEFAULT AS IDENTITY
                       CONSTRAINT PK_APP_IMPORT_LOTE PRIMARY KEY,
      -- archivo
      FS_FILE_ID       NUMBER,                        -- APP_FS_FILE.ID (binario en filesystem)
      NOMBRE_ARCHIVO   VARCHAR2(400) NOT NULL,
      EXTENSION        VARCHAR2(10),
      SIZE_BYTES       NUMBER,
      CHECKSUM_SHA256  VARCHAR2(64),
      VERSION          NUMBER DEFAULT 1 NOT NULL,     -- por NOMBRE_ARCHIVO
      -- resultado de la validacion
      ESTADO           VARCHAR2(20) DEFAULT 'VALIDADO' NOT NULL, -- VALIDADO|CONFIRMADO|DESCARTADO|SUSTITUIDO
      HOJAS            NUMBER DEFAULT 0 NOT NULL,
      PROCESADOS       NUMBER DEFAULT 0 NOT NULL,
      CORRECTOS        NUMBER DEFAULT 0 NOT NULL,
      ADVERTENCIAS     NUMBER DEFAULT 0 NOT NULL,
      RECHAZADOS       NUMBER DEFAULT 0 NOT NULL,
      RESUMEN_JSON     CLOB,                          -- hojas + incidencias, tal como se pintan
      -- auditoria
      CREATED_AT       TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
      CREATED_BY       VARCHAR2(120),
      CONFIRMED_AT     TIMESTAMP(6),
      CONFIRMED_BY     VARCHAR2(120)
    )
  ]';
  DBMS_OUTPUT.PUT_LINE('[OK] APP_IMPORT_LOTE creada.');
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE = -955 THEN DBMS_OUTPUT.PUT_LINE('[SKIP] APP_IMPORT_LOTE ya existe.');
  ELSE RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE APP_IMPORT_FILA (
      ID               NUMBER GENERATED BY DEFAULT AS IDENTITY
                       CONSTRAINT PK_APP_IMPORT_FILA PRIMARY KEY,
      LOTE_ID          NUMBER NOT NULL
                       CONSTRAINT FK_APP_IMPORT_FILA_LOTE REFERENCES APP_IMPORT_LOTE (ID),
      HOJA             VARCHAR2(120) NOT NULL,
      FILA_NUM         NUMBER NOT NULL,               -- numero de renglon en la hoja (1-based, como Excel)
      ESTADO           VARCHAR2(20) NOT NULL,         -- OK|ADVERTENCIA|RECHAZADO
      MENSAJES         VARCHAR2(2000),                -- " · " separado
      VALORES_JSON     CLOB NOT NULL                  -- {"ENCABEZADO": valor, ...} en el orden de la hoja
    )
  ]';
  DBMS_OUTPUT.PUT_LINE('[OK] APP_IMPORT_FILA creada.');
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE = -955 THEN DBMS_OUTPUT.PUT_LINE('[SKIP] APP_IMPORT_FILA ya existe.');
  ELSE RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX IX_APP_IMPORT_FILA_LOTE ON APP_IMPORT_FILA (LOTE_ID, HOJA, FILA_NUM)';
  DBMS_OUTPUT.PUT_LINE('[OK] IX_APP_IMPORT_FILA_LOTE creado.');
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE IN (-955, -1408) THEN DBMS_OUTPUT.PUT_LINE('[SKIP] IX_APP_IMPORT_FILA_LOTE ya existe.');
  ELSE RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX IX_APP_IMPORT_LOTE_NOMBRE ON APP_IMPORT_LOTE (NOMBRE_ARCHIVO, VERSION)';
  DBMS_OUTPUT.PUT_LINE('[OK] IX_APP_IMPORT_LOTE_NOMBRE creado.');
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE IN (-955, -1408) THEN DBMS_OUTPUT.PUT_LINE('[SKIP] IX_APP_IMPORT_LOTE_NOMBRE ya existe.');
  ELSE RAISE; END IF;
END;
/

COMMENT ON TABLE APP_IMPORT_LOTE IS 'Importador Excel: un lote por archivo cargado. Staging temporal hasta tener layouts destino.';
COMMENT ON TABLE APP_IMPORT_FILA IS 'Importador Excel: un renglon por fila de cada hoja del lote, valores en JSON.';

-- Verificacion rapida:
--   select * from APP_IMPORT_LOTE order by id desc;
--   select hoja, estado, count(*) from APP_IMPORT_FILA where lote_id = :id group by hoja, estado;
