-- =============================================================================
-- Examen medico inicial (FT-SO-04 rev. 04) - modulo de captura por hojas.
-- Aplicar en la BASE DEL PORTAL (tablas SERV_MED_* dentro de BIOMETRICO), NO en ORDS.
--
-- El examen terminado NO se guarda aqui: al "Finalizar" viaja al mismo almacen que el
-- modulo Examen medico (WS Servcio/Medico + SERV_MED_TAG), con tipoExamenInputO = 1
-- (Admision). Esta tabla guarda solo el BORRADOR mientras el medico captura (se guarda
-- solo, hoja por hoja) y deja constancia de que ese examen se capturo desde este modulo.
--
-- Por que borrador: el WS pisa con NULL cualquier seccion que no viaje en el payload
-- (PR_SERVICIO_MED_EXAMEN2 hace UPDATE incondicional por seccion). Capturar 10 hojas en
-- varias sentadas mandando cada una al WS seria destructivo; con el borrador se manda
-- todo de una vez al final.
-- =============================================================================
SET SERVEROUTPUT ON;

BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE SERV_MED_EXAMEN_BORRADOR (
      ID             NUMBER GENERATED BY DEFAULT AS IDENTITY
                     CONSTRAINT SERV_MED_PK_EXAMEN_BORRADOR PRIMARY KEY,
      NSS            VARCHAR2(50)  NOT NULL,
      TIPO_EXAMEN    VARCHAR2(20)  DEFAULT 'INICIAL'  NOT NULL,   -- INICIAL (unico por ahora)
      ESTATUS        VARCHAR2(20)  DEFAULT 'BORRADOR' NOT NULL,   -- BORRADOR | FINALIZADO
      HOJA_ACTUAL    NUMBER(2)     DEFAULT 1 NOT NULL,            -- donde se quedo el medico
      DATOS          CLOB,                                        -- JSON {clave: valor}
      CREATED_AT     TIMESTAMP(6)  DEFAULT SYSTIMESTAMP NOT NULL,
      CREATED_BY     VARCHAR2(100),
      UPDATED_AT     TIMESTAMP(6)  DEFAULT SYSTIMESTAMP NOT NULL,
      UPDATED_BY     VARCHAR2(100),
      FINALIZADO_AT  TIMESTAMP(6),
      FINALIZADO_BY  VARCHAR2(100),
      CONSTRAINT SERV_MED_CK_EXAMEN_BORR_EST CHECK (ESTATUS IN ('BORRADOR','FINALIZADO'))
    )
  ]';
  DBMS_OUTPUT.PUT_LINE('SERV_MED_EXAMEN_BORRADOR creada');
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX SERV_MED_IX_EXAMEN_BORR_NSS ON SERV_MED_EXAMEN_BORRADOR (NSS, ESTATUS)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
/

-- Menu del expediente de la persona (fragments/nss-modules.html resuelve la pantalla por CODE).
-- Se asigna a los mismos roles que ya ven EXAMEN_MEDICO, para no inventar permisos nuevos.
DECLARE
  v_id NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_id FROM SERV_MED_MENU WHERE CODE = 'EXAMEN_INICIAL';
  IF v_id = 0 THEN
    INSERT INTO SERV_MED_MENU (CODE, TITLE, ICON, ORDER_NO, ACTIVE)
    VALUES ('EXAMEN_INICIAL', 'Examen Médico Inicial', 'ri-file-add-line',
            (SELECT NVL(MAX(ORDER_NO), 0) + 1 FROM SERV_MED_MENU WHERE CODE = 'EXAMEN_MEDICO'), 'Y');
    DBMS_OUTPUT.PUT_LINE('Menu EXAMEN_INICIAL insertado');
  END IF;
  INSERT INTO SERV_MED_MENU_ROLE (MENU_ID, ROLE_ID)
  SELECT n.ID, mr.ROLE_ID
    FROM SERV_MED_MENU n, SERV_MED_MENU m
    JOIN SERV_MED_MENU_ROLE mr ON mr.MENU_ID = m.ID
   WHERE n.CODE = 'EXAMEN_INICIAL' AND m.CODE = 'EXAMEN_MEDICO'
     AND NOT EXISTS (SELECT 1 FROM SERV_MED_MENU_ROLE x WHERE x.MENU_ID = n.ID AND x.ROLE_ID = mr.ROLE_ID);
  DBMS_OUTPUT.PUT_LINE('Roles asignados: ' || SQL%ROWCOUNT);
  COMMIT;
END;
/
