-- =============================================================================
-- Historico de examenes medicos finalizados (foto completa por examen).
-- Aplicar en la BASE DEL PORTAL (tablas SERV_MED_* dentro de BIOMETRICO), NO en ORDS.
--
-- El WS Servcio/Medico guarda UN examen por persona: cada guardado con dictamen pisa al
-- anterior, desde cualquiera de los dos modulos (Examen medico y Examen medico inicial), y
-- el proc de lectura rellena con COALESCE, asi que nunca se sabe que habia antes.
-- Esta tabla guarda una fila por examen finalizado, con el examen completo en JSON, desde
-- los dos modulos. No cambia ningun flujo: el guardado sigue yendo al WS como siempre y de
-- paso deja aqui su copia.
--
-- Usos: saber si un examen fue inicial (ORIGEN/TIPO_EXAMEN), candado del modulo inicial,
-- tipo de examen en el dashboard, lista de no aptos, y consultar un examen anterior.
-- NO alimenta cantidades del dashboard (esas siguen saliendo del WS); solo etiqueta.
-- =============================================================================
SET SERVEROUTPUT ON;

BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE SERV_MED_EXAMEN_HISTORICO (
      ID             NUMBER GENERATED BY DEFAULT AS IDENTITY
                     CONSTRAINT SERV_MED_PK_EXAMEN_HIST PRIMARY KEY,
      NSS            VARCHAR2(50)  NOT NULL,
      ORIGEN         VARCHAR2(20)  NOT NULL,            -- INICIAL (modulo inicial) | GENERAL (modulo Examen medico)
      TIPO_EXAMEN    VARCHAR2(5),                       -- codigo del legacy: 1 Admision, 2 Periodico, 3 Cambio de rol,
                                                        -- 4 Post incapacidad, 5 Especial; NULL si no se capturo
      DICTAMEN       VARCHAR2(30),                      -- apto | no_apto | apto_condicionado | apto_restringido
      FECHA_EXAMEN   TIMESTAMP(6)  DEFAULT SYSTIMESTAMP NOT NULL,
      USUARIO        VARCHAR2(100),
      DATOS          CLOB,                              -- examen completo aplanado {SECCION.CAMPO: valor}
      CREATED_AT     TIMESTAMP(6)  DEFAULT SYSTIMESTAMP NOT NULL,
      CONSTRAINT SERV_MED_CK_EXAMEN_HIST_ORI CHECK (ORIGEN IN ('INICIAL','GENERAL'))
    )
  ]';
  DBMS_OUTPUT.PUT_LINE('SERV_MED_EXAMEN_HISTORICO creada');
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; ELSE DBMS_OUTPUT.PUT_LINE('SERV_MED_EXAMEN_HISTORICO ya existia'); END IF; END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX SERV_MED_IX_EXAMEN_HIST_NSS ON SERV_MED_EXAMEN_HISTORICO (NSS, FECHA_EXAMEN)';
  DBMS_OUTPUT.PUT_LINE('SERV_MED_IX_EXAMEN_HIST_NSS creado');
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; ELSE DBMS_OUTPUT.PUT_LINE('SERV_MED_IX_EXAMEN_HIST_NSS ya existia'); END IF; END;
/
