-- =============================================================================
-- MIGRACIÓN: servicioMedico.files (MariaDB) → MED_FILE (Oracle 21c)
-- =============================================================================
-- Proyecto   : Portal Salud — portalsalud-personal
-- Origen     : MariaDB · servicioMedico.files
-- Destino    : Oracle 21c · MED_FILE
-- Autor      : Agente IA (Claude) + revisión Tech Lead
-- Fecha      : 2026-07-04
-- Versión    : V1
--
-- ALCANCE
-- ───────
-- Migra la tabla `files` (adjuntos PDF del expediente) como tabla de aterrizaje
-- fiel MED_FILE, consistente con la estrategia de tags-salud.sql:
-- "landear primero sin pérdida, normalizar/optimizar después".
--
-- CONTEXTO DE LA TABLA ORIGEN (confirmado en Contexto.txt)
-- ────────────────────────────────────────────────────────
--   files
--   ├── id           int(10)   PK AUTO_INCREMENT
--   ├── nss          varchar(50)
--   ├── name         varchar(50)   -- ⚠ encoding mixto latin1/utf8 (~0.4% filas)
--   ├── date_upload  datetime
--   ├── url          longtext      -- ‼ NO es URL: es el PDF completo en base64
--   └── type         varchar(50)   -- examen_medico|nota_medica|laboratorio|
--                                   --  nota_incapacidad|''|<hash_MD5_32>
--
-- Estadística (muestra 500 filas): url base64 promedio 539 KB, p90 932 KB,
-- máx ~2 MB. 11 filas con url vacío (huérfanas). 17 GB backup total.
--
-- USO EN EL CÓDIGO (relevante para índices):
--   · Adjuntos de una consulta:  SELECT * FROM files WHERE type = <consulta_relacionada>
--   · Por NSS + type funcional:  SELECT * FROM files WHERE nss=? AND type='examen_medico'
--   · downloadPDFCons: el front toma url (base64) y la descarga como application/pdf
--
-- DECISIÓN DE DISEÑO
-- ───────────────────
-- MED_FILE guarda:
--   · URL_B64  (CLOB)  → copia FIEL del base64 de origen (cero pérdida)
--   · CONTENT_BLOB (BLOB, nullable) → binario decodificado (ahorra ~33% vs base64)
--     Se puebla en un 2º paso (SP_DECODE_FILE_BLOBS) tras validar el landing.
-- Una vez validado CONTENT_BLOB se puede vaciar URL_B64 para recuperar espacio.
-- Prereq de ejecución: DB Link a MariaDB o export (ver BLOQUE 6). Igual que tags.
-- =============================================================================

SET SERVEROUTPUT ON;

-- =============================================================================
-- BLOQUE 1: TABLA DESTINO MED_FILE
-- =============================================================================
BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE MED_FILE (
      -- Clave primaria
      ID            NUMBER
                    GENERATED BY DEFAULT AS IDENTITY
                    CONSTRAINT PK_MED_FILE PRIMARY KEY,

      -- Datos de negocio (mapeo directo de files legacy)
      NSS           VARCHAR2(50),            -- files.nss
      NAME          VARCHAR2(400),           -- files.name (ampliado; ver NOTA encoding)
      DATE_UPLOAD   TIMESTAMP(6),            -- files.date_upload
      FILE_TYPE     VARCHAR2(120),           -- files.type (incluye '' y hash MD5)

      -- Binario
      MIME_TYPE     VARCHAR2(200) DEFAULT 'application/pdf',
      URL_B64       CLOB,                    -- files.url: base64 FIEL del PDF
      CONTENT_BLOB  BLOB,                    -- decodificado (2º paso, nullable)
      SIZE_BYTES    NUMBER,                  -- tamaño del binario decodificado

      -- Trazabilidad de origen (no tocar tras migración)
      SOURCE_ID     NUMBER,                  -- files.id original en MariaDB
      MIGRATED_AT   TIMESTAMP(6) DEFAULT SYSTIMESTAMP,

      -- Auditoría estándar
      CREATED_AT    TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
      CREATED_BY    VARCHAR2(100) DEFAULT 'MIGRATION' NOT NULL,
      UPDATED_AT    TIMESTAMP(6),
      UPDATED_BY    VARCHAR2(100)
    )
  ]';
  DBMS_OUTPUT.PUT_LINE('[OK] Tabla MED_FILE creada.');
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE = -955 THEN DBMS_OUTPUT.PUT_LINE('[SKIP] MED_FILE ya existe.');
  ELSE RAISE; END IF;
END;
/

COMMENT ON TABLE  MED_FILE              IS 'Adjuntos PDF del expediente — migrado desde MariaDB.servicioMedico.files';
COMMENT ON COLUMN MED_FILE.URL_B64      IS 'files.url: PDF completo en base64 (copia fiel, cero pérdida).';
COMMENT ON COLUMN MED_FILE.CONTENT_BLOB IS 'Binario decodificado desde URL_B64 (SP_DECODE_FILE_BLOBS). Nullable hasta 2º paso.';
COMMENT ON COLUMN MED_FILE.FILE_TYPE    IS 'files.type: examen_medico|nota_medica|laboratorio|nota_incapacidad|''''|hash MD5.';
COMMENT ON COLUMN MED_FILE.SOURCE_ID    IS 'files.id original en MariaDB. Reconciliación y rollback.';
/

-- =============================================================================
-- BLOQUE 2: ÍNDICES (según patrones de acceso reales del PHP)
-- =============================================================================
BEGIN EXECUTE IMMEDIATE 'CREATE INDEX IDX_MED_FILE_NSS       ON MED_FILE (NSS)';
  DBMS_OUTPUT.PUT_LINE('[OK] IDX_MED_FILE_NSS');
EXCEPTION WHEN OTHERS THEN IF SQLCODE=-955 THEN NULL; ELSE RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE INDEX IDX_MED_FILE_TYPE      ON MED_FILE (FILE_TYPE)';
  DBMS_OUTPUT.PUT_LINE('[OK] IDX_MED_FILE_TYPE');   -- adjuntos por consulta_relacionada
EXCEPTION WHEN OTHERS THEN IF SQLCODE=-955 THEN NULL; ELSE RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE INDEX IDX_MED_FILE_NSS_TYPE  ON MED_FILE (NSS, FILE_TYPE)';
  DBMS_OUTPUT.PUT_LINE('[OK] IDX_MED_FILE_NSS_TYPE');
EXCEPTION WHEN OTHERS THEN IF SQLCODE=-955 THEN NULL; ELSE RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX UX_MED_FILE_SOURCE_ID ON MED_FILE (SOURCE_ID)';
  DBMS_OUTPUT.PUT_LINE('[OK] UX_MED_FILE_SOURCE_ID');   -- evita duplicar al reanudar
EXCEPTION WHEN OTHERS THEN IF SQLCODE=-955 THEN NULL; ELSE RAISE; END IF; END;
/

-- =============================================================================
-- BLOQUE 3: FUNCIÓN BASE64 → BLOB (decodifica en chunks alineados a 4)
-- Asume base64 de una sola línea (el que produce FileReader/btoa del legacy).
-- Soporta prefijo data-URI ('data:...;base64,') si viniera presente.
-- =============================================================================
CREATE OR REPLACE FUNCTION FN_BASE64_DECODE_BLOB(p_b64 IN CLOB)
RETURN BLOB
IS
  v_blob   BLOB;
  v_len    INTEGER;
  v_pos    INTEGER := 1;
  v_step   CONSTANT INTEGER := 32764;      -- múltiplo de 4 (alinea chunks base64)
  v_chunk  VARCHAR2(32767);
  v_start  INTEGER := 1;
  v_comma  INTEGER;
BEGIN
  IF p_b64 IS NULL OR DBMS_LOB.GETLENGTH(p_b64) = 0 THEN
    RETURN NULL;
  END IF;

  -- Quitar prefijo data-URI si existe: 'data:application/pdf;base64,....'
  IF DBMS_LOB.SUBSTR(p_b64, 5, 1) = 'data:' THEN
    v_comma := DBMS_LOB.INSTR(p_b64, ',', 1, 1);
    IF v_comma > 0 THEN v_start := v_comma + 1; END IF;
  END IF;

  DBMS_LOB.CREATETEMPORARY(v_blob, TRUE);
  v_len := DBMS_LOB.GETLENGTH(p_b64);
  v_pos := v_start;
  WHILE v_pos <= v_len LOOP
    v_chunk := DBMS_LOB.SUBSTR(p_b64, v_step, v_pos);
    IF v_chunk IS NOT NULL AND LENGTH(v_chunk) > 0 THEN
      DBMS_LOB.APPEND(v_blob,
        UTL_ENCODE.BASE64_DECODE(UTL_RAW.CAST_TO_RAW(v_chunk)));
    END IF;
    v_pos := v_pos + v_step;
  END LOOP;
  RETURN v_blob;
END FN_BASE64_DECODE_BLOB;
/

-- =============================================================================
-- BLOQUE 4: TABLA DE CONTROL DE MIGRACIÓN POR LOTES
-- =============================================================================
BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE MED_FILE_MIG_LOG (
      ID             NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      PHASE          VARCHAR2(20) DEFAULT 'LANDING' NOT NULL,  -- LANDING | DECODE
      BATCH_NO       NUMBER NOT NULL,
      SOURCE_ID_FROM NUMBER,
      SOURCE_ID_TO   NUMBER,
      ROWS_EXPECTED  NUMBER,
      ROWS_DONE      NUMBER,
      STATUS         VARCHAR2(20) DEFAULT 'PENDING' NOT NULL,  -- PENDING|RUNNING|DONE|ERROR|DRY-RUN
      STARTED_AT     TIMESTAMP(6),
      FINISHED_AT    TIMESTAMP(6),
      ERROR_MSG      VARCHAR2(4000)
    )
  ]';
  DBMS_OUTPUT.PUT_LINE('[OK] MED_FILE_MIG_LOG creada.');
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE=-955 THEN DBMS_OUTPUT.PUT_LINE('[SKIP] MED_FILE_MIG_LOG ya existe.');
  ELSE RAISE; END IF;
END;
/

-- =============================================================================
-- BLOQUE 5: PROCEDIMIENTOS DE MIGRACIÓN
--
-- USO:
--   -- 1) landing fiel (metadatos + base64), dry-run primero:
--   EXEC SP_MIGRATE_FILES(p_dry_run => 'S');
--   EXEC SP_MIGRATE_FILES(p_batch_size => 50, p_dry_run => 'N');
--   -- 2) decodificar base64 -> CONTENT_BLOB (2º paso, más pesado):
--   EXEC SP_DECODE_FILE_BLOBS(p_batch_size => 50);
--
-- ⚠ LOB OVER DB LINK: seleccionar LOBs grandes vía DB Link tiene límites en
--   Oracle. Si SP_MIGRATE_FILES falla por el CLOB `url`, usar el ETL externo
--   del BLOQUE 6 (SQL*Loader), que es la vía recomendada para `files`.
-- =============================================================================
CREATE OR REPLACE PROCEDURE SP_MIGRATE_FILES (
  p_batch_size IN NUMBER DEFAULT 50,
  p_dry_run    IN CHAR   DEFAULT 'N'
)
IS
  CURSOR c_files IS
    SELECT id, nss, name, date_upload, type, url
    FROM   files@MARIADB_LINK
    WHERE  id NOT IN (SELECT SOURCE_ID FROM MED_FILE WHERE SOURCE_ID IS NOT NULL)
    ORDER BY id ASC;

  v_batch_no  NUMBER := 1;
  v_total     NUMBER := 0;
  v_cnt       NUMBER := 0;
  v_from      NUMBER;
  v_to        NUMBER;
BEGIN
  DBMS_OUTPUT.PUT_LINE('SP_MIGRATE_FILES — modo: ' ||
    CASE p_dry_run WHEN 'S' THEN 'DRY-RUN' ELSE 'REAL' END || ' lote=' || p_batch_size);

  FOR r IN c_files LOOP
    IF v_cnt = 0 THEN v_from := r.id; END IF;
    v_to := r.id;

    IF p_dry_run = 'N' THEN
      INSERT INTO MED_FILE (NSS, NAME, DATE_UPLOAD, FILE_TYPE, URL_B64,
                            SIZE_BYTES, SOURCE_ID, CREATED_BY)
      VALUES (r.nss, r.name, r.date_upload, r.type, r.url,
              NULL, r.id, 'SP_MIGRATE_FILES');
    END IF;

    v_cnt   := v_cnt + 1;
    v_total := v_total + 1;

    IF v_cnt >= p_batch_size THEN
      INSERT INTO MED_FILE_MIG_LOG (PHASE, BATCH_NO, SOURCE_ID_FROM, SOURCE_ID_TO,
             ROWS_EXPECTED, ROWS_DONE, STATUS, STARTED_AT, FINISHED_AT)
      VALUES ('LANDING', v_batch_no, v_from, v_to, v_cnt,
              CASE p_dry_run WHEN 'N' THEN v_cnt ELSE 0 END,
              CASE p_dry_run WHEN 'N' THEN 'DONE' ELSE 'DRY-RUN' END,
              SYSTIMESTAMP, SYSTIMESTAMP);
      COMMIT;
      DBMS_OUTPUT.PUT_LINE('[lote ' || v_batch_no || '] IDs ' || v_from || '→' || v_to || ' filas=' || v_cnt);
      v_batch_no := v_batch_no + 1;
      v_cnt := 0;
    END IF;
  END LOOP;

  IF v_cnt > 0 THEN
    INSERT INTO MED_FILE_MIG_LOG (PHASE, BATCH_NO, SOURCE_ID_FROM, SOURCE_ID_TO,
           ROWS_EXPECTED, ROWS_DONE, STATUS, STARTED_AT, FINISHED_AT)
    VALUES ('LANDING', v_batch_no, v_from, v_to, v_cnt,
            CASE p_dry_run WHEN 'N' THEN v_cnt ELSE 0 END,
            CASE p_dry_run WHEN 'N' THEN 'DONE' ELSE 'DRY-RUN' END,
            SYSTIMESTAMP, SYSTIMESTAMP);
    COMMIT;
  END IF;

  DBMS_OUTPUT.PUT_LINE('Total procesado: ' || v_total);
END SP_MIGRATE_FILES;
/

-- 2º paso: decodifica URL_B64 → CONTENT_BLOB y calcula SIZE_BYTES.
CREATE OR REPLACE PROCEDURE SP_DECODE_FILE_BLOBS (
  p_batch_size IN NUMBER DEFAULT 50
)
IS
  CURSOR c_pending IS
    SELECT ID, URL_B64
    FROM   MED_FILE
    WHERE  CONTENT_BLOB IS NULL
      AND  URL_B64 IS NOT NULL
      AND  DBMS_LOB.GETLENGTH(URL_B64) > 0
    FOR UPDATE OF CONTENT_BLOB, SIZE_BYTES;

  v_blob BLOB;
  v_cnt  NUMBER := 0;
BEGIN
  FOR r IN c_pending LOOP
    BEGIN
      v_blob := FN_BASE64_DECODE_BLOB(r.URL_B64);
      UPDATE MED_FILE
         SET CONTENT_BLOB = v_blob,
             SIZE_BYTES   = DBMS_LOB.GETLENGTH(v_blob),
             UPDATED_AT   = SYSTIMESTAMP,
             UPDATED_BY   = 'SP_DECODE_FILE_BLOBS'
       WHERE CURRENT OF c_pending;
    EXCEPTION WHEN OTHERS THEN
      DBMS_OUTPUT.PUT_LINE('[ERROR decode ID ' || r.ID || '] ' || SQLERRM);
    END;

    v_cnt := v_cnt + 1;
    IF MOD(v_cnt, p_batch_size) = 0 THEN COMMIT; END IF;
  END LOOP;
  COMMIT;
  DBMS_OUTPUT.PUT_LINE('Decodificados: ' || v_cnt);
END SP_DECODE_FILE_BLOBS;
/

-- =============================================================================
-- BLOQUE 6: ETL EXTERNO (VÍA RECOMENDADA PARA `files` POR EL TAMAÑO DE LOS LOB)
--
-- PASO A — Exportar desde MariaDB (fijar charset para el fix de encoding):
--   mysqldump -u root -p --default-character-set=utf8mb4 \
--     --no-create-info --complete-insert servicioMedico files > files_data.sql
--
--   O TSV para SQL*Loader (base64 en una columna LOB):
--   mysql --default-character-set=utf8mb4 -u root -p servicioMedico \
--     -e "SELECT id, nss, name, date_upload, type, url FROM files ORDER BY id" \
--     --batch --raw > files_export.tsv
--
-- PASO B — Control file de SQL*Loader (LOB de tamaño variable):
--   LOAD DATA
--   INFILE 'files_export.tsv' "STR '\n'"
--   INTO TABLE MED_FILE
--   FIELDS TERMINATED BY '\t' TRAILING NULLCOLS
--   ( SOURCE_ID, NSS, NAME CHAR(4000), DATE_UPLOAD DATE "YYYY-MM-DD HH24:MI:SS",
--     FILE_TYPE, URL_B64 CHAR(100000000),
--     CREATED_BY CONSTANT 'ETL_SQLLDR' )
--
-- PASO C — Ejecutar SP_DECODE_FILE_BLOBS para poblar CONTENT_BLOB.
-- =============================================================================

-- =============================================================================
-- BLOQUE 7: VISTAS DE RECONCILIACIÓN
-- =============================================================================
-- 7a. Resumen por tipo funcional
CREATE OR REPLACE VIEW V_MED_FILE_BY_TYPE AS
SELECT NVL(FILE_TYPE, '(vacio)') AS FILE_TYPE,
       COUNT(*) AS TOTAL_FILAS,
       COUNT(DISTINCT NSS) AS TOTAL_NSS,
       SUM(CASE WHEN CONTENT_BLOB IS NOT NULL THEN 1 ELSE 0 END) AS DECODIFICADOS,
       ROUND(SUM(NVL(SIZE_BYTES,0))/1024/1024, 2) AS MB_BINARIO
FROM MED_FILE
GROUP BY NVL(FILE_TYPE, '(vacio)')
ORDER BY TOTAL_FILAS DESC;
/

-- 7b. Huérfanos: sin binario (url vacío en origen) — se esperaban ~11
CREATE OR REPLACE VIEW V_MED_FILE_ORPHANS AS
SELECT ID, NSS, NAME, FILE_TYPE, SOURCE_ID, MIGRATED_AT
FROM   MED_FILE
WHERE  URL_B64 IS NULL OR DBMS_LOB.GETLENGTH(URL_B64) = 0;
/

-- 7c. Estado de lotes
CREATE OR REPLACE VIEW V_MED_FILE_MIG_STATUS AS
SELECT PHASE, STATUS, COUNT(*) AS LOTES,
       SUM(ROWS_EXPECTED) AS FILAS_ESPERADAS, SUM(ROWS_DONE) AS FILAS_HECHAS
FROM  MED_FILE_MIG_LOG
GROUP BY PHASE, STATUS;
/

-- =============================================================================
-- BLOQUE 8: VALIDACIÓN POST-MIGRACIÓN (comparar contra MariaDB)
-- =============================================================================
-- ① Total:  Oracle SELECT COUNT(*) FROM MED_FILE;  vs  MariaDB SELECT COUNT(*) FROM files;
-- ② Estado: SELECT * FROM V_MED_FILE_MIG_STATUS;  (sin ERROR/RUNNING)
-- ③ Tipos:  SELECT * FROM V_MED_FILE_BY_TYPE;
-- ④ Huérfanos: SELECT COUNT(*) FROM V_MED_FILE_ORPHANS;   (esperado ~11)
-- ⑤ Decode pendiente: SELECT COUNT(*) FROM MED_FILE WHERE CONTENT_BLOB IS NULL AND URL_B64 IS NOT NULL;
-- ⑥ Integridad SOURCE_ID (requiere DB Link):
--    SELECT COUNT(*) FROM (SELECT id FROM files@MARIADB_LINK
--                          MINUS SELECT SOURCE_ID FROM MED_FILE);  -- debe ser 0
-- ⑦ Sanidad binario: SELECT ID, SIZE_BYTES FROM MED_FILE
--    WHERE CONTENT_BLOB IS NOT NULL AND SIZE_BYTES < 100;  -- PDFs sospechosamente chicos

-- =============================================================================
-- BLOQUE 9: NOTAS
-- =============================================================================
-- [NOTA-1] ENCODING DE `name`
--   ~0.4% de files.name tiene tildes dobles-codificadas (latin1/utf8). Corregir
--   al EXPORTAR (--default-character-set=utf8mb4). Post-fix opcional en Oracle:
--   UPDATE MED_FILE SET NAME = CONVERT(NAME,'UTF8','WE8ISO8859P1') WHERE ...;
--   (validar caso por caso; no aplicar a ciegas.)
--
-- [NOTA-2] BLOB vs base64
--   URL_B64 es el landing fiel. CONTENT_BLOB ahorra ~33%. Tras validar el
--   decode, para recuperar espacio: UPDATE MED_FILE SET URL_B64 = NULL
--   WHERE CONTENT_BLOB IS NOT NULL;  (¡solo tras respaldo y validación!)
--
-- [NOTA-3] files.type = hash MD5 (~9.4%)
--   Origen a confirmar en el PHP. En el detalle de consulta, los adjuntos se
--   buscan por  type = consulta_relacionada  → esos hashes son la relación
--   consulta↔archivo. Conservar FILE_TYPE tal cual (no normalizar aún).
--
-- [NOTA-4] Integración con Java (U04 adjuntos)
--   El detalle de consulta (fragments/consulta-detalle.html) tiene el bloque de
--   adjuntos como placeholder. Al validar MED_FILE, exponer un endpoint que lea
--   MED_FILE WHERE FILE_TYPE = :consultaRelacionada y sirva CONTENT_BLOB como PDF.
--
-- [NOTA-5] APP_FS_FILE
--   La arquitectura define APP_FS_FILE (metadatos + binario en filesystem). MED_FILE
--   es la capa de aterrizaje del legacy. Mapear MED_FILE → APP_FS_FILE (mover binario
--   a filesystem + metadatos) es una fase posterior si se adopta ese modelo.
-- =============================================================================
-- FIN DEL SCRIPT
-- =============================================================================
