-- =============================================================================
-- Notificaciones del portal (campanita del encabezado + aviso de escritorio).
-- Aplicar en la BASE DEL PORTAL (tablas SERV_MED_* dentro de BIOMETRICO), NO en ORDS.
--
-- Primer uso: la solicitud de examen medico inicial que mandara el sistema OCR
-- (docs/integracion-ocr-examen-inicial.md). La tabla es generica: cualquier modulo
-- puede crear una fila y la ve quien tenga acceso al menu DESTINO_MENU_CODE (o el
-- usuario DESTINO_USUARIO). Leida = compartida: en cuanto un medico la abre, se
-- marca para todos (la lista de pendientes del modulo es la fuente de verdad, la
-- notificacion solo avisa).
-- =============================================================================
SET SERVEROUTPUT ON;
-- Los enlaces llevan "&" (nss?nss=...&abrir=...): sin esto SQL Developer / SQL*Plus los toma
-- como variables de sustitucion y pide valores.
SET DEFINE OFF;

BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE SERV_MED_NOTIFICACION (
      ID                 NUMBER GENERATED BY DEFAULT AS IDENTITY
                         CONSTRAINT SERV_MED_PK_NOTIFICACION PRIMARY KEY,
      TIPO               VARCHAR2(40)  NOT NULL,          -- EXAMEN_INICIAL_SOLICITUD, ...
      TITULO             VARCHAR2(200) NOT NULL,
      MENSAJE            VARCHAR2(1000),
      NSS                VARCHAR2(50),
      ENLACE             VARCHAR2(400),                   -- ruta relativa al portal (nss?nss=...&abrir=examen-inicial)
      DESTINO_MENU_CODE  VARCHAR2(120),                   -- la ven los roles con ese menu (SERV_MED_MENU.CODE)
      DESTINO_USUARIO    VARCHAR2(100),                   -- o un usuario concreto
      ORIGEN             VARCHAR2(60),                    -- OCR, PORTAL, ...
      REFERENCIA         VARCHAR2(120),                   -- id externo (p.ej. referenciaOcr)
      CREATED_AT         TIMESTAMP(6)  DEFAULT SYSTIMESTAMP NOT NULL,
      CREATED_BY         VARCHAR2(100),
      LEIDA_AT           TIMESTAMP(6),
      LEIDA_POR          VARCHAR2(100)
    )
  ]';
  DBMS_OUTPUT.PUT_LINE('SERV_MED_NOTIFICACION creada');
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX SERV_MED_IX_NOTIF_PEND ON SERV_MED_NOTIFICACION (LEIDA_AT, CREATED_AT)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
/

-- Para probar la campanita sin OCR: una notificacion de ejemplo para quien tenga el menu
-- EXAMEN_INICIAL, sobre el NSS de pruebas. Borrarla despues o marcarla leida desde el portal.
-- INSERT INTO SERV_MED_NOTIFICACION (TIPO, TITULO, MENSAJE, NSS, ENLACE, DESTINO_MENU_CODE, ORIGEN, REFERENCIA, CREATED_BY)
-- VALUES ('EXAMEN_INICIAL_SOLICITUD', 'Examen médico inicial pendiente',
--         'OCR solicita examen inicial de MIGUEL MALDONADO CLEMENTE (cita 06/10/2026)',
--         '30048315698', 'nss?nss=30048315698&abrir=examen-inicial', 'EXAMEN_INICIAL', 'OCR', 'OCR-2026-000123', 'PRUEBA');
-- COMMIT;
