-- =============================================================================
-- MIGRACIÓN: servicioMedico.tags (MariaDB) → MED_TAG (Oracle 21c)
-- =============================================================================
-- Proyecto   : Portal Salud — portalsalud-personal
-- Origen     : MariaDB · servicioMedico.tags
-- Destino    : Oracle 21c · MED_TAG
-- Autor      : Agente IA (Claude) + revisión Tech Lead
-- Fecha      : 2026-06-29
-- Versión    : V2  (Flyway-compatible)
--
-- ALCANCE DE ESTE SCRIPT
-- ──────────────────────
-- Solo cubre la tabla `tags`. La tabla `files` NO se migra aquí porque
-- el módulo APP_FS_FILE del proyecto Java ya gestiona almacenamiento de
-- archivos (metadatos en Oracle + archivo físico en filesystem).
-- El ETL de files → APP_FS_FILE es un proceso separado.
--
-- CONTEXTO DE LA TABLA ORIGEN
-- ────────────────────────────
-- Schema real confirmado en MariaDB:
--
--   tags
--   ├── id       int(255)      PK AUTO_INCREMENT  NOT NULL
--   ├── nss      varchar(255)  NULL
--   ├── type     varchar(50)   NULL
--   └── content  longtext      NULL
--
-- Patrón de uso: EAV (Entity-Attribute-Value)
--   · nss     → NSS del empleado/paciente
--   · type    → nombre del campo del formulario médico (137 valores distintos)
--   · content → valor del campo (texto libre, JSON o base64 para firma digital)
--
-- Comportamiento del PHP (crítico para migración):
--   · Cada guardado hace DELETE + INSERT (no UPDATE)
--   · Pueden existir múltiples filas con mismo nss+type (versiones)
--   · El PHP siempre lee: ORDER BY id DESC LIMIT 1  (el más reciente)
--   · Algunos content son base64 de firma digital → candidatos a APP_FS_FILE
--     pero eso se decide en una fase posterior, no aquí
--
-- DECISIÓN DE DISEÑO
-- ───────────────────
-- Se migra como EAV fiel (copia exacta de la estructura) sin normalizar.
-- La normalización (MED_PRETEST, MED_EXAMEN_FISICO, etc.) ocurrirá en una
-- fase posterior, leyendo desde MED_TAG ya en Oracle.
-- Esto garantiza cero pérdida de datos: MariaDB.tags → MED_TAG es una copia
-- completa antes de cualquier transformación.
--
-- GRUPOS FUNCIONALES identificados en código PHP (137 tipos):
--   PRETEST          → campos del pre-test de ingreso (*PRETEST)
--   EXAMEN_FISICO    → audiometría, agudeza visual, SpO2, Romberg, etc.
--   CONTACTO_EMER    → hasta 3 contactos de emergencia
--   HISTORIA_LABORAL → hasta 4 empleos anteriores
--   VACUNAS          → fechaINFLUEN y similares
--   FIRMA_DIGITAL    → drawdataUrlPRETEST (base64 canvas)
--   PERMISO_EXAMEN   → checkExamPermiso, tipoExamenInputO
--   CLINICO_MISC     → CCA, DIENTE_2, Drenaje, ciruOBS, pension, etc.
-- =============================================================================


-- =============================================================================
-- BLOQUE 1: TABLA DESTINO MED_TAG
-- =============================================================================
BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE MED_TAG (

      -- Clave primaria
      ID            NUMBER
                    GENERATED BY DEFAULT AS IDENTITY
                    START WITH 1 INCREMENT BY 1
                    CONSTRAINT PK_MED_TAG PRIMARY KEY,

      -- Datos de negocio (mapeo directo de tags legacy)
      NSS           VARCHAR2(255),           -- tags.nss  (nullable conservado del origen)
      TYPE          VARCHAR2(120) NOT NULL,  -- tags.type (ampliado de 50 → 120 por seguridad)
      CONTENT       CLOB,                    -- tags.content (longtext → CLOB, hasta 4 GB)

      -- Columna derivada: grupo funcional para queries y futura normalización
      -- Se puebla automáticamente vía FN_MED_TAG_GROUP durante la migración
      TAG_GROUP     VARCHAR2(60),

      -- Trazabilidad de origen (no tocar después de migración)
      SOURCE_ID     NUMBER,                  -- tags.id original en MariaDB
      MIGRATED_AT   TIMESTAMP(6) DEFAULT SYSTIMESTAMP,

      -- Auditoría estándar
      CREATED_AT    TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
      CREATED_BY    VARCHAR2(100) DEFAULT 'MIGRATION'  NOT NULL,
      UPDATED_AT    TIMESTAMP(6),
      UPDATED_BY    VARCHAR2(100)
    )
  ]';
  DBMS_OUTPUT.PUT_LINE('[OK] Tabla MED_TAG creada.');
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE = -955 THEN
      DBMS_OUTPUT.PUT_LINE('[SKIP] Tabla MED_TAG ya existe — sin cambios.');
    ELSE
      RAISE;
    END IF;
END;
/

-- Comentarios de columna
COMMENT ON TABLE  MED_TAG           IS 'EAV de formularios médicos — migrado desde MariaDB.servicioMedico.tags';
COMMENT ON COLUMN MED_TAG.NSS       IS 'NSS del empleado/paciente. NULL permitido por compatibilidad con origen.';
COMMENT ON COLUMN MED_TAG.TYPE      IS 'Nombre del atributo del formulario (137 valores distintos en legacy)';
COMMENT ON COLUMN MED_TAG.CONTENT   IS 'Valor del atributo. Puede ser texto, JSON o base64 (firma digital).';
COMMENT ON COLUMN MED_TAG.TAG_GROUP IS 'Grupo funcional derivado de TYPE. Facilita futura normalización.';
COMMENT ON COLUMN MED_TAG.SOURCE_ID IS 'ID original en MariaDB.tags. Permite reconciliación y rollback.';
/


-- =============================================================================
-- BLOQUE 2: ÍNDICES
-- Basados en los patrones de acceso reales del PHP:
--   SELECT * FROM tags WHERE nss=? AND type=? ORDER BY id DESC LIMIT 1
-- =============================================================================

-- Acceso principal: por NSS + TYPE (el más usado)
BEGIN
  EXECUTE IMMEDIATE
    'CREATE INDEX IDX_MED_TAG_NSS_TYPE
     ON MED_TAG (NSS, TYPE)';
  DBMS_OUTPUT.PUT_LINE('[OK] Índice IDX_MED_TAG_NSS_TYPE creado.');
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE = -955 THEN
    DBMS_OUTPUT.PUT_LINE('[SKIP] IDX_MED_TAG_NSS_TYPE ya existe.');
  ELSE RAISE; END IF;
END;
/

-- Acceso por grupo funcional (para futura normalización por fases)
BEGIN
  EXECUTE IMMEDIATE
    'CREATE INDEX IDX_MED_TAG_NSS_GROUP
     ON MED_TAG (NSS, TAG_GROUP)';
  DBMS_OUTPUT.PUT_LINE('[OK] Índice IDX_MED_TAG_NSS_GROUP creado.');
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE = -955 THEN
    DBMS_OUTPUT.PUT_LINE('[SKIP] IDX_MED_TAG_NSS_GROUP ya existe.');
  ELSE RAISE; END IF;
END;
/

-- Trazabilidad: buscar por ID de origen para reconciliación
BEGIN
  EXECUTE IMMEDIATE
    'CREATE INDEX IDX_MED_TAG_SOURCE_ID
     ON MED_TAG (SOURCE_ID)';
  DBMS_OUTPUT.PUT_LINE('[OK] Índice IDX_MED_TAG_SOURCE_ID creado.');
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE = -955 THEN
    DBMS_OUTPUT.PUT_LINE('[SKIP] IDX_MED_TAG_SOURCE_ID ya existe.');
  ELSE RAISE; END IF;
END;
/


-- =============================================================================
-- BLOQUE 3: FUNCIÓN DE CLASIFICACIÓN FN_MED_TAG_GROUP
-- Clasifica el valor de TYPE en un grupo funcional.
-- DETERMINISTIC permite que Oracle la use en índices funcionales si se necesita.
-- Basada en los 137 tipos reales encontrados en el código PHP.
-- =============================================================================
CREATE OR REPLACE FUNCTION FN_MED_TAG_GROUP(p_type IN VARCHAR2)
RETURN VARCHAR2
DETERMINISTIC
IS
BEGIN
  -- Pre-Test de ingreso (sufijo *PRETEST en todos sus campos)
  IF p_type LIKE '%PRETEST%' THEN
    RETURN 'PRETEST';
  END IF;

  -- Firma digital (base64 de canvas HTML — candidato a APP_FS_FILE en fase futura)
  IF p_type = 'drawdataUrlPRETEST' THEN
    RETURN 'FIRMA_DIGITAL';
  END IF;

  -- Examen físico: audiometría OD/OI, agudeza visual, SpO2, Romberg, voz, traquea
  IF p_type IN (
    'ODAGAUDIINPEXP', 'ODCAEINPEXP', 'ODEXCAEEXFISINP',
    'ODEXFISINPCERC', 'ODEXFISINPCERCIZQ', 'ODMEMTIMINPEXP',
    'OIAGAUDIINPEXP', 'OICAEINPEXP',  'OIMEMTIMINPEXP',
    'LENTEOJODERECHOEXP', 'LENTEOJOIZQUIERDOEXP',
    'ROMBERGEXFIS', 'STPO2', 'VOZCLARAYFUERTE',
    'TRAQUEA_OBSINP', 'OBSGENERALINPEX'
  ) THEN
    RETURN 'EXAMEN_FISICO';
  END IF;

  -- Contactos de emergencia (prefijo contactoEmer*)
  IF p_type LIKE 'contactoEmer%' THEN
    RETURN 'CONTACTO_EMERGENCIA';
  END IF;

  -- Historia laboral: hasta 4 empleos anteriores (sufijo 1..4)
  IF p_type IN (
    'nombre1',       'nombre2',       'nombre3',       'nombre4',
    'puesto1',       'puesto2',       'puesto3',       'puesto4',
    'giro1',         'giro2',         'giro3',         'giro4',
    'antiguedad1',   'antiguedad2',   'antiguedad3',   'antiguedad4',
    'salida1',       'salida2',       'salida3',       'salida4',
    'turno1',        'turno2',        'turno3',        'turno4',
    'riesgos1',      'riesgos2',      'riesgos3',      'riesgos4',
    'epp1',          'epp2',          'epp3',          'epp4',
    'observaciones1','observaciones2','observaciones3','observaciones4',
    'descripcion1',  'descripcion2',  'descripcion3',  'descripcion4',
    'cantidad_trabajos', 'edad_inicio_laborar'
  ) THEN
    RETURN 'HISTORIA_LABORAL';
  END IF;

  -- Vacunas / inmunizaciones
  IF p_type = 'fechaINFLUEN' THEN
    RETURN 'VACUNAS';
  END IF;

  -- Permisos de examen médico
  IF p_type IN ('checkExamPermiso', 'tipoExamenInputO') THEN
    RETURN 'PERMISO_EXAMEN';
  END IF;

  -- Incapacidades
  IF p_type LIKE '%INCAP%' OR p_type LIKE '%incap%' THEN
    RETURN 'INCAPACIDAD';
  END IF;

  -- Campos clínicos misceláneos
  IF p_type IN (
    'CCA', 'DIENTE_2', 'Drenaje', 'ciruOBS', 'pension',
    'cadaCuandoDep', 'cadaCuandoPasa'
  ) THEN
    RETURN 'CLINICO_MISC';
  END IF;

  -- Cualquier tipo no clasificado queda en OTRO para revisión posterior
  RETURN 'OTRO';

END FN_MED_TAG_GROUP;
/


-- =============================================================================
-- BLOQUE 4: TABLA DE CONTROL DE MIGRACIÓN POR LOTES
-- Registra el progreso de cada lote para poder reanudar si falla a medias.
-- =============================================================================
BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE MED_TAG_MIG_LOG (
      ID             NUMBER  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      BATCH_NO       NUMBER  NOT NULL,
      SOURCE_ID_FROM NUMBER  NOT NULL,
      SOURCE_ID_TO   NUMBER  NOT NULL,
      ROWS_EXPECTED  NUMBER,
      ROWS_INSERTED  NUMBER,
      STATUS         VARCHAR2(20) DEFAULT 'PENDING' NOT NULL,
                     -- PENDING | RUNNING | DONE | ERROR | DRY-RUN
      STARTED_AT     TIMESTAMP(6),
      FINISHED_AT    TIMESTAMP(6),
      ERROR_MSG      VARCHAR2(4000)
    )
  ]';
  DBMS_OUTPUT.PUT_LINE('[OK] Tabla MED_TAG_MIG_LOG creada.');
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE = -955 THEN
    DBMS_OUTPUT.PUT_LINE('[SKIP] MED_TAG_MIG_LOG ya existe.');
  ELSE RAISE; END IF;
END;
/


-- =============================================================================
-- BLOQUE 5: PROCEDIMIENTO DE MIGRACIÓN SP_MIGRATE_TAGS
--
-- MODO DE USO:
--   -- Primero correr en dry-run para validar conteos sin insertar:
--   EXEC SP_MIGRATE_TAGS(p_dry_run => 'S');
--
--   -- Luego correr la migración real en lotes de 500 (ajustar según volumen):
--   EXEC SP_MIGRATE_TAGS(p_batch_size => 500, p_dry_run => 'N');
--
-- PREREQUISITO:
--   Requiere Database Link desde Oracle hacia MariaDB llamado MARIADB_LINK.
--   Si no existe DB Link ver BLOQUE 6 (alternativa ETL externo).
-- =============================================================================
CREATE OR REPLACE PROCEDURE SP_MIGRATE_TAGS (
  p_batch_size  IN NUMBER DEFAULT 500,
  p_dry_run     IN CHAR   DEFAULT 'N'   -- 'S' = solo cuenta, no inserta
)
IS
  -- Cursor sobre DB Link a MariaDB
  -- Solo trae registros que aún no existen en Oracle (reanudable)
  CURSOR c_tags IS
    SELECT id, nss, type, content
    FROM   tags@MARIADB_LINK
    WHERE  id NOT IN (
             SELECT SOURCE_ID
             FROM   MED_TAG
             WHERE  SOURCE_ID IS NOT NULL
           )
    ORDER BY id ASC;

  TYPE t_ids      IS TABLE OF NUMBER;
  TYPE t_nss      IS TABLE OF VARCHAR2(255);
  TYPE t_types    IS TABLE OF VARCHAR2(120);
  TYPE t_contents IS TABLE OF CLOB;

  v_ids      t_ids;
  v_nss      t_nss;
  v_types    t_types;
  v_contents t_contents;

  v_batch_no   NUMBER := 1;
  v_total_ins  NUMBER := 0;
  v_batch_ins  NUMBER := 0;
  v_id_from    NUMBER;
  v_id_to      NUMBER;

BEGIN
  DBMS_OUTPUT.PUT_LINE('════════════════════════════════════════════');
  DBMS_OUTPUT.PUT_LINE('SP_MIGRATE_TAGS — inicio: ' ||
                       TO_CHAR(SYSTIMESTAMP,'YYYY-MM-DD HH24:MI:SS'));
  DBMS_OUTPUT.PUT_LINE('Modo    : ' ||
                       CASE p_dry_run WHEN 'S' THEN 'DRY-RUN (solo conteo)'
                                      ELSE 'REAL (insertando en Oracle)' END);
  DBMS_OUTPUT.PUT_LINE('Lote    : ' || p_batch_size || ' filas');
  DBMS_OUTPUT.PUT_LINE('════════════════════════════════════════════');

  OPEN c_tags;
  LOOP
    FETCH c_tags
    BULK COLLECT INTO v_ids, v_nss, v_types, v_contents
    LIMIT p_batch_size;

    EXIT WHEN v_ids.COUNT = 0;

    v_id_from := v_ids(1);
    v_id_to   := v_ids(v_ids.LAST);

    -- Registrar inicio de lote
    INSERT INTO MED_TAG_MIG_LOG
      (BATCH_NO, SOURCE_ID_FROM, SOURCE_ID_TO,
       ROWS_EXPECTED, STATUS, STARTED_AT)
    VALUES
      (v_batch_no, v_id_from, v_id_to,
       v_ids.COUNT, 'RUNNING', SYSTIMESTAMP);
    COMMIT;

    IF p_dry_run = 'N' THEN
      BEGIN
        -- Inserción masiva con clasificación automática de TAG_GROUP
        FORALL i IN 1..v_ids.COUNT
          INSERT INTO MED_TAG (
            NSS, TYPE, CONTENT, TAG_GROUP,
            SOURCE_ID,   MIGRATED_AT,
            CREATED_AT,  CREATED_BY
          ) VALUES (
            v_nss(i),
            v_types(i),
            v_contents(i),
            FN_MED_TAG_GROUP(v_types(i)),  -- clasificación automática
            v_ids(i),
            SYSTIMESTAMP,
            SYSTIMESTAMP,
            'SP_MIGRATE_TAGS_V2'
          );

        v_batch_ins := SQL%ROWCOUNT;
        v_total_ins := v_total_ins + v_batch_ins;

        UPDATE MED_TAG_MIG_LOG
        SET    STATUS       = 'DONE',
               ROWS_INSERTED = v_batch_ins,
               FINISHED_AT  = SYSTIMESTAMP
        WHERE  BATCH_NO = v_batch_no AND STATUS = 'RUNNING';
        COMMIT;

        DBMS_OUTPUT.PUT_LINE('[LOTE ' || LPAD(v_batch_no,3) || ']' ||
                             ' IDs '   || v_id_from || ' → ' || v_id_to ||
                             ' | ins: ' || v_batch_ins);

      EXCEPTION WHEN OTHERS THEN
        ROLLBACK;
        UPDATE MED_TAG_MIG_LOG
        SET    STATUS      = 'ERROR',
               ERROR_MSG   = SUBSTR(SQLERRM, 1, 4000),
               FINISHED_AT = SYSTIMESTAMP
        WHERE  BATCH_NO = v_batch_no AND STATUS = 'RUNNING';
        COMMIT;
        DBMS_OUTPUT.PUT_LINE('[ERROR lote ' || v_batch_no || '] ' || SQLERRM);
        EXIT;  -- detener en primer error; relanzar desde el lote fallido
      END;

    ELSE
      -- Dry-run: solo reporta, no inserta
      UPDATE MED_TAG_MIG_LOG
      SET    STATUS       = 'DRY-RUN',
             ROWS_INSERTED = 0,
             FINISHED_AT  = SYSTIMESTAMP
      WHERE  BATCH_NO = v_batch_no AND STATUS = 'RUNNING';
      COMMIT;
      DBMS_OUTPUT.PUT_LINE('[DRY-RUN lote ' || LPAD(v_batch_no,3) || ']' ||
                           ' IDs ' || v_id_from || ' → ' || v_id_to ||
                           ' | filas: ' || v_ids.COUNT);
    END IF;

    v_batch_no := v_batch_no + 1;
  END LOOP;

  CLOSE c_tags;

  DBMS_OUTPUT.PUT_LINE('════════════════════════════════════════════');
  DBMS_OUTPUT.PUT_LINE('Total insertados : ' || v_total_ins);
  DBMS_OUTPUT.PUT_LINE('Fin              : ' ||
                       TO_CHAR(SYSTIMESTAMP,'YYYY-MM-DD HH24:MI:SS'));
  DBMS_OUTPUT.PUT_LINE('════════════════════════════════════════════');

END SP_MIGRATE_TAGS;
/


-- =============================================================================
-- BLOQUE 6: ALTERNATIVA SIN DB LINK (ETL externo)
-- Si no puedes crear un Database Link Oracle → MariaDB:
--
-- PASO A — Exportar desde MariaDB:
--   mysqldump -u root -p --no-create-info --complete-insert \
--     --where="1=1" servicioMedico tags > tags_data.sql
--
--   O en TSV para SQL*Loader:
--   mysql -u root -p servicioMedico \
--     -e "SELECT id, nss, type, content FROM tags ORDER BY id" \
--     --batch --silent > tags_export.tsv
--
-- PASO B — Cada fila debe insertarse en Oracle así:
--   INSERT INTO MED_TAG
--     (NSS, TYPE, CONTENT, TAG_GROUP, SOURCE_ID, MIGRATED_AT, CREATED_AT, CREATED_BY)
--   VALUES
--     (:nss, :type, :content,
--      FN_MED_TAG_GROUP(:type),
--      :source_id, SYSTIMESTAMP, SYSTIMESTAMP, 'ETL_EXTERNAL');
--
-- Herramientas compatibles: SQL*Loader, DBeaver ETL, Apache Hop, Kettle/PDI.
-- =============================================================================


-- =============================================================================
-- BLOQUE 7: VISTAS DE RECONCILIACIÓN
-- Ejecutar DESPUÉS de SP_MIGRATE_TAGS para validar integridad.
-- =============================================================================

-- 7a. Resumen por grupo funcional
CREATE OR REPLACE VIEW V_MED_TAG_BY_GROUP AS
SELECT
  TAG_GROUP,
  COUNT(*)             AS TOTAL_FILAS,
  COUNT(DISTINCT NSS)  AS TOTAL_NSS,
  COUNT(DISTINCT TYPE) AS TOTAL_TIPOS
FROM  MED_TAG
GROUP BY TAG_GROUP
ORDER BY TOTAL_FILAS DESC;
/

-- 7b. Último valor por NSS+TYPE
--     Replica el comportamiento PHP: ORDER BY id DESC LIMIT 1
--     Úsala desde Java en lugar de consultar directamente MED_TAG
CREATE OR REPLACE VIEW V_MED_TAG_LATEST AS
SELECT DISTINCT
  NSS,
  TYPE,
  TAG_GROUP,
  FIRST_VALUE(CONTENT) OVER (
    PARTITION BY NSS, TYPE
    ORDER BY ID DESC
    ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING
  ) AS CONTENT,
  FIRST_VALUE(ID) OVER (
    PARTITION BY NSS, TYPE
    ORDER BY ID DESC
    ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING
  ) AS LAST_ID
FROM MED_TAG;
/

-- 7c. Registros sin NSS (huérfanos del legacy)
CREATE OR REPLACE VIEW V_MED_TAG_ORPHANS AS
SELECT ID, TYPE, TAG_GROUP, SOURCE_ID, MIGRATED_AT
FROM   MED_TAG
WHERE  NSS IS NULL OR TRIM(NSS) IS NULL;
/

-- 7d. Estado de lotes de migración
CREATE OR REPLACE VIEW V_MED_TAG_MIG_STATUS AS
SELECT
  STATUS,
  COUNT(*)          AS LOTES,
  SUM(ROWS_EXPECTED) AS FILAS_ESPERADAS,
  SUM(ROWS_INSERTED) AS FILAS_INSERTADAS
FROM  MED_TAG_MIG_LOG
GROUP BY STATUS;
/


-- =============================================================================
-- BLOQUE 8: QUERIES DE VALIDACIÓN POST-MIGRACIÓN
-- Ejecutar manualmente y comparar resultados con MariaDB.
-- =============================================================================

-- ① Total migrado vs origen
--    Oracle : SELECT COUNT(*) FROM MED_TAG;
--    MariaDB: SELECT COUNT(*) FROM tags;
--    → Deben ser iguales

-- ② Estado de lotes
--    SELECT * FROM V_MED_TAG_MIG_STATUS;
--    → STATUS debe ser solo 'DONE' o 'DRY-RUN', ningún 'ERROR' o 'RUNNING'

-- ③ Distribución por grupo funcional
--    SELECT * FROM V_MED_TAG_BY_GROUP;

-- ④ Huérfanos (nss nulo en origen)
--    SELECT COUNT(*) FROM V_MED_TAG_ORPHANS;

-- ⑤ Tipos no clasificados (caen en OTRO — revisar si hay tipos nuevos en prod)
--    SELECT DISTINCT TYPE FROM MED_TAG WHERE TAG_GROUP = 'OTRO' ORDER BY TYPE;

-- ⑥ Verificar que ningún SOURCE_ID del origen falte en Oracle
--    (requiere DB Link activo)
--    SELECT COUNT(*) AS FALTANTES
--    FROM  (SELECT id FROM tags@MARIADB_LINK
--           MINUS
--           SELECT SOURCE_ID FROM MED_TAG WHERE SOURCE_ID IS NOT NULL);
--    → Debe ser 0

-- ⑦ Muestra de datos por grupo para revisión manual
--    SELECT NSS, TYPE, SUBSTR(CONTENT,1,80) AS PREVIEW
--    FROM   V_MED_TAG_LATEST
--    WHERE  TAG_GROUP = 'PRETEST'
--    AND    ROWNUM   <= 10;


-- =============================================================================
-- BLOQUE 9: NOTAS PARA EL EQUIPO
-- =============================================================================
--
-- [NOTA-1] SCOPE
--   Este script solo crea el esquema y migra datos de `tags`.
--   La tabla `files` queda fuera porque APP_FS_FILE en Java ya maneja
--   almacenamiento de archivos. El ETL de files es un proceso separado.
--
-- [NOTA-2] DEUDA TÉCNICA DOCUMENTADA
--   NSS y TYPE admiten NULL en Oracle por compatibilidad con el origen.
--   Evaluar NOT NULL en sprint de hardening después de validar datos.
--
-- [NOTA-3] NORMALIZACIÓN FUTURA
--   MED_TAG es la capa de aterrizaje segura. En una fase posterior se
--   crearán MED_PRETEST, MED_EXAMEN_FISICO, etc. leyendo desde MED_TAG.
--   No hacer esa normalización hasta que MED_TAG esté validado en producción.
--
-- [NOTA-4] FIRMA DIGITAL
--   Los registros con TAG_GROUP = 'FIRMA_DIGITAL' contienen base64 de
--   la firma del paciente. En fase futura migrar a APP_FS_FILE.
--   Por ahora se quedan en MED_TAG.CONTENT (CLOB soporta el tamaño).
--
-- [NOTA-5] PATRÓN DELETE+INSERT del PHP
--   El PHP nunca hace UPDATE — siempre DELETE+INSERT por campo.
--   MED_TAG conserva todo el historial porque SOURCE_ID evita duplicados
--   al relanzar SP_MIGRATE_TAGS. La vista V_MED_TAG_LATEST replica el
--   comportamiento legacy para el código Java que consuma estos datos.
--
-- =============================================================================
-- FIN DEL SCRIPT
-- =============================================================================
