-- =============================================================================
-- MATERNIDAD — SEGUIMIENTO — DDL + handlers ORDS
-- =============================================================================
-- Destino : instancia Oracle que respalda el WS ORDS real (security/Servcio/*,
--           http://10.249.249.3/biows/ords/security) — misma instancia donde
--           viven SERV_MED_ACCIDENTE, SERV_MED_RESULTADO_EXAMEN_HIST, etc.
-- Fecha   : 21 de agosto de 2026
-- Motivo  : "Maternidad — seguimiento completo" se re-diseñó como tabla dedicada
--           en vez de EAV sobre SERV_MED_TAG — "seguimiento" implica historial a lo
--           largo del embarazo (semanas que avanzan, próxima revisión, varios
--           chequeos); el patrón SERV_MED_TAG "ultimo valor por campo" pierde ese
--           historial en cada guardado nuevo. Mismo patrón que
--           SERV_MED_RESULTADO_EXAMEN_HIST/SERV_MED_ACCIDENTE: cada alta es
--           un registro nuevo (un chequeo), no un upsert que pisa el anterior.
-- Campos  : definidos en docs/ONEST_Proyecto_Salud_Ocupacional_Decisiones.pdf §7
--           (fecha de registro, semanas de gestación, fecha probable de parto,
--           restricciones laborales, próxima revisión, observaciones, estatus,
--           incapacidad, reincorporación). RESTRICCIONES_LABORALES e
--           INCAPACIDAD quedan como texto libre (nota/referencia) — no hay
--           todavía un catálogo real de restricciones ni un vínculo formal a
--           TBL_SERV_INCAPACIDAD_MEDICA, no se inventa esa integración aquí.
--
-- Como aplicar los handlers: igual que docs/ords-accidentes.sql (SQL Developer
-- > conexión > RESTful Services > módulo "Servcio" > New Template "maternidad"
-- / "consulta_maternidad" > New Handler POST, Source Type PL/SQL).
-- =============================================================================


-- =============================================================================
-- BLOQUE 1: TABLA SERV_MED_MATERNIDAD_SEGUIMIENTO
-- =============================================================================
BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE SERV_MED_MATERNIDAD_SEGUIMIENTO (
      REG_ID                    NUMBER GENERATED BY DEFAULT AS IDENTITY START WITH 1 INCREMENT BY 1
                                 CONSTRAINT PK_SERV_MED_MATERNIDAD PRIMARY KEY,
      NSS                       VARCHAR2(13) NOT NULL,
      FECHA_REGISTRO            DATE DEFAULT SYSDATE NOT NULL,
      SEMANAS_GESTACION         NUMBER,
      FECHA_PROBABLE_PARTO      DATE,
      RESTRICCIONES_LABORALES   VARCHAR2(500),
      PROXIMA_REVISION          DATE,
      OBSERVACIONES             VARCHAR2(500),
      ESTATUS                   VARCHAR2(30),   -- texto libre, sin catalogo cerrado (ej. ACTIVO/CERRADO)
      INCAPACIDAD               VARCHAR2(100),  -- nota/referencia libre, sin FK a TBL_SERV_INCAPACIDAD_MEDICA
      REINCORPORACION           DATE,
      ID_USUARIO                VARCHAR2(50),
      NOMBRE_USUARIO            VARCHAR2(100)
    )
  ]';
EXCEPTION WHEN OTHERS THEN IF SQLCODE = -955 THEN NULL; ELSE RAISE; END IF;
END;
/

BEGIN EXECUTE IMMEDIATE 'CREATE INDEX IDX_SERV_MED_MATERNIDAD_NSS ON SERV_MED_MATERNIDAD_SEGUIMIENTO (NSS)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE = -955 THEN NULL; ELSE RAISE; END IF; END;
/

COMMENT ON TABLE SERV_MED_MATERNIDAD_SEGUIMIENTO IS 'Seguimiento de maternidad, un registro por chequeo/revision (no upsert). Campos definidos en ONEST_Proyecto_Salud_Ocupacional_Decisiones.pdf paragrafo 7, aplicado 21-ago-2026.';
/


-- =============================================================================
-- BLOQUE 2: HANDLER ORDS — POST /Servcio/maternidad (alta de un chequeo)
-- Mismo patron que security/Servcio/accidente (docs/ords-accidentes.sql).
-- Pegar completo como "Source" del handler POST.
-- =============================================================================
declare

l_response_body_clob  clob ;
l_response_length     NUMBER;
l_response_buffer     VARCHAR2(32767);
l_response_chunk_size BINARY_INTEGER := 32000;
l_offset              INTEGER := 1;
j apex_json.t_values;
kjson clob;
kclob clob;
KNNS VARCHAR2(13);
ksemanasgestacion number;
kfechaprobableparto varchar2(20);
krestriccioneslaborales varchar2(500);
kproximarevision varchar2(20);
kobservaciones varchar2(500);
kestatus varchar2(30);
kincapacidad varchar2(100);
kreincorporacion varchar2(20);
kidusuario varchar2(50);
knombreusuario varchar2(100);

begin
kclob:= utl_raw.cast_to_varchar2(:body);
apex_json.parse(j,kclob);

knns                    := apex_json.get_varchar2(p_path=>'NSS',p_values=>j);
ksemanasgestacion       := apex_json.get_number(p_path=>'SEMANAS_GESTACION',p_values=>j);
kfechaprobableparto     := apex_json.get_varchar2(p_path=>'FECHA_PROBABLE_PARTO',p_values=>j);
krestriccioneslaborales := apex_json.get_varchar2(p_path=>'RESTRICCIONES_LABORALES',p_values=>j);
kproximarevision        := apex_json.get_varchar2(p_path=>'PROXIMA_REVISION',p_values=>j);
kobservaciones          := apex_json.get_varchar2(p_path=>'OBSERVACIONES',p_values=>j);
kestatus                := apex_json.get_varchar2(p_path=>'ESTATUS',p_values=>j);
kincapacidad            := apex_json.get_varchar2(p_path=>'INCAPACIDAD',p_values=>j);
kreincorporacion        := apex_json.get_varchar2(p_path=>'REINCORPORACION',p_values=>j);
kidusuario              := apex_json.get_varchar2(p_path=>'USUARIO_ID',p_values=>j);
knombreusuario          := apex_json.get_varchar2(p_path=>'NOMBRE_USUARIO',p_values=>j);

insert into SERV_MED_MATERNIDAD_SEGUIMIENTO(
  NSS, SEMANAS_GESTACION, FECHA_PROBABLE_PARTO, RESTRICCIONES_LABORALES,
  PROXIMA_REVISION, OBSERVACIONES, ESTATUS, INCAPACIDAD, REINCORPORACION,
  ID_USUARIO, NOMBRE_USUARIO)
values (knns, ksemanasgestacion,
  case when kfechaprobableparto is not null then to_date(kfechaprobableparto,'DD/MM/YYYY') end,
  krestriccioneslaborales,
  case when kproximarevision is not null then to_date(kproximarevision,'DD/MM/YYYY') end,
  kobservaciones, kestatus, kincapacidad,
  case when kreincorporacion is not null then to_date(kreincorporacion,'DD/MM/YYYY') end,
  kidusuario, knombreusuario);

commit;

APEX_JSON.initialize_clob_output;
   APEX_JSON.open_OBJECT;
    APEX_JSON.open_array('Datos');
   APEX_JSON.open_OBJECT;
      APEX_JSON.write('Proceso','Registro de seguimiento de maternidad procesado correctamente');
      APEX_JSON.write('Estado',100);
      APEX_JSON.write('Mensaje','Insercion correcta');
      APEX_JSON.write('Data','Proceso correcto');
   APEX_JSON.close_OBJECT;
  APEX_JSON.close_array;
 APEX_JSON.close_OBJECT;
kjson := APEX_JSON.get_clob_output;
APEX_JSON.free_output;

l_response_body_clob := kjson;
dbms_lob.open(l_response_body_clob, dbms_lob.lob_readonly);
l_response_length := dbms_lob.getlength (l_response_body_clob);

WHILE (l_response_length > 0)
 LOOP
    dbms_lob.read(l_response_body_clob, l_response_chunk_size, l_offset, l_response_buffer);
     htp.prn(l_response_buffer);
     l_offset := l_offset + l_response_chunk_size;
     l_response_length := l_response_length - l_response_chunk_size;
 END LOOP;

  dbms_lob.close(l_response_body_clob);

end;


-- =============================================================================
-- BLOQUE 3: HANDLER ORDS — POST /Servcio/consulta_maternidad (historial por NSS)
-- Mismo patron que security/Servcio/consulta_accidente (docs/ords-accidentes.sql).
-- Pegar completo como "Source" del handler POST.
-- =============================================================================
declare

l_response_body_clob  clob ;
l_response_length     NUMBER;
l_response_buffer     VARCHAR2(32767);
l_response_chunk_size BINARY_INTEGER := 32000;
l_offset              INTEGER := 1;
j apex_json.t_values;
kjson clob;
kclob clob;
kdata varchar2(250);
KEXISTE NUMBER;
KNNS VARCHAR2(13);

begin
kclob:= utl_raw.cast_to_varchar2(:body);
apex_json.parse(j,kclob);

knns  := apex_json.get_varchar2(p_path=>'NSS',p_values=>j);

select COUNT(*) into KEXISTE from SERV_MED_MATERNIDAD_SEGUIMIENTO where NSS=knns;

APEX_JSON.initialize_clob_output;
APEX_JSON.OPEN_OBJECT;

IF KEXISTE > 0 THEN
APEX_JSON.open_array('Datos');
for i in (select
REG_ID, FECHA_REGISTRO, SEMANAS_GESTACION, FECHA_PROBABLE_PARTO, RESTRICCIONES_LABORALES,
PROXIMA_REVISION, OBSERVACIONES, ESTATUS, INCAPACIDAD, REINCORPORACION, NOMBRE_USUARIO
from SERV_MED_MATERNIDAD_SEGUIMIENTO where NSS=knns order by FECHA_REGISTRO desc)
loop
  APEX_JSON.open_OBJECT;
    APEX_JSON.WRITE('id_registro',coalesce(i.reg_id,0));
    APEX_JSON.WRITE('fecha_registro',coalesce(to_char(i.fecha_registro,'DD/MM/YYYY'),'0'));
    APEX_JSON.WRITE('semanas_gestacion',coalesce(i.semanas_gestacion,0));
    APEX_JSON.WRITE('fecha_probable_parto',coalesce(to_char(i.fecha_probable_parto,'DD/MM/YYYY'),'0'));
    APEX_JSON.WRITE('restricciones_laborales',coalesce(i.restricciones_laborales,'0'));
    APEX_JSON.WRITE('proxima_revision',coalesce(to_char(i.proxima_revision,'DD/MM/YYYY'),'0'));
    APEX_JSON.WRITE('observaciones',coalesce(i.observaciones,'0'));
    APEX_JSON.WRITE('estatus',coalesce(i.estatus,'0'));
    APEX_JSON.WRITE('incapacidad',coalesce(i.incapacidad,'0'));
    APEX_JSON.WRITE('reincorporacion',coalesce(to_char(i.reincorporacion,'DD/MM/YYYY'),'0'));
    APEX_JSON.WRITE('usuario',coalesce(i.nombre_usuario,'0'));
  APEX_JSON.close_OBJECT;
end loop;
   APEX_JSON.CLOSE_array;
  APEX_JSON.close_OBJECT;
       kjson := APEX_JSON.get_clob_output;
    APEX_JSON.free_output;

ELSE
   APEX_JSON.initialize_clob_output;
            APEX_JSON.open_OBJECT;
             APEX_JSON.open_array('Datos');
            APEX_JSON.open_OBJECT;
               APEX_JSON.write('Proceso','consulta de maternidad por NSS');
               APEX_JSON.write('Estado',-100);
               APEX_JSON.write('Mensaje','No se tienen datos en la consulta');
               APEX_JSON.write('Data',kdata);
            APEX_JSON.close_OBJECT;
           APEX_JSON.close_array;
          APEX_JSON.close_OBJECT;
              kjson := APEX_JSON.get_clob_output;
    APEX_JSON.free_output;
END IF;

l_response_body_clob := kjson;
dbms_lob.open(l_response_body_clob, dbms_lob.lob_readonly);
l_response_length := dbms_lob.getlength (l_response_body_clob);

WHILE (l_response_length > 0)
 LOOP
    dbms_lob.read(l_response_body_clob, l_response_chunk_size, l_offset, l_response_buffer);
     htp.prn(l_response_buffer);
     l_offset := l_offset + l_response_chunk_size;
     l_response_length := l_response_length - l_response_chunk_size;
 END LOOP;

  dbms_lob.close(l_response_body_clob);

end;


-- =============================================================================
-- NOTAS
-- =============================================================================
-- [NOTA-1] "Estado":100 replica el patron de Servcio/accidente/incapacidades.
-- [NOTA-2] Fechas se reciben como texto 'DD/MM/YYYY' (mismo formato que el
--   resto del sistema) y se convierten con TO_DATE, solo si vienen no-nulas
--   (los 3 campos de fecha son opcionales - un chequeo temprano puede no
--   tener fecha probable de parto o proxima revision definidas aun).
-- [NOTA-3] RESTRICCIONES_LABORALES e INCAPACIDAD son texto libre a proposito -
--   no existe todavia un catalogo real de restricciones (ver tarea aparte
--   "Catalogo de restricciones medicas") ni una integracion formal con
--   TBL_SERV_INCAPACIDAD_MEDICA - no se inventa esa relacion aqui.
-- [NOTA-4] Cada alta es un registro NUEVO (un chequeo), nunca un UPDATE -
--   mismo criterio que SERV_MED_ACCIDENTE/SERV_MED_RESULTADO_EXAMEN_HIST -
--   preserva el historial completo del seguimiento del embarazo.
-- =============================================================================
