-- =============================================================================
-- ACCIDENTES DE TRABAJO — DDL + handlers ORDS
-- =============================================================================
-- Destino : instancia Oracle que respalda el WS ORDS real (security/Servcio/*,
--           http://10.249.249.3/biows/ords/security) — NO la BD local del
--           proyecto Java (PROYECTO_BASE_PDB) ni ONEWMS_QA (200.94.116.132),
--           son instancias distintas. Correr esto donde vive SERV_MED_*,
--           TBL_SERV_CONSULTA_MEDICA, TBL_SERV_INCAPACIDAD_MEDICA, etc.
-- Fecha   : 13 de agosto de 2026
-- Estado  : estructura de campos confirmada contra reportes reales
--           (6 REPORTE ACCIDENTABILIDAD 2026 AIFA.xls, via analisis de
--           salud-ocupacional-v2) - NO confirmada contra un DDL Oracle
--           existente, porque esta tabla no existe todavia. El FLUJO DE
--           INVESTIGACION (quien califica, criterio, plazos) sigue sin
--           definir (Gerente SO) - no bloquea esta captura basica.
--
-- Como aplicar los handlers: igual que docs/ords-antidoping.sql (SQL
-- Developer > conexion > RESTful Services > modulo "Servcio" > New Template
-- "accidente" / "consulta_accidente" > New Handler POST, Source Type PL/SQL).
-- =============================================================================


-- =============================================================================
-- BLOQUE 1: TABLA SERV_MED_ACCIDENTE
-- =============================================================================
BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE SERV_MED_ACCIDENTE (
      REG_ID              NUMBER GENERATED BY DEFAULT AS IDENTITY START WITH 1 INCREMENT BY 1
                          CONSTRAINT PK_SERV_MED_ACCIDENTE PRIMARY KEY,
      NSS                 VARCHAR2(13) NOT NULL,
      FECHA_REGISTRO      DATE DEFAULT SYSDATE NOT NULL,
      FECHA_ACCIDENTE     DATE,
      TIPO_RIESGO         VARCHAR2(20) NOT NULL,   -- LABORAL | TRAYECTO
      CAUSA_RT            VARCHAR2(30),            -- ACCID_VIAL/AGRESION_ASALTO/CAIDA/
                                                     -- GOLPE_DIRECTO/HERIDA/LESION_ERGONOMICA/OTRO_IMPROCEDENTE
      DIAGNOSTICO         VARCHAR2(500),            -- "DX IMSS", texto libre
      SDI                 NUMBER,                   -- Salario Diario Integrado
      STATUS_CALIFICACION VARCHAR2(30),             -- CALIFICADO|IMPROCEDENTE|PENDIENTE|BAJA_INCONCLUSO
      COSTO               NUMBER,
      OBSERVACIONES       VARCHAR2(500),
      ID_USUARIO          VARCHAR2(50),
      NOMBRE_USUARIO      VARCHAR2(100)
    )
  ]';
EXCEPTION WHEN OTHERS THEN IF SQLCODE = -955 THEN NULL; ELSE RAISE; END IF;
END;
/

BEGIN EXECUTE IMMEDIATE 'CREATE INDEX IDX_SERV_MED_ACCIDENTE_NSS ON SERV_MED_ACCIDENTE (NSS)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE = -955 THEN NULL; ELSE RAISE; END IF; END;
/

COMMENT ON TABLE SERV_MED_ACCIDENTE IS 'Accidente de trabajo (RT1/RT2). Estructura confirmada 2026-08-13 contra 6 REPORTE ACCIDENTABILIDAD 2026 AIFA.xls.';
/


-- =============================================================================
-- BLOQUE 2: HANDLER ORDS — POST /Servcio/accidente (alta)
-- Mismo patron que security/Servcio/incapacidades (docs/contextoWS.txt:1931).
-- Pegar completo como "Source" del handler POST.
-- =============================================================================
declare

l_response_body_clob  clob ;
l_response_length     NUMBER;
l_response_buffer     VARCHAR2(32767);
l_response_chunk_size BINARY_INTEGER := 32000;
l_offset              INTEGER := 1;
j apex_json.t_values;
kjson clob;
kclob clob;
KNNS VARCHAR2(13);
kfechaaccidente varchar2(20);
ktiporiesgo varchar2(20);
kcausart varchar2(30);
kdiagnostico varchar2(500);
ksdi number;
kstatuscalificacion varchar2(30);
kcosto number;
kobservaciones varchar2(500);
kidusuario varchar2(50);
knombreusuario varchar2(100);

begin
kclob:= utl_raw.cast_to_varchar2(:body);
apex_json.parse(j,kclob);

knns                := apex_json.get_varchar2(p_path=>'NSS',p_values=>j);
kfechaaccidente     := apex_json.get_varchar2(p_path=>'FECHA_ACCIDENTE',p_values=>j);
ktiporiesgo         := apex_json.get_varchar2(p_path=>'TIPO_RIESGO',p_values=>j);
kcausart            := apex_json.get_varchar2(p_path=>'CAUSA_RT',p_values=>j);
kdiagnostico        := apex_json.get_varchar2(p_path=>'DIAGNOSTICO',p_values=>j);
ksdi                := apex_json.get_number(p_path=>'SDI',p_values=>j);
kstatuscalificacion := apex_json.get_varchar2(p_path=>'STATUS_CALIFICACION',p_values=>j);
kcosto              := apex_json.get_number(p_path=>'COSTO',p_values=>j);
kobservaciones      := apex_json.get_varchar2(p_path=>'OBSERVACIONES',p_values=>j);
kidusuario          := apex_json.get_varchar2(p_path=>'USUARIO_ID',p_values=>j);
knombreusuario      := apex_json.get_varchar2(p_path=>'NOMBRE_USUARIO',p_values=>j);

insert into SERV_MED_ACCIDENTE(
  NSS, FECHA_ACCIDENTE, TIPO_RIESGO, CAUSA_RT, DIAGNOSTICO, SDI,
  STATUS_CALIFICACION, COSTO, OBSERVACIONES, ID_USUARIO, NOMBRE_USUARIO)
values (knns, to_date(kfechaaccidente,'DD/MM/YYYY'), ktiporiesgo, kcausart, kdiagnostico, ksdi,
  kstatuscalificacion, kcosto, kobservaciones, kidusuario, knombreusuario);

commit;

APEX_JSON.initialize_clob_output;
   APEX_JSON.open_OBJECT;
    APEX_JSON.open_array('Datos');
   APEX_JSON.open_OBJECT;
      APEX_JSON.write('Proceso','Registro de accidente procesado correctamente');
      APEX_JSON.write('Estado',100);
      APEX_JSON.write('Mensaje','Insercion correcta');
      APEX_JSON.write('Data','Proceso correcto');
   APEX_JSON.close_OBJECT;
  APEX_JSON.close_array;
 APEX_JSON.close_OBJECT;
kjson := APEX_JSON.get_clob_output;
APEX_JSON.free_output;

l_response_body_clob := kjson;
dbms_lob.open(l_response_body_clob, dbms_lob.lob_readonly);
l_response_length := dbms_lob.getlength (l_response_body_clob);

WHILE (l_response_length > 0)
 LOOP
    dbms_lob.read(l_response_body_clob, l_response_chunk_size, l_offset, l_response_buffer);
     htp.prn(l_response_buffer);
     l_offset := l_offset + l_response_chunk_size;
     l_response_length := l_response_length - l_response_chunk_size;
 END LOOP;

  dbms_lob.close(l_response_body_clob);

end;


-- =============================================================================
-- BLOQUE 3: HANDLER ORDS — POST /Servcio/consulta_accidente (lista por NSS)
-- Mismo patron que security/Servcio/consulta_incapacidad (docs/contextoWS.txt:2122).
-- Pegar completo como "Source" del handler POST.
-- =============================================================================
declare

l_response_body_clob  clob ;
l_response_length     NUMBER;
l_response_buffer     VARCHAR2(32767);
l_response_chunk_size BINARY_INTEGER := 32000;
l_offset              INTEGER := 1;
j apex_json.t_values;
kjson clob;
kclob clob;
kdata varchar2(250);
KEXISTE NUMBER;
KNNS VARCHAR2(13);

begin
kclob:= utl_raw.cast_to_varchar2(:body);
apex_json.parse(j,kclob);

knns  := apex_json.get_varchar2(p_path=>'NSS',p_values=>j);

select COUNT(*) into KEXISTE from SERV_MED_ACCIDENTE where NSS=knns;

APEX_JSON.initialize_clob_output;
APEX_JSON.OPEN_OBJECT;

IF KEXISTE > 0 THEN
APEX_JSON.open_array('Datos');
for i in (select
REG_ID, FECHA_REGISTRO, FECHA_ACCIDENTE, TIPO_RIESGO, CAUSA_RT, DIAGNOSTICO,
SDI, STATUS_CALIFICACION, COSTO, OBSERVACIONES, NOMBRE_USUARIO
from SERV_MED_ACCIDENTE where NSS=knns order by FECHA_ACCIDENTE desc)
loop
  APEX_JSON.open_OBJECT;
    APEX_JSON.WRITE('id_registro',coalesce(i.reg_id,0));
    APEX_JSON.WRITE('fecha_registro',coalesce(to_char(i.fecha_registro,'DD/MM/YYYY'),'0'));
    APEX_JSON.WRITE('fecha_accidente',coalesce(to_char(i.fecha_accidente,'DD/MM/YYYY'),'0'));
    APEX_JSON.WRITE('tipo_riesgo',coalesce(i.tipo_riesgo,'0'));
    APEX_JSON.WRITE('causa_rt',coalesce(i.causa_rt,'0'));
    APEX_JSON.WRITE('diagnostico',coalesce(i.diagnostico,'0'));
    APEX_JSON.WRITE('sdi',coalesce(i.sdi,0));
    APEX_JSON.WRITE('status_calificacion',coalesce(i.status_calificacion,'0'));
    APEX_JSON.WRITE('costo',coalesce(i.costo,0));
    APEX_JSON.WRITE('observaciones',coalesce(i.observaciones,'0'));
    APEX_JSON.WRITE('usuario',coalesce(i.nombre_usuario,'0'));
  APEX_JSON.close_OBJECT;
end loop;
   APEX_JSON.CLOSE_array;
  APEX_JSON.close_OBJECT;
       kjson := APEX_JSON.get_clob_output;
    APEX_JSON.free_output;

ELSE
   APEX_JSON.initialize_clob_output;
            APEX_JSON.open_OBJECT;
             APEX_JSON.open_array('Datos');
            APEX_JSON.open_OBJECT;
               APEX_JSON.write('Proceso','consulta de accidentes por NSS');
               APEX_JSON.write('Estado',-100);
               APEX_JSON.write('Mensaje','No se tienen datos en la consulta');
               APEX_JSON.write('Data',kdata);
            APEX_JSON.close_OBJECT;
           APEX_JSON.close_array;
          APEX_JSON.close_OBJECT;
              kjson := APEX_JSON.get_clob_output;
    APEX_JSON.free_output;
END IF;

l_response_body_clob := kjson;
dbms_lob.open(l_response_body_clob, dbms_lob.lob_readonly);
l_response_length := dbms_lob.getlength (l_response_body_clob);

WHILE (l_response_length > 0)
 LOOP
    dbms_lob.read(l_response_body_clob, l_response_chunk_size, l_offset, l_response_buffer);
     htp.prn(l_response_buffer);
     l_offset := l_offset + l_response_chunk_size;
     l_response_length := l_response_length - l_response_chunk_size;
 END LOOP;

  dbms_lob.close(l_response_body_clob);

end;


-- =============================================================================
-- NOTAS
-- =============================================================================
-- [NOTA-1] "Estado":100 replica el patron de Servcio/incapacidades documentado
--   en contextoWS.txt. Si al probar en vivo el WS real usa otra convencion
--   (ej. Estado:0, visto empiricamente en Servcio/Medico el 2026-08-13),
--   ajustar aqui para consistencia con el resto del sistema.
-- [NOTA-2] FECHA_ACCIDENTE se recibe como texto 'DD/MM/YYYY' (mismo formato
--   que el resto del sistema, ver FECHA_INICIO/FECHA_TERMINO de incapacidades)
--   y se convierte con TO_DATE - ajustar la mascara si el frontend Java manda
--   otro formato.
-- [NOTA-3] Catalogos usados (TIPO_RIESGO, CAUSA_RT, STATUS_CALIFICACION) NO
--   se validan con CHECK constraint a proposito - mismo criterio que el resto
--   del esquema existente (SERV_MED_*), que tampoco los valida a nivel BD.
-- =============================================================================
