-- =============================================================================
-- ACCIDENTES DE TRABAJO — SEGUIMIENTO DE CASOS
-- =============================================================================
-- Destino : misma instancia ORDS que security/Servcio/* (10.249.249.3) — NO la
--           BD local del proyecto Java ni ONEWMS_QA.
-- Fecha   : 24 de agosto de 2026
-- Alcance : dimensionado en docs/entregable-liberacion-stoppers-salud.html §3
--           (Registro → Seguimiento → Actualización → Evidencias → Cierre, SIN
--           motor de investigación). Esta tabla es la sub-lista de
--           actualizaciones/observaciones de UN accidente ya registrado en
--           SERV_MED_ACCIDENTE (docs/ords-accidentes.sql) — no reemplaza esa
--           tabla, la complementa.
-- Diseño  : se descartó EAV sobre SERV_MED_TAG (el patrón que proponía el plan
--           original) por la MISMA razón que Maternidad se rediseñó de EAV a
--           tabla dedicada: "Conservar historial de seguimiento" implica
--           VARIAS entradas por caso a lo largo del tiempo, y EAV solo guarda
--           el último valor por campo. Tabla dedicada, cada seguimiento es un
--           INSERT nuevo (nunca UPDATE) — mismo patrón que el resto del
--           esquema SERV_MED_*.
-- Estado  : NO hay columna ESTADO en SERV_MED_ACCIDENTE ni aquí — el estado
--           del caso (ABIERTO/CERRADO) se DERIVA del lado Java: cerrado si
--           existe al menos un seguimiento con TIPO='CIERRE' para ese
--           ACCIDENTE_REG_ID, abierto si no. Evita ser el primer UPDATE del
--           esquema (todo el resto es insert-only) y "cerrar" queda como
--           cualquier otro seguimiento, con su propia fecha/observación/usuario.
--
-- Como aplicar (SQL Developer > conexión > RESTful Services):
--   1. Dentro del módulo "Servcio" existente > New Template.
--   2. URI Template: "accidente_seguimiento" (alta) / "consulta_accidente_seguimiento" (lista).
--   3. New Handler > Method: POST, Source Type: PL/SQL. Pegar BLOQUE 2 / BLOQUE 3.
-- =============================================================================


-- =============================================================================
-- BLOQUE 1: TABLA SERV_MED_ACCIDENTE_SEGUIMIENTO
-- =============================================================================
BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE SERV_MED_ACCIDENTE_SEGUIMIENTO (
      REG_ID             NUMBER GENERATED BY DEFAULT AS IDENTITY START WITH 1 INCREMENT BY 1
                          CONSTRAINT PK_SERV_MED_ACC_SEGUIM PRIMARY KEY,
      ACCIDENTE_REG_ID   NUMBER NOT NULL
                          CONSTRAINT FK_ACC_SEGUIM_ACCIDENTE REFERENCES SERV_MED_ACCIDENTE(REG_ID),
      TIPO               VARCHAR2(20) NOT NULL,   -- SEGUIMIENTO | CIERRE
      FECHA_SEGUIMIENTO  DATE DEFAULT SYSDATE NOT NULL,
      OBSERVACIONES      VARCHAR2(1000) NOT NULL,
      ID_USUARIO         VARCHAR2(50),
      NOMBRE_USUARIO     VARCHAR2(100)
    )
  ]';
EXCEPTION WHEN OTHERS THEN IF SQLCODE = -955 THEN NULL; ELSE RAISE; END IF;
END;
/

BEGIN EXECUTE IMMEDIATE 'CREATE INDEX IDX_ACC_SEGUIM_ACCIDENTE ON SERV_MED_ACCIDENTE_SEGUIMIENTO (ACCIDENTE_REG_ID)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE = -955 THEN NULL; ELSE RAISE; END IF; END;
/

COMMENT ON TABLE SERV_MED_ACCIDENTE_SEGUIMIENTO IS 'Historial de seguimiento de un caso de SERV_MED_ACCIDENTE (insert-only). TIPO=CIERRE marca el cierre del caso. Aplicada 24-ago-2026.';
/


-- =============================================================================
-- BLOQUE 2: HANDLER ORDS — POST /Servcio/accidente_seguimiento (alta)
-- Pegar completo como "Source" del handler POST.
-- =============================================================================
declare

l_response_body_clob  clob ;
l_response_length     NUMBER;
l_response_buffer     VARCHAR2(32767);
l_response_chunk_size BINARY_INTEGER := 32000;
l_offset              INTEGER := 1;
j apex_json.t_values;
kjson clob;
kclob clob;
kaccidenteregid number;
ktipo varchar2(20);
kobservaciones varchar2(1000);
kidusuario varchar2(50);
knombreusuario varchar2(100);

begin
kclob:= utl_raw.cast_to_varchar2(:body);
apex_json.parse(j,kclob);

kaccidenteregid := apex_json.get_number(p_path=>'ACCIDENTE_REG_ID',p_values=>j);
ktipo           := apex_json.get_varchar2(p_path=>'TIPO',p_values=>j);
kobservaciones  := apex_json.get_varchar2(p_path=>'OBSERVACIONES',p_values=>j);
kidusuario      := apex_json.get_varchar2(p_path=>'USUARIO_ID',p_values=>j);
knombreusuario  := apex_json.get_varchar2(p_path=>'NOMBRE_USUARIO',p_values=>j);

insert into SERV_MED_ACCIDENTE_SEGUIMIENTO(ACCIDENTE_REG_ID, TIPO, OBSERVACIONES, ID_USUARIO, NOMBRE_USUARIO)
values (kaccidenteregid, ktipo, kobservaciones, kidusuario, knombreusuario);

commit;

APEX_JSON.initialize_clob_output;
   APEX_JSON.open_OBJECT;
    APEX_JSON.open_array('Datos');
   APEX_JSON.open_OBJECT;
      APEX_JSON.write('Proceso','Seguimiento registrado correctamente');
      APEX_JSON.write('Estado',100);
      APEX_JSON.write('Mensaje','Insercion correcta');
      APEX_JSON.write('Data','Proceso correcto');
   APEX_JSON.close_OBJECT;
  APEX_JSON.close_array;
 APEX_JSON.close_OBJECT;
kjson := APEX_JSON.get_clob_output;
APEX_JSON.free_output;

l_response_body_clob := kjson;
dbms_lob.open(l_response_body_clob, dbms_lob.lob_readonly);
l_response_length := dbms_lob.getlength (l_response_body_clob);

WHILE (l_response_length > 0)
 LOOP
    dbms_lob.read(l_response_body_clob, l_response_chunk_size, l_offset, l_response_buffer);
     htp.prn(l_response_buffer);
     l_offset := l_offset + l_response_chunk_size;
     l_response_length := l_response_length - l_response_chunk_size;
 END LOOP;

  dbms_lob.close(l_response_body_clob);

end;


li