-- =============================================================================
-- CATÁLOGO DE RESTRICCIONES MÉDICAS
-- =============================================================================
-- Destino : misma instancia ORDS que security/Servcio/* (10.249.249.3) — NO la
--           BD local del proyecto Java ni ONEWMS_QA.
-- Fecha   : 24 de agosto de 2026
-- Alcance : docs/checklist-bloqueadores-negocio.html #2 (Médico Jefe) — catálogo
--           de 16 restricciones (RES-01..RES-16), asignables en el dictamen de
--           Examen médico. RES-01..RES-16 son un catálogo FIJO/codificado (no
--           una tabla administrable como Causa de consulta) — viven como
--           constante en el código Java (RestriccionService.CATALOGO), igual
--           que los catálogos estáticos ya usados en Antidoping/Consulta. Lo
--           que SÍ es una tabla nueva es cada ASIGNACIÓN de una restricción a
--           un NSS (con sus campos ricos: valor límite, fechas, etc.).
-- Diseño  : insert-only (mismo patrón que Maternidad/Accidentes-seguimiento) —
--           cada asignación/revaloración es un registro nuevo, se conserva el
--           histórico completo de restricciones de un NSS a lo largo del tiempo.
--
-- Como aplicar (SQL Developer > conexión > RESTful Services):
--   1. Dentro del módulo "Servcio" existente > New Template.
--   2. URI Template: "restriccion" (alta) / "consulta_restriccion" (lista).
--   3. New Handler > Method: POST, Source Type: PL/SQL. Pegar BLOQUE 2 / BLOQUE 3.
-- =============================================================================


-- =============================================================================
-- BLOQUE 1: TABLA SERV_MED_RESTRICCION_ASIGNADA
-- =============================================================================
BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE SERV_MED_RESTRICCION_ASIGNADA (
      REG_ID               NUMBER GENERATED BY DEFAULT AS IDENTITY START WITH 1 INCREMENT BY 1
                            CONSTRAINT PK_SERV_MED_RESTRICCION PRIMARY KEY,
      NSS                  VARCHAR2(13) NOT NULL,
      CODIGO_RESTRICCION   VARCHAR2(10) NOT NULL,    -- RES-01..RES-16
      DESCRIPCION          VARCHAR2(500),             -- etiqueta o texto libre si RES-16 "Otra"
      VALOR_LIMITE         NUMBER,
      UNIDAD               VARCHAR2(30),
      FECHA_INICIO         DATE,
      FECHA_FIN             DATE,
      FECHA_REVALORACION   DATE,
      TEMPORALIDAD         VARCHAR2(30),              -- PERMANENTE | TEMPORAL
      OBSERVACIONES        VARCHAR2(500),
      MEDICO_RESPONSABLE   VARCHAR2(100),
      ESTATUS              VARCHAR2(30),              -- ACTIVA | VENCIDA | CANCELADA
      FECHA_REGISTRO       DATE DEFAULT SYSDATE NOT NULL,
      ID_USUARIO           VARCHAR2(50),
      NOMBRE_USUARIO       VARCHAR2(100)
    )
  ]';
EXCEPTION WHEN OTHERS THEN IF SQLCODE = -955 THEN NULL; ELSE RAISE; END IF;
END;
/

BEGIN EXECUTE IMMEDIATE 'CREATE INDEX IDX_SERV_MED_RESTRICCION_NSS ON SERV_MED_RESTRICCION_ASIGNADA (NSS)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE = -955 THEN NULL; ELSE RAISE; END IF; END;
/

COMMENT ON TABLE SERV_MED_RESTRICCION_ASIGNADA IS 'Restricciones medicas asignadas por NSS (insert-only, conserva historico de revaloraciones). Catalogo RES-01..RES-16 fijo del lado Java. Aplicada 24-ago-2026.';
/


-- =============================================================================
-- BLOQUE 2: HANDLER ORDS — POST /Servcio/restriccion (alta)
-- Pegar completo como "Source" del handler POST.
-- =============================================================================
declare

l_response_body_clob  clob ;
l_response_length     NUMBER;
l_response_buffer     VARCHAR2(32767);
l_response_chunk_size BINARY_INTEGER := 32000;
l_offset              INTEGER := 1;
j apex_json.t_values;
kjson clob;
kclob clob;
knns varchar2(13);
kcodigo varchar2(10);
kdescripcion varchar2(500);
kvalorlimite number;
kunidad varchar2(30);
kfechainicio varchar2(20);
kfechafin varchar2(20);
kfecharevaloracion varchar2(20);
ktemporalidad varchar2(30);
kobservaciones varchar2(500);
kmedicoresponsable varchar2(100);
kestatus varchar2(30);
kidusuario varchar2(50);
knombreusuario varchar2(100);

begin
kclob:= utl_raw.cast_to_varchar2(:body);
apex_json.parse(j,kclob);

knns               := apex_json.get_varchar2(p_path=>'NSS',p_values=>j);
kcodigo            := apex_json.get_varchar2(p_path=>'CODIGO_RESTRICCION',p_values=>j);
kdescripcion       := apex_json.get_varchar2(p_path=>'DESCRIPCION',p_values=>j);
kvalorlimite       := apex_json.get_number(p_path=>'VALOR_LIMITE',p_values=>j);
kunidad            := apex_json.get_varchar2(p_path=>'UNIDAD',p_values=>j);
kfechainicio       := apex_json.get_varchar2(p_path=>'FECHA_INICIO',p_values=>j);
kfechafin          := apex_json.get_varchar2(p_path=>'FECHA_FIN',p_values=>j);
kfecharevaloracion := apex_json.get_varchar2(p_path=>'FECHA_REVALORACION',p_values=>j);
ktemporalidad      := apex_json.get_varchar2(p_path=>'TEMPORALIDAD',p_values=>j);
kobservaciones     := apex_json.get_varchar2(p_path=>'OBSERVACIONES',p_values=>j);
kmedicoresponsable := apex_json.get_varchar2(p_path=>'MEDICO_RESPONSABLE',p_values=>j);
kestatus           := apex_json.get_varchar2(p_path=>'ESTATUS',p_values=>j);
kidusuario         := apex_json.get_varchar2(p_path=>'USUARIO_ID',p_values=>j);
knombreusuario     := apex_json.get_varchar2(p_path=>'NOMBRE_USUARIO',p_values=>j);

insert into SERV_MED_RESTRICCION_ASIGNADA(
  NSS, CODIGO_RESTRICCION, DESCRIPCION, VALOR_LIMITE, UNIDAD,
  FECHA_INICIO, FECHA_FIN, FECHA_REVALORACION, TEMPORALIDAD,
  OBSERVACIONES, MEDICO_RESPONSABLE, ESTATUS, ID_USUARIO, NOMBRE_USUARIO)
values (
  knns, kcodigo, kdescripcion, kvalorlimite, kunidad,
  case when kfechainicio is not null then to_date(kfechainicio,'DD/MM/YYYY') end,
  case when kfechafin is not null then to_date(kfechafin,'DD/MM/YYYY') end,
  case when kfecharevaloracion is not null then to_date(kfecharevaloracion,'DD/MM/YYYY') end,
  ktemporalidad, kobservaciones, kmedicoresponsable, kestatus, kidusuario, knombreusuario);

commit;

APEX_JSON.initialize_clob_output;
   APEX_JSON.open_OBJECT;
    APEX_JSON.open_array('Datos');
   APEX_JSON.open_OBJECT;
      APEX_JSON.write('Proceso','Restriccion registrada correctamente');
      APEX_JSON.write('Estado',100);
      APEX_JSON.write('Mensaje','Insercion correcta');
      APEX_JSON.write('Data','Proceso correcto');
   APEX_JSON.close_OBJECT;
  APEX_JSON.close_array;
 APEX_JSON.close_OBJECT;
kjson := APEX_JSON.get_clob_output;
APEX_JSON.free_output;

l_response_body_clob := kjson;
dbms_lob.open(l_response_body_clob, dbms_lob.lob_readonly);
l_response_length := dbms_lob.getlength (l_response_body_clob);

WHILE (l_response_length > 0)
 LOOP
    dbms_lob.read(l_response_body_clob, l_response_chunk_size, l_offset, l_response_buffer);
     htp.prn(l_response_buffer);
     l_offset := l_offset + l_response_chunk_size;
     l_response_length := l_response_length - l_response_chunk_size;
 END LOOP;

  dbms_lob.close(l_response_body_clob);

end;


-- =============================================================================
-- BLOQUE 3: HANDLER ORDS — POST /Servcio/consulta_restriccion (lista por NSS)
-- Pegar completo como "Source" del handler POST.
-- =============================================================================
declare

l_response_body_clob  clob ;
l_response_length     NUMBER;
l_response_buffer     VARCHAR2(32767);
l_response_chunk_size BINARY_INTEGER := 32000;
l_offset              INTEGER := 1;
j apex_json.t_values;
kjson clob;
kclob clob;
kdata varchar2(250);
KEXISTE NUMBER;
knns varchar2(13);

begin
kclob:= utl_raw.cast_to_varchar2(:body);
apex_json.parse(j,kclob);

knns := apex_json.get_varchar2(p_path=>'NSS',p_values=>j);

select COUNT(*) into KEXISTE from SERV_MED_RESTRICCION_ASIGNADA where NSS = knns;

APEX_JSON.initialize_clob_output;
APEX_JSON.OPEN_OBJECT;

IF KEXISTE > 0 THEN
APEX_JSON.open_array('Datos');
for i in (select
REG_ID, CODIGO_RESTRICCION, DESCRIPCION, VALOR_LIMITE, UNIDAD, FECHA_INICIO, FECHA_FIN,
FECHA_REVALORACION, TEMPORALIDAD, OBSERVACIONES, MEDICO_RESPONSABLE, ESTATUS, FECHA_REGISTRO, NOMBRE_USUARIO
from SERV_MED_RESTRICCION_ASIGNADA
where NSS = knns
order by FECHA_REGISTRO desc)
loop
  APEX_JSON.open_OBJECT;
    APEX_JSON.WRITE('id_registro',coalesce(i.reg_id,0));
    APEX_JSON.WRITE('codigo_restriccion',coalesce(i.codigo_restriccion,'0'));
    APEX_JSON.WRITE('descripcion',coalesce(i.descripcion,'0'));
    APEX_JSON.WRITE('valor_limite',coalesce(i.valor_limite,0));
    APEX_JSON.WRITE('unidad',coalesce(i.unidad,''));
    APEX_JSON.WRITE('fecha_inicio',coalesce(to_char(i.fecha_inicio,'DD/MM/YYYY'),''));
    APEX_JSON.WRITE('fecha_fin',coalesce(to_char(i.fecha_fin,'DD/MM/YYYY'),''));
    APEX_JSON.WRITE('fecha_revaloracion',coalesce(to_char(i.fecha_revaloracion,'DD/MM/YYYY'),''));
    APEX_JSON.WRITE('temporalidad',coalesce(i.temporalidad,'0'));
    APEX_JSON.WRITE('observaciones',coalesce(i.observaciones,''));
    APEX_JSON.WRITE('medico_responsable',coalesce(i.medico_responsable,''));
    APEX_JSON.WRITE('estatus',coalesce(i.estatus,'0'));
    APEX_JSON.WRITE('fecha_registro',coalesce(to_char(i.fecha_registro,'DD/MM/YYYY HH24:MI:SS'),'0'));
    APEX_JSON.WRITE('usuario',coalesce(i.nombre_usuario,'0'));
  APEX_JSON.close_OBJECT;
end loop;
   APEX_JSON.CLOSE_array;
  APEX_JSON.close_OBJECT;
       kjson := APEX_JSON.get_clob_output;
    APEX_JSON.free_output;

ELSE
   APEX_JSON.initialize_clob_output;
            APEX_JSON.open_OBJECT;
             APEX_JSON.open_array('Datos');
            APEX_JSON.open_OBJECT;
               APEX_JSON.write('Proceso','consulta de restricciones medicas');
               APEX_JSON.write('Estado',-100);
               APEX_JSON.write('Mensaje','No se tienen datos en la consulta');
               APEX_JSON.write('Data',kdata);
            APEX_JSON.close_OBJECT;
           APEX_JSON.close_array;
          APEX_JSON.close_OBJECT;
              kjson := APEX_JSON.get_clob_output;
    APEX_JSON.free_output;
END IF;

l_response_body_clob := kjson;
dbms_lob.open(l_response_body_clob, dbms_lob.lob_readonly);
l_response_length := dbms_lob.getlength (l_response_body_clob);

WHILE (l_response_length > 0)
 LOOP
    dbms_lob.read(l_response_body_clob, l_response_chunk_size, l_offset, l_response_buffer);
     htp.prn(l_response_buffer);
     l_offset := l_offset + l_response_chunk_size;
     l_response_length := l_response_length - l_response_chunk_size;
 END LOOP;

  dbms_lob.close(l_response_body_clob);

end;


-- =============================================================================
-- NOTAS
-- =============================================================================
-- [NOTA-1] Los codigos RES-01..RES-16 NO tienen tabla catalogo propia en Oracle -
--   viven como constante fija en el codigo Java (RestriccionService.CATALOGO),
--   mismo criterio que los <select> estaticos de tipoConsulta/areaAccidente en
--   Consulta. No se pidio que fueran administrables (a diferencia de Causa de
--   consulta) - son 16 codigos fijos definidos en la propuesta formal.
-- [NOTA-2] Insert-only: revalorar una restriccion (nueva fecha de revaloracion,
--   nuevo valor limite, etc.) es un registro NUEVO, no un UPDATE del existente -
--   conserva el historico completo de como fue cambiando la restriccion de un
--   NSS en el tiempo. La UI muestra el mas reciente primero.
-- =============================================================================
