-- =============================================================================
-- EXAMEN MÉDICO — Tabla de historial (dictamen APTO/NO_APTO por fecha)
-- =============================================================================
-- Destino : instancia Oracle que respalda el WS ORDS real (security/Servcio/*,
--           http://10.249.249.3/biows/ords/security) — misma instancia donde ya
--           viven SERV_MED_RESULTADO_EXAMEN y PR_SERVICIO_MED_EXAMEN2.
-- Fecha   : 17 de agosto de 2026
-- Motivo  : SERV_MED_RESULTADO_EXAMEN no tiene columna de fecha y guarda UNA
--           SOLA fila por NSS (cada examen nuevo sobreescribe al anterior) - no
--           se puede armar un dashboard "Exámenes Médicos" ni completar
--           "Resumen General" sin esto. Ver docs/bloqueo-examen-resumen-general.md.
--
-- IMPORTANTE - SIN DATOS RETROACTIVOS: esta tabla arranca vacía. Los dictámenes
-- ya guardados en SERV_MED_RESULTADO_EXAMEN hoy NUNCA tuvieron fecha asociada -
-- no hay forma de reconstruir cuándo se capturó cada uno. Solo se registrarán
-- los exámenes que se guarden DESPUÉS de aplicar este cambio.
--
-- CAMBIO ADITIVO: no se toca ni una sola línea del INSERT/UPDATE existente sobre
-- SERV_MED_RESULTADO_EXAMEN (el guardado real del examen no cambia en nada). Solo
-- se agrega un bloque nuevo, aislado con su propio manejo de excepción, para que
-- un fallo ahí jamás pueda romper ni revertir el guardado real del examen.
-- =============================================================================


-- =============================================================================
-- BLOQUE 1: TABLA SERV_MED_RESULTADO_EXAMEN_HIST
-- =============================================================================
BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE SERV_MED_RESULTADO_EXAMEN_HIST (
      REG_ID              NUMBER GENERATED BY DEFAULT AS IDENTITY START WITH 1 INCREMENT BY 1
                          CONSTRAINT PK_RESULTADO_EXAMEN_HIST PRIMARY KEY,
      NSS                 VARCHAR2(13) NOT NULL,
      FECHA_REGISTRO      DATE DEFAULT SYSDATE NOT NULL,
      APTO                VARCHAR2(100),
      NO_APTO             VARCHAR2(100),
      APTO_CONDICIONADO   VARCHAR2(100),
      APTO_RESTRINGIDO    VARCHAR2(100)
    )
  ]';
EXCEPTION WHEN OTHERS THEN IF SQLCODE = -955 THEN NULL; ELSE RAISE; END IF;
END;
/

BEGIN EXECUTE IMMEDIATE 'CREATE INDEX IDX_RESULTADO_EXAMEN_HIST_NSS ON SERV_MED_RESULTADO_EXAMEN_HIST (NSS)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE = -955 THEN NULL; ELSE RAISE; END IF; END;
/

BEGIN EXECUTE IMMEDIATE 'CREATE INDEX IDX_RESULTADO_EXAMEN_HIST_FECHA ON SERV_MED_RESULTADO_EXAMEN_HIST (FECHA_REGISTRO)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE = -955 THEN NULL; ELSE RAISE; END IF; END;
/

COMMENT ON TABLE SERV_MED_RESULTADO_EXAMEN_HIST IS 'Historial por fecha del dictamen de examen medico (APTO/NO_APTO/etc). No retroactivo - arranca vacia el 2026-08-17. Alimentada por PR_SERVICIO_MED_EXAMEN2 (bloque aditivo, ver docs/ords-examen-historial.sql BLOQUE 2).';
/


-- =============================================================================
-- BLOQUE 2: EDICIÓN QUIRÚRGICA de PR_SERVICIO_MED_EXAMEN2 (NO recrear el proc completo)
-- =============================================================================
-- Este procedimiento tiene ~750 líneas y controla TODAS las secciones del examen
-- (heredofamiliares, antecedentes laborales, exploración física, etc.) - no
-- reemplazarlo completo. Editarlo en SQL Developer y agregar SOLO el bloque nuevo
-- de abajo, exactamente en el punto indicado.
--
-- PASO A: abrir PR_SERVICIO_MED_EXAMEN2 en SQL Developer.
--
-- PASO B: localizar este bloque EXISTENTE (no tocarlo, es solo la referencia para
-- ubicar el punto de insercion):
--
--   IF kexiste = 0 then
--      insert into SERV_MED_RESULTADO_EXAMEN(NSS,
--      OBSERVACIONES, APTO, NO_APTO, APTO_CONDICIONADO, APTO_RESTRINGIDO,
--      firma_digital) VALUES (KNNS,CVAR100,CVAR1,CVAR2,CVAR3,CVAR4,kfirma);
--   ELSE
--      UPDATE SERV_MED_RESULTADO_EXAMEN SET
--      OBSERVACIONES=CVAR100,
--      APTO=CVAR1,NO_APTO=CVAR2,APTO_CONDICIONADO=CVAR3,APTO_RESTRINGIDO=CVAR4,
--      firma_digital=kfirma
--      where NSS=KNNS;
--   END IF;
--                                          <-- INSERTAR EL BLOQUE NUEVO JUSTO AQUI
--   KRESPUESTA:= 0;
--
-- PASO C: pegar este bloque nuevo INMEDIATAMENTE DESPUES del "END IF;" de arriba
-- y ANTES de "KRESPUESTA:= 0;" (no antes, no despues - debe correr una sola vez
-- por guardado, con los mismos CVAR1-4/KNNS que ya se acaban de usar):
--
--   ----------------------------------------------------------------------------
--   -- Historial para dashboard (aditivo). Aislado con su propio manejo de
--   -- excepcion: si esto falla por cualquier razon, NO afecta KRESPUESTA ni
--   -- revierte el guardado real del examen (que ya paso arriba).
--   ----------------------------------------------------------------------------
--   BEGIN
--     INSERT INTO SERV_MED_RESULTADO_EXAMEN_HIST (NSS, APTO, NO_APTO, APTO_CONDICIONADO, APTO_RESTRINGIDO)
--     VALUES (KNNS, CVAR1, CVAR2, CVAR3, CVAR4);
--   EXCEPTION
--     WHEN OTHERS THEN
--       NULL; -- nunca debe tumbar el guardado real del examen
--   END;
--
-- PASO D: guardar/compilar el procedimiento. Probar guardando un examen real
-- (mismo NSS de prueba usado en las rondas anteriores) y confirmar DOS cosas:
--   1. El examen se guarda igual que siempre (SERV_MED_RESULTADO_EXAMEN sin cambios
--      de comportamiento).
--   2. Aparece una fila nueva en SERV_MED_RESULTADO_EXAMEN_HIST con la fecha de hoy.
-- =============================================================================


-- =============================================================================
-- NOTAS
-- =============================================================================
-- [NOTA-1] KRESPUESTA es la unica salida que el llamador (Servcio/Medico) revisa
--   para decidir COMMIT vs ROLLBACK (docs/contextoWS.txt:1296-1298). El bloque
--   nuevo NUNCA debe tocar esa variable - por eso su propio EXCEPTION WHEN OTHERS
--   THEN NULL, sin propagar el error hacia arriba.
-- [NOTA-2] Si PR_SERVICIO_MED_EXAMEN1 falla (KRESP<>0), PR_SERVICIO_MED_EXAMEN2
--   nunca se ejecuta y todo se revierte (docs/contextoWS.txt:1294-1348) - el
--   bloque de historial nuevo tampoco corre en ese caso, comportamiento correcto
--   sin necesidad de logica adicional.
-- [NOTA-3] Siguiente paso (fuera de este script): crear el WS agregado
--   consulta_examen_fecha sobre esta tabla nueva, mismo patron que
--   consulta_incapacidades_fecha/consulta_accidentes_fecha/consulta_medica_fecha/
--   consulta_antidoping_fecha.
-- =============================================================================
