-- =============================================================================
-- ANTIDOPING — SELECCIÓN ALEATORIA (historial de quién fue elegido y cuándo)
-- =============================================================================
-- Destino : misma instancia ORDS que security/Servcio/* (10.249.249.3) — NO la
--           BD local del proyecto Java ni ONEWMS_QA.
-- Fecha   : 22 de agosto de 2026
-- Alcance : NO es el resultado del antidoping (eso ya vive en
--           SERV_MED_ANTIDOPING_RESULTADO, docs/ords-antidoping.sql) — esta
--           tabla es la traza de la RONDA de selección aleatoria en sí (quién
--           salió elegido de qué tamaño de pool y cuándo), pedida el 22 de
--           agosto para cumplir el requerimiento "conservar historial y
--           trazabilidad" de docs/entregable-liberacion-stoppers-salud.html §2
--           de forma completa (antes solo vivía en memoria del navegador,
--           se perdía al recargar la página /antidoping-seleccion).
-- Alta    : se llama UNA VEZ POR CADA NSS elegido en una ronda (si se
--           seleccionan 2, son 2 INSERT) — mismo criterio simple que el resto
--           del esquema SERV_MED_*, sin parsear arreglos en PL/SQL.
--
-- Como aplicar (SQL Developer > conexión > RESTful Services):
--   1. Dentro del módulo "Servcio" existente > New Template.
--   2. URI Template: "antidoping_seleccion" (alta) / "consulta_antidoping_seleccion" (lista).
--   3. New Handler > Method: POST, Source Type: PL/SQL. Pegar BLOQUE 2 / BLOQUE 3.
-- =============================================================================


-- =============================================================================
-- BLOQUE 1: TABLA SERV_MED_ANTIDOPING_SELECCION
-- =============================================================================
BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE SERV_MED_ANTIDOPING_SELECCION (
      REG_ID           NUMBER GENERATED BY DEFAULT AS IDENTITY START WITH 1 INCREMENT BY 1
                        CONSTRAINT PK_SERV_MED_ANTIDOP_SELEC PRIMARY KEY,
      FECHA_SELECCION  DATE DEFAULT SYSDATE NOT NULL,
      NSS              VARCHAR2(13) NOT NULL,
      TAMANO_POOL      NUMBER,
      ID_USUARIO       VARCHAR2(50),
      NOMBRE_USUARIO   VARCHAR2(100)
    )
  ]';
EXCEPTION WHEN OTHERS THEN IF SQLCODE = -955 THEN NULL; ELSE RAISE; END IF;
END;
/

BEGIN EXECUTE IMMEDIATE 'CREATE INDEX IDX_SERV_MED_ANTIDOP_SELEC_NSS ON SERV_MED_ANTIDOPING_SELECCION (NSS)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE = -955 THEN NULL; ELSE RAISE; END IF; END;
/

COMMENT ON TABLE SERV_MED_ANTIDOPING_SELECCION IS 'Traza de quien fue elegido al azar y cuando en /antidoping-seleccion - separada del resultado real (SERV_MED_ANTIDOPING_RESULTADO). Aplicada 22-ago-2026.';
/


-- =============================================================================
-- BLOQUE 2: HANDLER ORDS — POST /Servcio/antidoping_seleccion (alta, 1 por NSS elegido)
-- Mismo patron que security/Servcio/consumibles (docs/ords-antidoping-consumibles.sql).
-- Pegar completo como "Source" del handler POST.
-- =============================================================================
declare

l_response_body_clob  clob ;
l_response_length     NUMBER;
l_response_buffer     VARCHAR2(32767);
l_response_chunk_size BINARY_INTEGER := 32000;
l_offset              INTEGER := 1;
j apex_json.t_values;
kjson clob;
kclob clob;
knns varchar2(13);
ktamanopool number;
kidusuario varchar2(50);
knombreusuario varchar2(100);

begin
kclob:= utl_raw.cast_to_varchar2(:body);
apex_json.parse(j,kclob);

knns           := apex_json.get_varchar2(p_path=>'NSS',p_values=>j);
ktamanopool    := apex_json.get_number(p_path=>'TAMANO_POOL',p_values=>j);
kidusuario     := apex_json.get_varchar2(p_path=>'USUARIO_ID',p_values=>j);
knombreusuario := apex_json.get_varchar2(p_path=>'NOMBRE_USUARIO',p_values=>j);

insert into SERV_MED_ANTIDOPING_SELECCION(NSS, TAMANO_POOL, ID_USUARIO, NOMBRE_USUARIO)
values (knns, ktamanopool, kidusuario, knombreusuario);

commit;

APEX_JSON.initialize_clob_output;
   APEX_JSON.open_OBJECT;
    APEX_JSON.open_array('Datos');
   APEX_JSON.open_OBJECT;
      APEX_JSON.write('Proceso','Seleccion aleatoria registrada correctamente');
      APEX_JSON.write('Estado',100);
      APEX_JSON.write('Mensaje','Insercion correcta');
      APEX_JSON.write('Data','Proceso correcto');
   APEX_JSON.close_OBJECT;
  APEX_JSON.close_array;
 APEX_JSON.close_OBJECT;
kjson := APEX_JSON.get_clob_output;
APEX_JSON.free_output;

l_response_body_clob := kjson;
dbms_lob.open(l_response_body_clob, dbms_lob.lob_readonly);
l_response_length := dbms_lob.getlength (l_response_body_clob);

WHILE (l_response_length > 0)
 LOOP
    dbms_lob.read(l_response_body_clob, l_response_chunk_size, l_offset, l_response_buffer);
     htp.prn(l_response_buffer);
     l_offset := l_offset + l_response_chunk_size;
     l_response_length := l_response_length - l_response_chunk_size;
 END LOOP;

  dbms_lob.close(l_response_body_clob);

end;


-- =============================================================================
-- BLOQUE 3: HANDLER ORDS — POST /Servcio/consulta_antidoping_seleccion (lista)
-- NSS es OPCIONAL: si viene vacio/null, regresa TODO el historial (es un log
-- general de rondas de seleccion, no esta atado a un NSS especifico como el
-- resto de los consulta_* del sistema) - mismo criterio que consulta_consumibles.
-- Pegar completo como "Source" del handler POST.
-- =============================================================================
declare

l_response_body_clob  clob ;
l_response_length     NUMBER;
l_response_buffer     VARCHAR2(32767);
l_response_chunk_size BINARY_INTEGER := 32000;
l_offset              INTEGER := 1;
j apex_json.t_values;
kjson clob;
kclob clob;
kdata varchar2(250);
KEXISTE NUMBER;
knns varchar2(13);

begin
kclob:= utl_raw.cast_to_varchar2(:body);
apex_json.parse(j,kclob);

knns := apex_json.get_varchar2(p_path=>'NSS',p_values=>j);

select COUNT(*) into KEXISTE from SERV_MED_ANTIDOPING_SELECCION
  where (knns is null or NSS = knns);

APEX_JSON.initialize_clob_output;
APEX_JSON.OPEN_OBJECT;

IF KEXISTE > 0 THEN
APEX_JSON.open_array('Datos');
for i in (select
REG_ID, FECHA_SELECCION, NSS, TAMANO_POOL, NOMBRE_USUARIO
from SERV_MED_ANTIDOPING_SELECCION
where (knns is null or NSS = knns)
order by FECHA_SELECCION desc)
loop
  APEX_JSON.open_OBJECT;
    APEX_JSON.WRITE('id_registro',coalesce(i.reg_id,0));
    APEX_JSON.WRITE('fecha_seleccion',coalesce(to_char(i.fecha_seleccion,'DD/MM/YYYY HH24:MI:SS'),'0'));
    APEX_JSON.WRITE('nss',coalesce(i.nss,'0'));
    APEX_JSON.WRITE('tamano_pool',coalesce(i.tamano_pool,0));
    APEX_JSON.WRITE('usuario',coalesce(i.nombre_usuario,'0'));
  APEX_JSON.close_OBJECT;
end loop;
   APEX_JSON.CLOSE_array;
  APEX_JSON.close_OBJECT;
       kjson := APEX_JSON.get_clob_output;
    APEX_JSON.free_output;

ELSE
   APEX_JSON.initialize_clob_output;
            APEX_JSON.open_OBJECT;
             APEX_JSON.open_array('Datos');
            APEX_JSON.open_OBJECT;
               APEX_JSON.write('Proceso','consulta de seleccion aleatoria de antidoping');
               APEX_JSON.write('Estado',-100);
               APEX_JSON.write('Mensaje','No se tienen datos en la consulta');
               APEX_JSON.write('Data',kdata);
            APEX_JSON.close_OBJECT;
           APEX_JSON.close_array;
          APEX_JSON.close_OBJECT;
              kjson := APEX_JSON.get_clob_output;
    APEX_JSON.free_output;
END IF;

l_response_body_clob := kjson;
dbms_lob.open(l_response_body_clob, dbms_lob.lob_readonly);
l_response_length := dbms_lob.getlength (l_response_body_clob);

WHILE (l_response_length > 0)
 LOOP
    dbms_lob.read(l_response_body_clob, l_response_chunk_size, l_offset, l_response_buffer);
     htp.prn(l_response_buffer);
     l_offset := l_offset + l_response_chunk_size;
     l_response_length := l_response_length - l_response_chunk_size;
 END LOOP;

  dbms_lob.close(l_response_body_clob);

end;


-- =============================================================================
-- NOTAS
-- =============================================================================
-- [NOTA-1] "Estado":100/−100 replica el mismo patron que docs/ords-antidoping.sql
--   y docs/ords-antidoping-consumibles.sql - mismo esquema hermano.
-- [NOTA-2] Una ronda que selecciona N NSS genera N filas con FECHA_SELECCION
--   casi identica (mismo request, distinto INSERT) - no hay un "id de ronda"
--   explicito; se agrupan visualmente en el frontend por timestamp.
-- [NOTA-3] Esta tabla es solo trazabilidad de la seleccion - NO reemplaza ni
--   se relaciona por FK con SERV_MED_ANTIDOPING_RESULTADO (el resultado real
--   de la prueba). Un NSS puede aparecer aqui sin tener nunca un resultado
--   capturado (si se selecciono pero no se llego a aplicar la prueba).
-- =============================================================================
