-- =============================================================================
-- PREDIO ANALITICO + MAPEO CUENTA -> PREDIO
-- =============================================================================
-- Destino : misma instancia ORDS que security/Servcio/* (10.249.249.3) - NO la
--           BD local del proyecto Java ni ONEWMS_QA. NO se toca TAB_PREDIOS ni
--           BIO_DATOS_LABORALES_EMPLEADOS (compartidas con Rack/Seguridad/Comedor/
--           Encuestas/Boletos - ver docs/contextoWS.txt y la busqueda de columnas
--           que confirmo esos consumidores). Todo lo de este archivo es NUEVO y
--           propio del modulo de dashboards analiticos (rol MEDICO_ANALISTA).
-- Fecha   : 08 de septiembre de 2026
-- Motivo  : BIO_DATOS_LABORALES_EMPLEADOS.PREDIO (real, ligado a TAB_PREDIOS) hoy
--           solo distingue 2 valores (MACRO 1 / MACRO 2, confirmado con conteo real:
--           3521 activos, 3298 con predio, 223 sin dato). El dashboard analitico
--           necesita la granularidad de 17 sitios que ya traia el Excel de
--           morbilidad (docs/01_ANALISIS_ACTUAL.md) - "cuenta" (56 valores, ya
--           disponible via biometrico_cuenta_SAP/Catalogo/usuario) es el puente:
--           SE MAPEA cuenta -> predio-fino en una tabla propia, en vez de tocar el
--           dato real compartido de RH.
-- IMPORTANTE: crear la tabla NO destraba nada por si solo. El mapeo
--           SERV_MED_CUENTA_PREDIO nace VACIO - hasta que alguien que conozca la
--           operacion real asigne predio a cada cuenta (pantalla admin, BLOQUE 5),
--           los dashboards "por predio fino" muestran todo como "Sin asignar".
--
-- Como aplicar (SQL Developer > conexion > RESTful Services):
--   1. Correr BLOQUE 1 y 2 directo en el Worksheet SQL (son DDL, no van en ORDS).
--   2. Dentro del modulo "Servcio" existente > New Template para cada URI:
--      "predios" (BLOQUE 3), "cuenta_predio_lista" (BLOQUE 4),
--      "cuenta_predio_asignar" (BLOQUE 5).
--   3. New Handler > Method: POST, Source Type: PL/SQL. Pegar el bloque
--      correspondiente como Source.
-- =============================================================================


-- =============================================================================
-- BLOQUE 1: TABLA SERV_MED_PREDIO + seed de los 17 sitios (+ Sin dato)
-- =============================================================================
BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE SERV_MED_PREDIO (
      REG_ID  NUMBER GENERATED BY DEFAULT AS IDENTITY START WITH 1 INCREMENT BY 1
              CONSTRAINT PK_SERV_MED_PREDIO PRIMARY KEY,
      NOMBRE  VARCHAR2(100) NOT NULL,
      ACTIVO  CHAR(1) DEFAULT 'Y' NOT NULL CONSTRAINT CK_PREDIO_ACTIVO CHECK (ACTIVO IN ('Y','N'))
    )
  ]';
EXCEPTION WHEN OTHERS THEN IF SQLCODE = -955 THEN NULL; ELSE RAISE; END IF;
END;
/

BEGIN EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX UX_SERV_MED_PREDIO_NOMBRE ON SERV_MED_PREDIO (UPPER(NOMBRE))';
EXCEPTION WHEN OTHERS THEN IF SQLCODE = -955 THEN NULL; ELSE RAISE; END IF; END;
/

COMMENT ON TABLE SERV_MED_PREDIO IS 'Catalogo de predios (sitios fisicos) para el dashboard analitico de MEDICO_ANALISTA. Independiente de TAB_PREDIOS (compartida con otros sistemas) - ver docs/ords-predio-cuenta.sql. Aplicada 08-sep-2026.';
/

-- Seed idempotente: los 17 sitios identificados en el Excel de morbilidad
-- (docs/01_ANALISIS_ACTUAL.md §4.1) + "Sin dato" para casos sin cuenta mapeada.
DECLARE
  TYPE t_predios IS TABLE OF VARCHAR2(100);
  predios t_predios := t_predios(
    'AIFA', 'ATIZAPAN', 'CHARCON', 'FLORA', 'MACRO I', 'MACRO II', 'MERCURIO', 'MIKELS',
    'SIGLO XXI', 'SMO', 'TOLUCA', 'TULTIPARK', 'U TEPALCAPA', 'WORLD PARK', 'Z VALLEJO',
    'FORANEO', 'SIN DATO'
  );
  v_existe NUMBER;
BEGIN
  FOR i IN 1 .. predios.COUNT LOOP
    SELECT COUNT(*) INTO v_existe FROM SERV_MED_PREDIO WHERE UPPER(NOMBRE) = UPPER(predios(i));
    IF v_existe = 0 THEN
      INSERT INTO SERV_MED_PREDIO (NOMBRE) VALUES (predios(i));
    END IF;
  END LOOP;
  COMMIT;
END;
/


-- =============================================================================
-- BLOQUE 2: TABLA SERV_MED_CUENTA_PREDIO (mapeo, insert-only con historico)
-- =============================================================================
-- Insert-only (mismo patron que Accidentes/Antidoping de este proyecto): reasignar
-- una cuenta a otro predio es una fila NUEVA, nunca un UPDATE - conserva cuando
-- cambio la asignacion. "Vigente" = la fila con FECHA_ASIGNACION mas reciente por
-- CUENTA_NOMBRE (ver BLOQUE 4).
BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE SERV_MED_CUENTA_PREDIO (
      REG_ID            NUMBER GENERATED BY DEFAULT AS IDENTITY START WITH 1 INCREMENT BY 1
                        CONSTRAINT PK_SERV_MED_CTA_PREDIO PRIMARY KEY,
      CUENTA_NOMBRE     VARCHAR2(50) NOT NULL,
      PREDIO_ID         NUMBER NOT NULL CONSTRAINT FK_CTA_PREDIO_PREDIO REFERENCES SERV_MED_PREDIO(REG_ID),
      FECHA_ASIGNACION  DATE DEFAULT SYSDATE NOT NULL,
      ID_USUARIO        VARCHAR2(50),
      NOMBRE_USUARIO    VARCHAR2(100)
    )
  ]';
EXCEPTION WHEN OTHERS THEN IF SQLCODE = -955 THEN NULL; ELSE RAISE; END IF;
END;
/

BEGIN EXECUTE IMMEDIATE 'CREATE INDEX IX_CTA_PREDIO_CUENTA ON SERV_MED_CUENTA_PREDIO (UPPER(CUENTA_NOMBRE), FECHA_ASIGNACION)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE = -955 THEN NULL; ELSE RAISE; END IF; END;
/

COMMENT ON TABLE SERV_MED_CUENTA_PREDIO IS 'Mapeo cuenta->predio (insert-only, vigente = ultima fila por cuenta). Nace vacia - alguien con conocimiento operativo real debe asignar cada cuenta desde la pantalla admin. Aplicada 08-sep-2026.';
/


-- =============================================================================
-- BLOQUE 3: HANDLER ORDS — POST /Servcio/predios (catalogo, para filtros/dropdown)
-- =============================================================================
declare
  l_response_body_clob  clob;
  l_response_length     number;
  l_response_buffer     varchar2(32767);
  l_response_chunk_size binary_integer := 32000;
  l_offset              integer := 1;
  kjson                 clob;
begin
  APEX_JSON.initialize_clob_output;
  APEX_JSON.open_object;
  APEX_JSON.open_array('Datos');

  for x in (select reg_id, nombre from SERV_MED_PREDIO where activo = 'Y' order by nombre) loop
    APEX_JSON.open_object;
      APEX_JSON.write('predioId', x.reg_id);
      APEX_JSON.write('nombre', x.nombre);
    APEX_JSON.close_object;
  end loop;

  APEX_JSON.close_array;
  APEX_JSON.close_object;
  kjson := APEX_JSON.get_clob_output;
  APEX_JSON.free_output;

  l_response_body_clob := kjson;
  dbms_lob.open(l_response_body_clob, dbms_lob.lob_readonly);
  l_response_length := dbms_lob.getlength(l_response_body_clob);
  while (l_response_length > 0) loop
    dbms_lob.read(l_response_body_clob, l_response_chunk_size, l_offset, l_response_buffer);
    htp.prn(l_response_buffer);
    l_offset := l_offset + l_response_chunk_size;
    l_response_length := l_response_length - l_response_chunk_size;
  end loop;
  dbms_lob.close(l_response_body_clob);
end;


-- =============================================================================
-- BLOQUE 4: HANDLER ORDS — POST /Servcio/cuenta_predio_lista
-- =============================================================================
-- Lista TODAS las cuentas reales de biometrico_cuenta_SAP (solo lectura, tabla ya
-- existente y en uso - cero riesgo) con su predio VIGENTE si ya fue asignado, o
-- null si sigue pendiente. Esto alimenta la pantalla admin de asignacion: siempre
-- muestra el universo real de cuentas de hoy, no una lista congelada.
declare
  l_response_body_clob  clob;
  l_response_length     number;
  l_response_buffer     varchar2(32767);
  l_response_chunk_size binary_integer := 32000;
  l_offset              integer := 1;
  kjson                 clob;
begin
  APEX_JSON.initialize_clob_output;
  APEX_JSON.open_object;
  APEX_JSON.open_array('Datos');

  for x in (
    select bc.cuenta_id, bc.cuenta_nombre, v.predio_id, v.predio_nombre
      from biometrico_cuenta_SAP bc
      left join (
        select m.cuenta_nombre, m.predio_id, p.nombre predio_nombre,
               row_number() over (partition by upper(m.cuenta_nombre) order by m.fecha_asignacion desc) rn
          from SERV_MED_CUENTA_PREDIO m
          join SERV_MED_PREDIO p on p.reg_id = m.predio_id
      ) v on upper(v.cuenta_nombre) = upper(bc.cuenta_nombre) and v.rn = 1
     order by bc.cuenta_nombre
  ) loop
    APEX_JSON.open_object;
      APEX_JSON.write('cuentaId', x.cuenta_id);
      APEX_JSON.write('cuentaNombre', x.cuenta_nombre);
      APEX_JSON.write('predioId', x.predio_id);
      APEX_JSON.write('predioNombre', coalesce(x.predio_nombre, '0'));
    APEX_JSON.close_object;
  end loop;

  APEX_JSON.close_array;
  APEX_JSON.close_object;
  kjson := APEX_JSON.get_clob_output;
  APEX_JSON.free_output;

  l_response_body_clob := kjson;
  dbms_lob.open(l_response_body_clob, dbms_lob.lob_readonly);
  l_response_length := dbms_lob.getlength(l_response_body_clob);
  while (l_response_length > 0) loop
    dbms_lob.read(l_response_body_clob, l_response_chunk_size, l_offset, l_response_buffer);
    htp.prn(l_response_buffer);
    l_offset := l_offset + l_response_chunk_size;
    l_response_length := l_response_length - l_response_chunk_size;
  end loop;
  dbms_lob.close(l_response_body_clob);
end;


-- =============================================================================
-- BLOQUE 5: HANDLER ORDS — POST /Servcio/cuenta_predio_asignar
-- =============================================================================
-- body: {"CuentaNombre":"UNILEVER TEPALCAPA","PredioId":3,"IdUsuario":"...","NombreUsuario":"..."}
-- Insert-only: cada llamada agrega una fila nueva (nunca UPDATE), la vigente es la
-- de fecha mas reciente (ver BLOQUE 4).
declare
  l_response_body_clob  clob;
  l_response_length     number;
  l_response_buffer     varchar2(32767);
  l_response_chunk_size binary_integer := 32000;
  l_offset              integer := 1;
  kjson                 clob;
  j                     apex_json.t_values;
  kcuenta               varchar2(50);
  kpredio_id            number;
  kid_usuario           varchar2(50);
  knombre_usuario       varchar2(100);
  kexiste               number;
begin
  apex_json.parse(j, utl_raw.cast_to_varchar2(:body));
  kcuenta         := apex_json.get_varchar2(p_path => 'CuentaNombre', p_values => j);
  kpredio_id      := apex_json.get_number(p_path => 'PredioId', p_values => j);
  kid_usuario     := apex_json.get_varchar2(p_path => 'IdUsuario', p_values => j);
  knombre_usuario := apex_json.get_varchar2(p_path => 'NombreUsuario', p_values => j);

  APEX_JSON.initialize_clob_output;
  APEX_JSON.open_object;
  APEX_JSON.open_array('Datos');

  select count(*) into kexiste from SERV_MED_PREDIO where reg_id = kpredio_id and activo = 'Y';

  if kcuenta is null or kpredio_id is null or kexiste = 0 then
    APEX_JSON.open_object;
      APEX_JSON.write('proceso', 'Rechazado: CuentaNombre/PredioId invalido o predio inactivo');
    APEX_JSON.close_object;
  else
    insert into SERV_MED_CUENTA_PREDIO (CUENTA_NOMBRE, PREDIO_ID, ID_USUARIO, NOMBRE_USUARIO)
    values (kcuenta, kpredio_id, kid_usuario, knombre_usuario);
    commit;

    APEX_JSON.open_object;
      APEX_JSON.write('proceso', 'Asignacion registrada');
    APEX_JSON.close_object;
  end if;

  APEX_JSON.close_array;
  APEX_JSON.close_object;
  kjson := APEX_JSON.get_clob_output;
  APEX_JSON.free_output;

  l_response_body_clob := kjson;
  dbms_lob.open(l_response_body_clob, dbms_lob.lob_readonly);
  l_response_length := dbms_lob.getlength(l_response_body_clob);
  while (l_response_length > 0) loop
    dbms_lob.read(l_response_body_clob, l_response_chunk_size, l_offset, l_response_buffer);
    htp.prn(l_response_buffer);
    l_offset := l_offset + l_response_chunk_size;
    l_response_length := l_response_length - l_response_chunk_size;
  end loop;
  dbms_lob.close(l_response_body_clob);
end;

-- =============================================================================
-- NOTAS
-- =============================================================================
-- [NOTA-1] CUENTA_NOMBRE (texto, no cuenta_id numerico) es la llave del mapeo a
--   proposito: es lo que YA fluye hoy por toda la app (EmpleadoDto.cuenta(), via
--   Catalogo/usuario -> bc.cuenta_nombre) - matchear por nombre (case-insensitive,
--   UPPER() en el indice) evita tener que agregar cuenta_id a ningun WS existente.
-- [NOTA-2] BLOQUE 4 asume que biometrico_cuenta_SAP tiene columnas cuenta_id y
--   cuenta_nombre (confirmado en el join de Catalogo/usuario: "bc.cuenta_nombre",
--   "c.cuenta_id=bc.cuenta_id") - no se corrio contra el diccionario de datos real
--   en esta sesion, verificar nombres exactos antes de aplicar.
-- [NOTA-3] Para resolver el predio-fino de un CASO (incapacidad/examen/etc.): del
--   lado Java, NSS -> Catalogo/usuario -> cuenta (nombre) -> buscar en el resultado
--   de cuenta_predio_lista (cacheado, no llamar por cada caso) -> predioId/nombre.
--   Si la cuenta no esta en el mapeo (predioNombre='0'), el caso cae en "Sin
--   asignar", nunca se descarta ni se rompe.
-- =============================================================================
