-- =============================================================================
-- CAUSA DE CONSULTA MÉDICA — CATÁLOGO CERRADO
-- =============================================================================
-- Destino : misma instancia ORDS que security/Servcio/* (10.249.249.3) — NO la
--           BD local del proyecto Java ni ONEWMS_QA.
-- Fecha   : 24 de agosto de 2026
-- Alcance : docs/ONEST_Proyecto_Salud_Ocupacional_Decisiones.pdf §2 — revierte la
--           respuesta original del PO ("texto libre"); exige catálogo normalizado
--           de 23 causas + "Otro" con descripción libre, administrable (altas,
--           bajas/activación, histórico, control de duplicados).
-- Uso     : el campo CAUSA de Servcio/consulta (docs/... ya existente, sin tocar)
--           sigue siendo texto libre del lado del WS — este catálogo solo
--           CONTROLA qué texto se puede elegir en la captura (o "Otro" + lo que
--           el usuario escriba). No hay FK entre este catálogo y TBL_SERV_CONSULTA
--           porque esa tabla ya existe con CAUSA como texto plano.
--
-- Como aplicar (SQL Developer > conexión > RESTful Services):
--   1. Dentro del módulo "Servcio" existente > New Template.
--   2. URI Template: "causa_consulta" (alta) / "consulta_causa_consulta" (lista) /
--      "causa_consulta_estado" (activar/desactivar).
--   3. New Handler > Method: POST, Source Type: PL/SQL. Pegar BLOQUE 2 / 3 / 4.
-- =============================================================================


-- =============================================================================
-- BLOQUE 1: TABLA SERV_MED_CAT_CAUSA_CONSULTA + seed de las 23 causas + Otro
-- =============================================================================
BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE SERV_MED_CAT_CAUSA_CONSULTA (
      REG_ID          NUMBER GENERATED BY DEFAULT AS IDENTITY START WITH 1 INCREMENT BY 1
                       CONSTRAINT PK_SERV_MED_CAT_CAUSA PRIMARY KEY,
      NOMBRE          VARCHAR2(200) NOT NULL,
      ACTIVO          CHAR(1) DEFAULT 'Y' NOT NULL CONSTRAINT CK_CAT_CAUSA_ACTIVO CHECK (ACTIVO IN ('Y','N')),
      FECHA_ALTA      DATE DEFAULT SYSDATE NOT NULL,
      FECHA_BAJA      DATE,
      ID_USUARIO      VARCHAR2(50),
      NOMBRE_USUARIO  VARCHAR2(100)
    )
  ]';
EXCEPTION WHEN OTHERS THEN IF SQLCODE = -955 THEN NULL; ELSE RAISE; END IF;
END;
/

-- Control de duplicados: unico case-insensitive sobre el nombre (no se puede dar de
-- alta "Dolor De Cabeza" si ya existe "dolor de cabeza", activo o no).
BEGIN EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX UX_CAT_CAUSA_NOMBRE ON SERV_MED_CAT_CAUSA_CONSULTA (UPPER(NOMBRE))';
EXCEPTION WHEN OTHERS THEN IF SQLCODE = -955 THEN NULL; ELSE RAISE; END IF; END;
/

COMMENT ON TABLE SERV_MED_CAT_CAUSA_CONSULTA IS 'Catalogo administrable de causas de consulta (23 + Otro). ACTIVO=N es "baja" (soft, conserva historico). Aplicada 24-ago-2026.';
/

-- Seed: las 23 causas de docs/checklist-bloqueadores-negocio.html + "Otro". Idempotente -
-- solo inserta las que no existan ya (por si se re-corre este script).
DECLARE
  TYPE t_causas IS TABLE OF VARCHAR2(200);
  causas t_causas := t_causas(
    'Enfermedad general', 'Dolor de cabeza', 'Problema gastrointestinal', 'Problema respiratorio',
    'Dolor muscular', 'Dolor de espalda', 'Lesión musculoesquelética', 'Caída', 'Golpe/contusión',
    'Herida/cortadura', 'Quemadura', 'Problema ocular', 'Reacción alérgica', 'Mareo',
    'Presión arterial', 'Accidente de trabajo', 'Accidente en trayecto', 'Accidente no laboral',
    'Seguimiento médico', 'Examen médico', 'Maternidad/embarazo', 'Curación', 'Valoración preventiva',
    'Otro'
  );
  v_existe NUMBER;
BEGIN
  FOR i IN 1 .. causas.COUNT LOOP
    SELECT COUNT(*) INTO v_existe FROM SERV_MED_CAT_CAUSA_CONSULTA WHERE UPPER(NOMBRE) = UPPER(causas(i));
    IF v_existe = 0 THEN
      INSERT INTO SERV_MED_CAT_CAUSA_CONSULTA (NOMBRE, ID_USUARIO, NOMBRE_USUARIO)
      VALUES (causas(i), '747849849', 'SEED');
    END IF;
  END LOOP;
  COMMIT;
END;
/


-- =============================================================================
-- BLOQUE 2: HANDLER ORDS — POST /Servcio/causa_consulta (alta)
-- Pegar completo como "Source" del handler POST.
-- =============================================================================
declare

l_response_body_clob  clob ;
l_response_length     NUMBER;
l_response_buffer     VARCHAR2(32767);
l_response_chunk_size BINARY_INTEGER := 32000;
l_offset              INTEGER := 1;
j apex_json.t_values;
kjson clob;
kclob clob;
knombre varchar2(200);
kidusuario varchar2(50);
knombreusuario varchar2(100);
kexiste number;

begin
kclob:= utl_raw.cast_to_varchar2(:body);
apex_json.parse(j,kclob);

knombre        := apex_json.get_varchar2(p_path=>'NOMBRE',p_values=>j);
kidusuario     := apex_json.get_varchar2(p_path=>'USUARIO_ID',p_values=>j);
knombreusuario := apex_json.get_varchar2(p_path=>'NOMBRE_USUARIO',p_values=>j);

select count(*) into kexiste from SERV_MED_CAT_CAUSA_CONSULTA where upper(nombre) = upper(knombre);

APEX_JSON.initialize_clob_output;
   APEX_JSON.open_OBJECT;
    APEX_JSON.open_array('Datos');
   APEX_JSON.open_OBJECT;

IF kexiste > 0 THEN
      APEX_JSON.write('Proceso','Ya existe una causa con ese nombre');
      APEX_JSON.write('Estado',-100);
      APEX_JSON.write('Mensaje','Duplicado');
      APEX_JSON.write('Data','0');
ELSE
      insert into SERV_MED_CAT_CAUSA_CONSULTA(NOMBRE, ID_USUARIO, NOMBRE_USUARIO)
      values (knombre, kidusuario, knombreusuario);
      commit;
      APEX_JSON.write('Proceso','Causa registrada correctamente');
      APEX_JSON.write('Estado',100);
      APEX_JSON.write('Mensaje','Insercion correcta');
      APEX_JSON.write('Data','Proceso correcto');
END IF;

   APEX_JSON.close_OBJECT;
  APEX_JSON.close_array;
 APEX_JSON.close_OBJECT;
kjson := APEX_JSON.get_clob_output;
APEX_JSON.free_output;

l_response_body_clob := kjson;
dbms_lob.open(l_response_body_clob, dbms_lob.lob_readonly);
l_response_length := dbms_lob.getlength (l_response_body_clob);

WHILE (l_response_length > 0)
 LOOP
    dbms_lob.read(l_response_body_clob, l_response_chunk_size, l_offset, l_response_buffer);
     htp.prn(l_response_buffer);
     l_offset := l_offset + l_response_chunk_size;
     l_response_length := l_response_length - l_response_chunk_size;
 END LOOP;

  dbms_lob.close(l_response_body_clob);

end;


-- =============================================================================
-- BLOQUE 3: HANDLER ORDS — POST /Servcio/consulta_causa_consulta (lista)
-- SOLO_ACTIVOS es OPCIONAL: 'Y' filtra solo activas (para el <select> de captura de
-- Consulta), null/vacio regresa TODAS (activas e inactivas, para la pantalla admin).
-- Pegar completo como "Source" del handler POST.
-- =============================================================================
declare

l_response_body_clob  clob ;
l_response_length     NUMBER;
l_response_buffer     VARCHAR2(32767);
l_response_chunk_size BINARY_INTEGER := 32000;
l_offset              INTEGER := 1;
j apex_json.t_values;
kjson clob;
kclob clob;
kdata varchar2(250);
KEXISTE NUMBER;
ksoloactivos varchar2(1);

begin
kclob:= utl_raw.cast_to_varchar2(:body);
apex_json.parse(j,kclob);

ksoloactivos := apex_json.get_varchar2(p_path=>'SOLO_ACTIVOS',p_values=>j);

select COUNT(*) into KEXISTE from SERV_MED_CAT_CAUSA_CONSULTA
  where (ksoloactivos is null or ksoloactivos != 'Y' or ACTIVO = 'Y');

APEX_JSON.initialize_clob_output;
APEX_JSON.OPEN_OBJECT;

IF KEXISTE > 0 THEN
APEX_JSON.open_array('Datos');
for i in (select
REG_ID, NOMBRE, ACTIVO, FECHA_ALTA, FECHA_BAJA, NOMBRE_USUARIO
from SERV_MED_CAT_CAUSA_CONSULTA
where (ksoloactivos is null or ksoloactivos != 'Y' or ACTIVO = 'Y')
order by NOMBRE asc)
loop
  APEX_JSON.open_OBJECT;
    APEX_JSON.WRITE('id_registro',coalesce(i.reg_id,0));
    APEX_JSON.WRITE('nombre',coalesce(i.nombre,'0'));
    APEX_JSON.WRITE('activo',coalesce(i.activo,'Y'));
    APEX_JSON.WRITE('fecha_alta',coalesce(to_char(i.fecha_alta,'DD/MM/YYYY'),'0'));
    APEX_JSON.WRITE('fecha_baja',coalesce(to_char(i.fecha_baja,'DD/MM/YYYY'),''));
    APEX_JSON.WRITE('usuario',coalesce(i.nombre_usuario,'0'));
  APEX_JSON.close_OBJECT;
end loop;
   APEX_JSON.CLOSE_array;
  APEX_JSON.close_OBJECT;
       kjson := APEX_JSON.get_clob_output;
    APEX_JSON.free_output;

ELSE
   APEX_JSON.initialize_clob_output;
            APEX_JSON.open_OBJECT;
             APEX_JSON.open_array('Datos');
            APEX_JSON.open_OBJECT;
               APEX_JSON.write('Proceso','consulta de catalogo de causas');
               APEX_JSON.write('Estado',-100);
               APEX_JSON.write('Mensaje','No se tienen datos en la consulta');
               APEX_JSON.write('Data',kdata);
            APEX_JSON.close_OBJECT;
           APEX_JSON.close_array;
          APEX_JSON.close_OBJECT;
              kjson := APEX_JSON.get_clob_output;
    APEX_JSON.free_output;
END IF;

l_response_body_clob := kjson;
dbms_lob.open(l_response_body_clob, dbms_lob.lob_readonly);
l_response_length := dbms_lob.getlength (l_response_body_clob);

WHILE (l_response_length > 0)
 LOOP
    dbms_lob.read(l_response_body_clob, l_response_chunk_size, l_offset, l_response_buffer);
     htp.prn(l_response_buffer);
     l_offset := l_offset + l_response_chunk_size;
     l_response_length := l_response_length - l_response_chunk_size;
 END LOOP;

  dbms_lob.close(l_response_body_clob);

end;


-- =============================================================================
-- BLOQUE 4: HANDLER ORDS — POST /Servcio/causa_consulta_estado (activar/desactivar)
-- Primer UPDATE de este esquema (todo lo demas es insert-only) - se justifica
-- porque esto es un CATALOGO administrable (estado on/off), no un historial de
-- eventos por caso/NSS. FECHA_BAJA se limpia al reactivar.
-- Pegar completo como "Source" del handler POST.
-- =============================================================================
declare

l_response_body_clob  clob ;
l_response_length     NUMBER;
l_response_buffer     VARCHAR2(32767);
l_response_chunk_size BINARY_INTEGER := 32000;
l_offset              INTEGER := 1;
j apex_json.t_values;
kjson clob;
kclob clob;
kregid number;
kactivo varchar2(1);

begin
kclob:= utl_raw.cast_to_varchar2(:body);
apex_json.parse(j,kclob);

kregid  := apex_json.get_number(p_path=>'REG_ID',p_values=>j);
kactivo := apex_json.get_varchar2(p_path=>'ACTIVO',p_values=>j);

update SERV_MED_CAT_CAUSA_CONSULTA
   set ACTIVO = kactivo,
       FECHA_BAJA = CASE WHEN kactivo = 'N' THEN SYSDATE ELSE NULL END
 where REG_ID = kregid;

commit;

APEX_JSON.initialize_clob_output;
   APEX_JSON.open_OBJECT;
    APEX_JSON.open_array('Datos');
   APEX_JSON.open_OBJECT;
      APEX_JSON.write('Proceso','Estado actualizado correctamente');
      APEX_JSON.write('Estado',100);
      APEX_JSON.write('Mensaje','Actualizacion correcta');
      APEX_JSON.write('Data','Proceso correcto');
   APEX_JSON.close_OBJECT;
  APEX_JSON.close_array;
 APEX_JSON.close_OBJECT;
kjson := APEX_JSON.get_clob_output;
APEX_JSON.free_output;

l_response_body_clob := kjson;
dbms_lob.open(l_response_body_clob, dbms_lob.lob_readonly);
l_response_length := dbms_lob.getlength (l_response_body_clob);

WHILE (l_response_length > 0)
 LOOP
    dbms_lob.read(l_response_body_clob, l_response_chunk_size, l_offset, l_response_buffer);
     htp.prn(l_response_buffer);
     l_offset := l_offset + l_response_chunk_size;
     l_response_length := l_response_length - l_response_chunk_size;
 END LOOP;

  dbms_lob.close(l_response_body_clob);

end;


-- =============================================================================
-- NOTAS
-- =============================================================================
-- [NOTA-1] Migracion de datos historicos (valores de texto libre ya guardados hoy
--   en CAUSA de TBL_SERV_CONSULTA hacia este catalogo) queda FUERA de este script
--   a proposito - el mapeo no viene definido en la propuesta formal, pendiente de
--   confirmar con Medico Jefe/PO antes de programarla (ver checklist-bloqueadores-negocio).
-- [NOTA-2] No hay FK entre este catalogo y TBL_SERV_CONSULTA.CAUSA - ese campo
--   sigue siendo texto libre del lado del WS existente, este catalogo solo
--   controla que opciones ve el usuario al capturar (incluyendo "Otro" + texto libre).
-- =============================================================================
