-- 01_rbac_local.sql
-- RBAC local para Portal Salud (roles/menus/usuarios propios) - idempotente.
-- Ubicacion: src/main/resources/db/sql
--
-- Contexto: activa el esquema APP_SEC_*/APP_MENU ya sembrado (dormant) en
-- 00_init_oracle21c.sql para resolver menus/permisos localmente en vez de
-- contra el WS ORDS compartido con el portal PHP legacy. Ver docs/plan-rbac-local.md.
--
-- Este script asume que 00_init_oracle21c.sql ya corrio (APP_SEC_ROLE, APP_SEC_USER,
-- APP_MENU, etc. ya existen). Ejecutar despues de ese, no en su lugar.

SET SERVEROUTPUT ON;

PROMPT ============================================================
PROMPT [1/4] TABLA APP_MENU_ROLE (join menu<->rol, espejo de TBL_APPS_ROL_MENU de ORDS)
PROMPT ============================================================

BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE APP_MENU_ROLE (
      ID          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      MENU_ID     NUMBER NOT NULL,
      ROLE_ID     NUMBER NOT NULL,
      CREATED_AT  TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
      CREATED_BY  VARCHAR2(100) DEFAULT USER NOT NULL
    )
  ]';
  DBMS_OUTPUT.PUT_LINE('Tabla creada: APP_MENU_ROLE');
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; ELSE DBMS_OUTPUT.PUT_LINE('Tabla existente (omitida): APP_MENU_ROLE'); END IF; END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX UX_APP_MENU_ROLE ON APP_MENU_ROLE(MENU_ID, ROLE_ID)';
  DBMS_OUTPUT.PUT_LINE('Indice creado: UX_APP_MENU_ROLE');
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; ELSE DBMS_OUTPUT.PUT_LINE('Indice existente (omitido): UX_APP_MENU_ROLE'); END IF; END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME = 'FK_MENU_ROLE_MENU';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE APP_MENU_ROLE ADD CONSTRAINT FK_MENU_ROLE_MENU FOREIGN KEY (MENU_ID) REFERENCES APP_MENU(ID)';
    DBMS_OUTPUT.PUT_LINE('Constraint creada: FK_MENU_ROLE_MENU');
  ELSE
    DBMS_OUTPUT.PUT_LINE('Constraint existente (omitida): FK_MENU_ROLE_MENU');
  END IF;

  SELECT COUNT(*) INTO v_count FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME = 'FK_MENU_ROLE_ROLE';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE APP_MENU_ROLE ADD CONSTRAINT FK_MENU_ROLE_ROLE FOREIGN KEY (ROLE_ID) REFERENCES APP_SEC_ROLE(ID)';
    DBMS_OUTPUT.PUT_LINE('Constraint creada: FK_MENU_ROLE_ROLE');
  ELSE
    DBMS_OUTPUT.PUT_LINE('Constraint existente (omitida): FK_MENU_ROLE_ROLE');
  END IF;
END;
/

PROMPT ============================================================
PROMPT [2/4] APP_SEC_USER.PASSWORD_HASH -> NULLABLE (usuarios de solo-rol nunca autentican local)
PROMPT ============================================================

DECLARE
  v_nullable USER_TAB_COLUMNS.NULLABLE%TYPE;
BEGIN
  SELECT NULLABLE INTO v_nullable FROM USER_TAB_COLUMNS
   WHERE TABLE_NAME = 'APP_SEC_USER' AND COLUMN_NAME = 'PASSWORD_HASH';
  IF v_nullable = 'N' THEN
    EXECUTE IMMEDIATE 'ALTER TABLE APP_SEC_USER MODIFY (PASSWORD_HASH NULL)';
    DBMS_OUTPUT.PUT_LINE('Columna alterada: APP_SEC_USER.PASSWORD_HASH ahora NULL');
  ELSE
    DBMS_OUTPUT.PUT_LINE('Columna ya era NULL (omitida): APP_SEC_USER.PASSWORD_HASH');
  END IF;
END;
/

PROMPT ============================================================
PROMPT [3/4] SEED: 14 modulos del submenu (mismos nombres/iconos que fragments/nss-modules.html)
PROMPT ============================================================

MERGE INTO APP_MENU t USING (SELECT 'EXPEDIENTE_GENERAL' code, 'Expediente General' title, 'ri-booklet-line' icon, 1 order_no FROM dual) s
  ON (t.CODE = s.code) WHEN NOT MATCHED THEN INSERT (CODE, TITLE, ICON, ORDER_NO) VALUES (s.code, s.title, s.icon, s.order_no);
MERGE INTO APP_MENU t USING (SELECT 'LABORATORIO' code, 'E. Laboratorio' title, 'ri-flask-line' icon, 2 order_no FROM dual) s
  ON (t.CODE = s.code) WHEN NOT MATCHED THEN INSERT (CODE, TITLE, ICON, ORDER_NO) VALUES (s.code, s.title, s.icon, s.order_no);
MERGE INTO APP_MENU t USING (SELECT 'HISTORICO_EM' code, 'Historico E.M' title, 'ri-history-line' icon, 3 order_no FROM dual) s
  ON (t.CODE = s.code) WHEN NOT MATCHED THEN INSERT (CODE, TITLE, ICON, ORDER_NO) VALUES (s.code, s.title, s.icon, s.order_no);
MERGE INTO APP_MENU t USING (SELECT 'NOTA_MEDICA' code, 'Nota Medica' title, 'ri-file-text-line' icon, 4 order_no FROM dual) s
  ON (t.CODE = s.code) WHEN NOT MATCHED THEN INSERT (CODE, TITLE, ICON, ORDER_NO) VALUES (s.code, s.title, s.icon, s.order_no);
MERGE INTO APP_MENU t USING (SELECT 'NOTA_INCAPACIDAD' code, 'Nota Incapacidad' title, 'ri-file-paper-2-line' icon, 5 order_no FROM dual) s
  ON (t.CODE = s.code) WHEN NOT MATCHED THEN INSERT (CODE, TITLE, ICON, ORDER_NO) VALUES (s.code, s.title, s.icon, s.order_no);
MERGE INTO APP_MENU t USING (SELECT 'ARCHIVO_CONSULTAS' code, 'Archivo de Consultas' title, 'ri-book-2-line' icon, 6 order_no FROM dual) s
  ON (t.CODE = s.code) WHEN NOT MATCHED THEN INSERT (CODE, TITLE, ICON, ORDER_NO) VALUES (s.code, s.title, s.icon, s.order_no);
MERGE INTO APP_MENU t USING (SELECT 'CONSULTA_MEDICA' code, 'Consulta Medica' title, 'ri-health-book-line' icon, 7 order_no FROM dual) s
  ON (t.CODE = s.code) WHEN NOT MATCHED THEN INSERT (CODE, TITLE, ICON, ORDER_NO) VALUES (s.code, s.title, s.icon, s.order_no);
MERGE INTO APP_MENU t USING (SELECT 'INCAPACIDADES' code, 'Incapacidades' title, 'ri-first-aid-kit-line' icon, 8 order_no FROM dual) s
  ON (t.CODE = s.code) WHEN NOT MATCHED THEN INSERT (CODE, TITLE, ICON, ORDER_NO) VALUES (s.code, s.title, s.icon, s.order_no);
MERGE INTO APP_MENU t USING (SELECT 'ARCHIVO_INCAPACIDADES' code, 'Archivo Incapacidades' title, 'ri-archive-line' icon, 9 order_no FROM dual) s
  ON (t.CODE = s.code) WHEN NOT MATCHED THEN INSERT (CODE, TITLE, ICON, ORDER_NO) VALUES (s.code, s.title, s.icon, s.order_no);
MERGE INTO APP_MENU t USING (SELECT 'EXAMEN_MEDICO' code, 'Examen Medico' title, 'ri-heart-pulse-line' icon, 10 order_no FROM dual) s
  ON (t.CODE = s.code) WHEN NOT MATCHED THEN INSERT (CODE, TITLE, ICON, ORDER_NO) VALUES (s.code, s.title, s.icon, s.order_no);
MERGE INTO APP_MENU t USING (SELECT 'PRETEST' code, 'Pre-Test' title, 'ri-survey-line' icon, 11 order_no FROM dual) s
  ON (t.CODE = s.code) WHEN NOT MATCHED THEN INSERT (CODE, TITLE, ICON, ORDER_NO) VALUES (s.code, s.title, s.icon, s.order_no);
MERGE INTO APP_MENU t USING (SELECT 'ANTIDOPING' code, 'Antidoping' title, 'ri-test-tube-line' icon, 12 order_no FROM dual) s
  ON (t.CODE = s.code) WHEN NOT MATCHED THEN INSERT (CODE, TITLE, ICON, ORDER_NO) VALUES (s.code, s.title, s.icon, s.order_no);
MERGE INTO APP_MENU t USING (SELECT 'ACCIDENTES' code, 'Accidentes' title, 'ri-alarm-warning-line' icon, 13 order_no FROM dual) s
  ON (t.CODE = s.code) WHEN NOT MATCHED THEN INSERT (CODE, TITLE, ICON, ORDER_NO) VALUES (s.code, s.title, s.icon, s.order_no);
MERGE INTO APP_MENU t USING (SELECT 'MATERNIDAD' code, 'Maternidad' title, 'ri-women-line' icon, 14 order_no FROM dual) s
  ON (t.CODE = s.code) WHEN NOT MATCHED THEN INSERT (CODE, TITLE, ICON, ORDER_NO) VALUES (s.code, s.title, s.icon, s.order_no);

PROMPT ============================================================
PROMPT [4/4] SEED: 3 roles reales (USER/ADM/ENFERMERO, mismos nombres que ORDS id_app=13)
PROMPT y sus asignaciones de menu (replica lo verificado en vivo contra ORDS 2026-08-26)
PROMPT ============================================================

MERGE INTO APP_SEC_ROLE t USING (SELECT 'USER' code, 'Usuario' name FROM dual) s
  ON (t.CODE = s.code) WHEN NOT MATCHED THEN INSERT (CODE, NAME) VALUES (s.code, s.name);
MERGE INTO APP_SEC_ROLE t USING (SELECT 'ADM' code, 'Administrador clinico' name FROM dual) s
  ON (t.CODE = s.code) WHEN NOT MATCHED THEN INSERT (CODE, NAME) VALUES (s.code, s.name);
MERGE INTO APP_SEC_ROLE t USING (SELECT 'ENFERMERO' code, 'Enfermero' name FROM dual) s
  ON (t.CODE = s.code) WHEN NOT MATCHED THEN INSERT (CODE, NAME) VALUES (s.code, s.name);
COMMIT;

-- ADM: los 14 modulos (equivalente al id_rol=2 real, acceso completo verificado en vivo).
INSERT INTO APP_MENU_ROLE (MENU_ID, ROLE_ID)
SELECT m.ID, r.ID FROM APP_MENU m, APP_SEC_ROLE r
 WHERE r.CODE = 'ADM'
   AND m.CODE IN ('EXPEDIENTE_GENERAL','LABORATORIO','HISTORICO_EM','NOTA_MEDICA','NOTA_INCAPACIDAD',
                  'ARCHIVO_CONSULTAS','CONSULTA_MEDICA','INCAPACIDADES','ARCHIVO_INCAPACIDADES',
                  'EXAMEN_MEDICO','PRETEST','ANTIDOPING','ACCIDENTES','MATERNIDAD')
   AND NOT EXISTS (SELECT 1 FROM APP_MENU_ROLE x WHERE x.MENU_ID = m.ID AND x.ROLE_ID = r.ID);

-- USER: todo excepto Antidoping/Accidentes/Maternidad (equivalente al id_rol=1 real).
INSERT INTO APP_MENU_ROLE (MENU_ID, ROLE_ID)
SELECT m.ID, r.ID FROM APP_MENU m, APP_SEC_ROLE r
 WHERE r.CODE = 'USER'
   AND m.CODE IN ('EXPEDIENTE_GENERAL','LABORATORIO','HISTORICO_EM','NOTA_MEDICA','NOTA_INCAPACIDAD',
                  'ARCHIVO_CONSULTAS','CONSULTA_MEDICA','INCAPACIDADES','ARCHIVO_INCAPACIDADES',
                  'EXAMEN_MEDICO','PRETEST')
   AND NOT EXISTS (SELECT 1 FROM APP_MENU_ROLE x WHERE x.MENU_ID = m.ID AND x.ROLE_ID = r.ID);

-- ENFERMERO: sin Expediente General/Laboratorio ni Antidoping/Accidentes/Maternidad
-- (equivalente al id_rol=3 real).
INSERT INTO APP_MENU_ROLE (MENU_ID, ROLE_ID)
SELECT m.ID, r.ID FROM APP_MENU m, APP_SEC_ROLE r
 WHERE r.CODE = 'ENFERMERO'
   AND m.CODE IN ('HISTORICO_EM','NOTA_MEDICA','NOTA_INCAPACIDAD','ARCHIVO_CONSULTAS',
                  'CONSULTA_MEDICA','INCAPACIDADES','ARCHIVO_INCAPACIDADES','EXAMEN_MEDICO','PRETEST')
   AND NOT EXISTS (SELECT 1 FROM APP_MENU_ROLE x WHERE x.MENU_ID = m.ID AND x.ROLE_ID = r.ID);

COMMIT;

PROMPT ============================================================
PROMPT [CHECK] Verificacion post-ejecucion
PROMPT ============================================================
SELECT r.CODE role_code, COUNT(*) menus_asignados
  FROM APP_MENU_ROLE mr JOIN APP_SEC_ROLE r ON r.ID = mr.ROLE_ID
 GROUP BY r.CODE ORDER BY r.CODE;
